// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v5.27.3
// source: address.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "address";

export interface Address {
  address_id?: string | undefined;
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  district?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postal_code?: string | undefined;
  country?: string | undefined;
  landmark?: string | undefined;
  direction_url?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

export interface CreateAddressRequest {
  entity_type: string;
  entity_id: string;
  street: string;
  building: string;
  apartment: string;
  district: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
  landmark: string;
  direction_url: string;
  latitude: number;
  longitude: number;
}

export interface VerifyAddressRequest {
  entity_type: string;
  entity_id: string;
}

export interface CreateAddressResponse {
  address?: Address | undefined;
  status: boolean;
}

export interface AddressResponse {
  address?: Address | undefined;
  status: boolean;
}

export const ADDRESS_PACKAGE_NAME = "address";

function createBaseAddress(): Address {
  return {};
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address_id !== undefined) {
      writer.uint32(10).string(message.address_id);
    }
    if (message.street !== undefined) {
      writer.uint32(18).string(message.street);
    }
    if (message.building !== undefined) {
      writer.uint32(26).string(message.building);
    }
    if (message.apartment !== undefined) {
      writer.uint32(34).string(message.apartment);
    }
    if (message.district !== undefined) {
      writer.uint32(42).string(message.district);
    }
    if (message.city !== undefined) {
      writer.uint32(50).string(message.city);
    }
    if (message.state !== undefined) {
      writer.uint32(58).string(message.state);
    }
    if (message.postal_code !== undefined) {
      writer.uint32(66).string(message.postal_code);
    }
    if (message.country !== undefined) {
      writer.uint32(74).string(message.country);
    }
    if (message.landmark !== undefined) {
      writer.uint32(82).string(message.landmark);
    }
    if (message.direction_url !== undefined) {
      writer.uint32(90).string(message.direction_url);
    }
    if (message.latitude !== undefined) {
      writer.uint32(97).double(message.latitude);
    }
    if (message.longitude !== undefined) {
      writer.uint32(105).double(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.street = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.building = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.apartment = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.postal_code = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.landmark = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.direction_url = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.latitude = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 105) {
            break;
          }

          message.longitude = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateAddressRequest(): CreateAddressRequest {
  return {
    entity_type: "",
    entity_id: "",
    street: "",
    building: "",
    apartment: "",
    district: "",
    city: "",
    state: "",
    postal_code: "",
    country: "",
    landmark: "",
    direction_url: "",
    latitude: 0,
    longitude: 0,
  };
}

export const CreateAddressRequest: MessageFns<CreateAddressRequest> = {
  encode(message: CreateAddressRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity_type !== "") {
      writer.uint32(10).string(message.entity_type);
    }
    if (message.entity_id !== "") {
      writer.uint32(18).string(message.entity_id);
    }
    if (message.street !== "") {
      writer.uint32(26).string(message.street);
    }
    if (message.building !== "") {
      writer.uint32(34).string(message.building);
    }
    if (message.apartment !== "") {
      writer.uint32(42).string(message.apartment);
    }
    if (message.district !== "") {
      writer.uint32(50).string(message.district);
    }
    if (message.city !== "") {
      writer.uint32(58).string(message.city);
    }
    if (message.state !== "") {
      writer.uint32(66).string(message.state);
    }
    if (message.postal_code !== "") {
      writer.uint32(74).string(message.postal_code);
    }
    if (message.country !== "") {
      writer.uint32(82).string(message.country);
    }
    if (message.landmark !== "") {
      writer.uint32(90).string(message.landmark);
    }
    if (message.direction_url !== "") {
      writer.uint32(98).string(message.direction_url);
    }
    if (message.latitude !== 0) {
      writer.uint32(105).double(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(113).double(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAddressRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAddressRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity_type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entity_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.street = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.building = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.apartment = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.postal_code = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.landmark = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.direction_url = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 105) {
            break;
          }

          message.latitude = reader.double();
          continue;
        }
        case 14: {
          if (tag !== 113) {
            break;
          }

          message.longitude = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVerifyAddressRequest(): VerifyAddressRequest {
  return { entity_type: "", entity_id: "" };
}

export const VerifyAddressRequest: MessageFns<VerifyAddressRequest> = {
  encode(message: VerifyAddressRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity_type !== "") {
      writer.uint32(10).string(message.entity_type);
    }
    if (message.entity_id !== "") {
      writer.uint32(18).string(message.entity_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyAddressRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyAddressRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity_type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entity_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateAddressResponse(): CreateAddressResponse {
  return { status: false };
}

export const CreateAddressResponse: MessageFns<CreateAddressResponse> = {
  encode(message: CreateAddressResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(10).fork()).join();
    }
    if (message.status !== false) {
      writer.uint32(16).bool(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateAddressResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateAddressResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddressResponse(): AddressResponse {
  return { status: false };
}

export const AddressResponse: MessageFns<AddressResponse> = {
  encode(message: AddressResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(10).fork()).join();
    }
    if (message.status !== false) {
      writer.uint32(16).bool(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddressResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddressResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** 📁 Files Service - handles file uploads, storage, and management */

export interface AddressServiceClient {
  verifyAddress(request: VerifyAddressRequest): Observable<AddressResponse>;

  createOrUpdateAddress(request: CreateAddressRequest): Observable<AddressResponse>;
}

/** 📁 Files Service - handles file uploads, storage, and management */

export interface AddressServiceController {
  verifyAddress(
    request: VerifyAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  createOrUpdateAddress(
    request: CreateAddressRequest,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;
}

export function AddressServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["verifyAddress", "createOrUpdateAddress"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AddressService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AddressService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ADDRESS_SERVICE_NAME = "AddressService";

/** 📁 Files Service - handles file uploads, storage, and management */
export type AddressServiceService = typeof AddressServiceService;
export const AddressServiceService = {
  verifyAddress: {
    path: "/address.AddressService/VerifyAddress",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VerifyAddressRequest): Buffer => Buffer.from(VerifyAddressRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyAddressRequest => VerifyAddressRequest.decode(value),
    responseSerialize: (value: AddressResponse): Buffer => Buffer.from(AddressResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddressResponse => AddressResponse.decode(value),
  },
  createOrUpdateAddress: {
    path: "/address.AddressService/CreateOrUpdateAddress",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateAddressRequest): Buffer => Buffer.from(CreateAddressRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateAddressRequest => CreateAddressRequest.decode(value),
    responseSerialize: (value: AddressResponse): Buffer => Buffer.from(AddressResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddressResponse => AddressResponse.decode(value),
  },
} as const;

export interface AddressServiceServer extends UntypedServiceImplementation {
  verifyAddress: handleUnaryCall<VerifyAddressRequest, AddressResponse>;
  createOrUpdateAddress: handleUnaryCall<CreateAddressRequest, AddressResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
