// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: admin.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "admin";

export enum rolesEnum {
  CLIENT = 0,
  BUSINESS_USER = 1,
  STAFF = 2,
  UNRECOGNIZED = -1,
}

export enum SendOtpType {
  REGISTRATION = 0,
  SIGNIN = 1,
  ADMIN_REGISTRATION = 2,
  ADMIN_SIGNIN = 3,
  FORGOT_PASSWORD = 4,
  UNRECOGNIZED = -1,
}

export interface FetchAllAdminResponse {
  users: User[];
  success: boolean;
  message: string;
}

export interface FetchAdminAccountRequest {
  userId: string;
}

export interface ValidateAdminAccountRequest {
  token: string;
}

export interface FetchAdminAccountResponse {
  user: User | undefined;
  success: boolean;
  message: string;
}

export interface EmptyRequest {
}

export interface Role {
  roleId: string;
  roleName: string;
  isActive: boolean;
}

export interface VerifyOtpResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  accessToken?: string | undefined;
  user?: User | undefined;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface SendOtpRequest {
  token: string;
  type: SendOtpType;
}

export interface VerifyOtpRequest {
  token: string;
  otp: string;
  type: SendOtpType;
}

export interface SendOtpResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
}

export interface RefreshTokenResponse {
  success: boolean;
  user: User | undefined;
  accessToken: string;
}

export interface AuthInitialResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  authToken?: string | undefined;
}

export interface AdminRegisterRequest {
  email: string;
  password: string;
  platformRef: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  phoneNumber: string;
  companyRef: string;
  roleName: string;
}

export interface LogoutRequest {
  userId: string;
}

export interface RefreshTokenRequest {
  userId: string;
}

export interface GetUserRequest {
  userId: string;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface UserResponse {
  success: boolean;
  error?: string | undefined;
  user?: User | undefined;
}

export interface GetUserByEmailResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  user?: User | undefined;
}

export interface GetUserContactsResponse {
  success: boolean;
  error?: string | undefined;
  contacts: Contact[];
  totalCount: number;
}

export interface User {
  userId: string;
  email: string;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  phoneNumber?: string | undefined;
  avatarUrl?: string | undefined;
  lastSeen?: string | undefined;
  createdAt: string;
  updatedAt: string;
  emailVerified: boolean;
  address?: Address | undefined;
}

export interface Contact {
  userId: string;
  email: string;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  avatarUrl?: string | undefined;
  lastSeen?: string | undefined;
  emailVerified: boolean;
}

export interface Organization {
  organizationId: string;
  name: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
  creatorId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface Address {
  addressId?: string | undefined;
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  district?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  landmark?: string | undefined;
  directionUrl?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

export interface UserRole {
  userRoleId: string;
  roleName: string;
  isActive: boolean;
}

export const ADMIN_PACKAGE_NAME = "admin";

/** 👤 Profile Service - handles user profiles and user management */

export interface AdminServiceClient {
  /** admin services */

  adminRegister(request: AdminRegisterRequest): Observable<AuthInitialResponse>;

  adminLogin(request: LoginRequest): Observable<AuthInitialResponse>;

  adminLogout(request: LogoutRequest): Observable<SendOtpResponse>;

  adminSendOtp(request: SendOtpRequest): Observable<SendOtpResponse>;

  adminVerifyOtp(request: VerifyOtpRequest): Observable<VerifyOtpResponse>;

  adminRefreshToken(request: RefreshTokenRequest): Observable<RefreshTokenResponse>;

  fetchAllAdmin(request: FetchAdminAccountRequest): Observable<FetchAllAdminResponse>;

  fetchAdminAccount(request: FetchAdminAccountRequest): Observable<FetchAdminAccountResponse>;

  validateAdminAccount(request: ValidateAdminAccountRequest): Observable<FetchAdminAccountResponse>;

  getUser(request: GetUserRequest): Observable<UserResponse>;
}

/** 👤 Profile Service - handles user profiles and user management */

export interface AdminServiceController {
  /** admin services */

  adminRegister(
    request: AdminRegisterRequest,
  ): Promise<AuthInitialResponse> | Observable<AuthInitialResponse> | AuthInitialResponse;

  adminLogin(
    request: LoginRequest,
  ): Promise<AuthInitialResponse> | Observable<AuthInitialResponse> | AuthInitialResponse;

  adminLogout(request: LogoutRequest): Promise<SendOtpResponse> | Observable<SendOtpResponse> | SendOtpResponse;

  adminSendOtp(request: SendOtpRequest): Promise<SendOtpResponse> | Observable<SendOtpResponse> | SendOtpResponse;

  adminVerifyOtp(
    request: VerifyOtpRequest,
  ): Promise<VerifyOtpResponse> | Observable<VerifyOtpResponse> | VerifyOtpResponse;

  adminRefreshToken(
    request: RefreshTokenRequest,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;

  fetchAllAdmin(
    request: FetchAdminAccountRequest,
  ): Promise<FetchAllAdminResponse> | Observable<FetchAllAdminResponse> | FetchAllAdminResponse;

  fetchAdminAccount(
    request: FetchAdminAccountRequest,
  ): Promise<FetchAdminAccountResponse> | Observable<FetchAdminAccountResponse> | FetchAdminAccountResponse;

  validateAdminAccount(
    request: ValidateAdminAccountRequest,
  ): Promise<FetchAdminAccountResponse> | Observable<FetchAdminAccountResponse> | FetchAdminAccountResponse;

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function AdminServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "adminRegister",
      "adminLogin",
      "adminLogout",
      "adminSendOtp",
      "adminVerifyOtp",
      "adminRefreshToken",
      "fetchAllAdmin",
      "fetchAdminAccount",
      "validateAdminAccount",
      "getUser",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AdminService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AdminService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ADMIN_SERVICE_NAME = "AdminService";
