// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v5.27.3
// source: communication.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleServerStreamingCall, handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "communication";

export enum SendOtpType {
  REGISTRATION = 0,
  SIGNIN = 1,
  UNRECOGNIZED = -1,
}

export enum ChatType {
  CHAT_TYPE_DIRECT = 0,
  CHAT_TYPE_GROUP = 1,
  CHAT_TYPE_CHANNEL = 2,
  UNRECOGNIZED = -1,
}

export enum ChatStatus {
  CHAT_STATUS_PENDING = 0,
  CHAT_STATUS_ACTIVE = 1,
  CHAT_STATUS_ARCHIVED = 2,
  CHAT_STATUS_DELETED = 3,
  UNRECOGNIZED = -1,
}

export enum MessageType {
  MESSAGE_TYPE_TEXT = 0,
  MESSAGE_TYPE_IMAGE = 1,
  MESSAGE_TYPE_VIDEO = 2,
  MESSAGE_TYPE_AUDIO = 3,
  MESSAGE_TYPE_FILE = 4,
  MESSAGE_TYPE_VOICE_NOTE = 5,
  MESSAGE_TYPE_SYSTEM = 6,
  UNRECOGNIZED = -1,
}

export enum MessageStatus {
  MESSAGE_STATUS_PENDING = 0,
  MESSAGE_STATUS_SENT = 1,
  MESSAGE_STATUS_DELIVERED = 2,
  MESSAGE_STATUS_READ = 3,
  MESSAGE_STATUS_FAILED = 4,
  UNRECOGNIZED = -1,
}

export interface SendOtpMailRequest {
  email: string;
  name: string;
  otp: string;
  type: SendOtpType;
}

export interface ClearUserPushSubscriptionsRequest {
  user_id: string;
}

export interface ClearUserPushSubscriptionsResponse {
  success: boolean;
}

export interface CreateChatRequest {
  name: string;
  chat_type: ChatType;
  creator_id: string;
  participant_ids: string[];
  avatar_url?: string | undefined;
}

export interface GetChatRequest {
  chat_id: string;
  user_id: string;
}

export interface GetUserChatsRequest {
  user_id: string;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface UpdateChatRequest {
  chat_id: string;
  user_id: string;
  name?: string | undefined;
  avatar_url?: string | undefined;
  status?: ChatStatus | undefined;
}

export interface DeleteChatRequest {
  chat_id: string;
  user_id: string;
}

export interface SendMessageRequest {
  chat_id: string;
  sender_id: string;
  content: string;
  type: MessageType;
  media_urls: string[];
  file_url?: string | undefined;
  file_size?: number | undefined;
  file_type?: string | undefined;
  duration?: number | undefined;
}

export interface GetMessagesRequest {
  chat_id: string;
  user_id: string;
  limit?: number | undefined;
  offset?: number | undefined;
  before_message_id?: string | undefined;
  after_message_id?: string | undefined;
}

export interface UpdateMessageRequest {
  message_id: string;
  user_id: string;
  content?: string | undefined;
  media_urls: string[];
}

export interface DeleteMessageRequest {
  message_id: string;
  user_id: string;
}

export interface AddParticipantRequest {
  chat_id: string;
  user_id: string;
  new_participant_id: string;
  is_admin?: boolean | undefined;
}

export interface RemoveParticipantRequest {
  chat_id: string;
  user_id: string;
  participant_id: string;
}

export interface GetParticipantsRequest {
  chat_id: string;
  user_id: string;
}

export interface MarkAsReadRequest {
  chat_id: string;
  user_id: string;
  message_ids: string[];
}

export interface GetUnreadCountsRequest {
  user_id: string;
  chat_ids: string[];
}

export interface ChatEventsRequest {
  user_id: string;
  chat_ids: string[];
}

export interface ChatResponse {
  success: boolean;
  error?: string | undefined;
  chat?: Chat | undefined;
}

export interface GetUserChatsResponse {
  success: boolean;
  error?: string | undefined;
  chats: ChatWithDetails[];
  total_count: number;
}

export interface DeleteChatResponse {
  success: boolean;
  error?: string | undefined;
  chat_id: string;
}

export interface SendOtpMailResponse {
  success: boolean;
  error?: string | undefined;
}

export interface MessageResponse {
  success: boolean;
  error?: string | undefined;
  message?: Message | undefined;
}

export interface GetMessagesResponse {
  success: boolean;
  error?: string | undefined;
  messages: Message[];
  total_count: number;
  next_cursor?: string | undefined;
}

export interface DeleteMessageResponse {
  success: boolean;
  error?: string | undefined;
  message_id: string;
}

export interface ParticipantResponse {
  success: boolean;
  error?: string | undefined;
  participant?: ChatParticipant | undefined;
}

export interface GetParticipantsResponse {
  success: boolean;
  error?: string | undefined;
  participants: ChatParticipant[];
}

export interface MarkAsReadResponse {
  success: boolean;
  error?: string | undefined;
  marked_count: number;
}

export interface GetUnreadCountsResponse {
  success: boolean;
  error?: string | undefined;
  unread_counts: UnreadCount[];
}

export interface ChatEventResponse {
  event_type: string;
  chat_id: string;
  message?: Message | undefined;
  participant?: ChatParticipant | undefined;
  chat?: Chat | undefined;
  timestamp: string;
}

export interface Chat {
  chat_id: string;
  name?: string | undefined;
  avatar_url?: string | undefined;
  chat_type: ChatType;
  status: ChatStatus;
  created_at: string;
  updated_at: string;
  deleted_at?: string | undefined;
}

export interface ChatWithDetails {
  chat_id: string;
  name?: string | undefined;
  avatar_url?: string | undefined;
  chat_type: ChatType;
  status: ChatStatus;
  is_admin: boolean;
  joined_at: string;
  last_message?: Message | undefined;
  unread_count: number;
  participant_count: number;
  created_at: string;
  updated_at: string;
}

export interface Message {
  message_id: string;
  chat_id: string;
  sender_id: string;
  content: string;
  media_urls: string[];
  type: MessageType;
  status: MessageStatus;
  created_at: string;
  updated_at: string;
  deleted_at?: string | undefined;
  duration?: number | undefined;
  file_url?: string | undefined;
  file_size?: number | undefined;
  file_type?: string | undefined;
}

export interface ChatParticipant {
  chat_id: string;
  user_id: string;
  joined_at: string;
  is_admin: boolean;
  is_active: boolean;
  unread_count: number;
}

export interface UnreadCount {
  chat_id: string;
  count: number;
  last_read_at: string;
}

export const COMMUNICATION_PACKAGE_NAME = "communication";

function createBaseSendOtpMailRequest(): SendOtpMailRequest {
  return { email: "", name: "", otp: "", type: 0 };
}

export const SendOtpMailRequest: MessageFns<SendOtpMailRequest> = {
  encode(message: SendOtpMailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.otp !== "") {
      writer.uint32(26).string(message.otp);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendOtpMailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendOtpMailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.otp = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseClearUserPushSubscriptionsRequest(): ClearUserPushSubscriptionsRequest {
  return { user_id: "" };
}

export const ClearUserPushSubscriptionsRequest: MessageFns<ClearUserPushSubscriptionsRequest> = {
  encode(message: ClearUserPushSubscriptionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearUserPushSubscriptionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearUserPushSubscriptionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseClearUserPushSubscriptionsResponse(): ClearUserPushSubscriptionsResponse {
  return { success: false };
}

export const ClearUserPushSubscriptionsResponse: MessageFns<ClearUserPushSubscriptionsResponse> = {
  encode(message: ClearUserPushSubscriptionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearUserPushSubscriptionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearUserPushSubscriptionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateChatRequest(): CreateChatRequest {
  return { name: "", chat_type: 0, creator_id: "", participant_ids: [] };
}

export const CreateChatRequest: MessageFns<CreateChatRequest> = {
  encode(message: CreateChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.chat_type !== 0) {
      writer.uint32(16).int32(message.chat_type);
    }
    if (message.creator_id !== "") {
      writer.uint32(26).string(message.creator_id);
    }
    for (const v of message.participant_ids) {
      writer.uint32(34).string(v!);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(42).string(message.avatar_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.chat_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.creator_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.participant_ids.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetChatRequest(): GetChatRequest {
  return { chat_id: "", user_id: "" };
}

export const GetChatRequest: MessageFns<GetChatRequest> = {
  encode(message: GetChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserChatsRequest(): GetUserChatsRequest {
  return { user_id: "" };
}

export const GetUserChatsRequest: MessageFns<GetUserChatsRequest> = {
  encode(message: GetUserChatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.limit !== undefined) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(24).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserChatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserChatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateChatRequest(): UpdateChatRequest {
  return { chat_id: "", user_id: "" };
}

export const UpdateChatRequest: MessageFns<UpdateChatRequest> = {
  encode(message: UpdateChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(34).string(message.avatar_url);
    }
    if (message.status !== undefined) {
      writer.uint32(40).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteChatRequest(): DeleteChatRequest {
  return { chat_id: "", user_id: "" };
}

export const DeleteChatRequest: MessageFns<DeleteChatRequest> = {
  encode(message: DeleteChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSendMessageRequest(): SendMessageRequest {
  return { chat_id: "", sender_id: "", content: "", type: 0, media_urls: [] };
}

export const SendMessageRequest: MessageFns<SendMessageRequest> = {
  encode(message: SendMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.sender_id !== "") {
      writer.uint32(18).string(message.sender_id);
    }
    if (message.content !== "") {
      writer.uint32(26).string(message.content);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    for (const v of message.media_urls) {
      writer.uint32(42).string(v!);
    }
    if (message.file_url !== undefined) {
      writer.uint32(50).string(message.file_url);
    }
    if (message.file_size !== undefined) {
      writer.uint32(56).int64(message.file_size);
    }
    if (message.file_type !== undefined) {
      writer.uint32(66).string(message.file_type);
    }
    if (message.duration !== undefined) {
      writer.uint32(72).int32(message.duration);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sender_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.media_urls.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.file_size = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.file_type = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetMessagesRequest(): GetMessagesRequest {
  return { chat_id: "", user_id: "" };
}

export const GetMessagesRequest: MessageFns<GetMessagesRequest> = {
  encode(message: GetMessagesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.limit !== undefined) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(32).int32(message.offset);
    }
    if (message.before_message_id !== undefined) {
      writer.uint32(42).string(message.before_message_id);
    }
    if (message.after_message_id !== undefined) {
      writer.uint32(50).string(message.after_message_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMessagesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMessagesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.before_message_id = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.after_message_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateMessageRequest(): UpdateMessageRequest {
  return { message_id: "", user_id: "", media_urls: [] };
}

export const UpdateMessageRequest: MessageFns<UpdateMessageRequest> = {
  encode(message: UpdateMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message_id !== "") {
      writer.uint32(10).string(message.message_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.content !== undefined) {
      writer.uint32(26).string(message.content);
    }
    for (const v of message.media_urls) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.media_urls.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteMessageRequest(): DeleteMessageRequest {
  return { message_id: "", user_id: "" };
}

export const DeleteMessageRequest: MessageFns<DeleteMessageRequest> = {
  encode(message: DeleteMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message_id !== "") {
      writer.uint32(10).string(message.message_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddParticipantRequest(): AddParticipantRequest {
  return { chat_id: "", user_id: "", new_participant_id: "" };
}

export const AddParticipantRequest: MessageFns<AddParticipantRequest> = {
  encode(message: AddParticipantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.new_participant_id !== "") {
      writer.uint32(26).string(message.new_participant_id);
    }
    if (message.is_admin !== undefined) {
      writer.uint32(32).bool(message.is_admin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddParticipantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddParticipantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.new_participant_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_admin = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoveParticipantRequest(): RemoveParticipantRequest {
  return { chat_id: "", user_id: "", participant_id: "" };
}

export const RemoveParticipantRequest: MessageFns<RemoveParticipantRequest> = {
  encode(message: RemoveParticipantRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.participant_id !== "") {
      writer.uint32(26).string(message.participant_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveParticipantRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveParticipantRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.participant_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetParticipantsRequest(): GetParticipantsRequest {
  return { chat_id: "", user_id: "" };
}

export const GetParticipantsRequest: MessageFns<GetParticipantsRequest> = {
  encode(message: GetParticipantsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetParticipantsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetParticipantsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMarkAsReadRequest(): MarkAsReadRequest {
  return { chat_id: "", user_id: "", message_ids: [] };
}

export const MarkAsReadRequest: MessageFns<MarkAsReadRequest> = {
  encode(message: MarkAsReadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    for (const v of message.message_ids) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarkAsReadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkAsReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message_ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUnreadCountsRequest(): GetUnreadCountsRequest {
  return { user_id: "", chat_ids: [] };
}

export const GetUnreadCountsRequest: MessageFns<GetUnreadCountsRequest> = {
  encode(message: GetUnreadCountsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    for (const v of message.chat_ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUnreadCountsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUnreadCountsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chat_ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChatEventsRequest(): ChatEventsRequest {
  return { user_id: "", chat_ids: [] };
}

export const ChatEventsRequest: MessageFns<ChatEventsRequest> = {
  encode(message: ChatEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    for (const v of message.chat_ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chat_ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChatResponse(): ChatResponse {
  return { success: false };
}

export const ChatResponse: MessageFns<ChatResponse> = {
  encode(message: ChatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.chat !== undefined) {
      Chat.encode(message.chat, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chat = Chat.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserChatsResponse(): GetUserChatsResponse {
  return { success: false, chats: [], total_count: 0 };
}

export const GetUserChatsResponse: MessageFns<GetUserChatsResponse> = {
  encode(message: GetUserChatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.chats) {
      ChatWithDetails.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total_count !== 0) {
      writer.uint32(32).int32(message.total_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserChatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserChatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chats.push(ChatWithDetails.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total_count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteChatResponse(): DeleteChatResponse {
  return { success: false, chat_id: "" };
}

export const DeleteChatResponse: MessageFns<DeleteChatResponse> = {
  encode(message: DeleteChatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.chat_id !== "") {
      writer.uint32(26).string(message.chat_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteChatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteChatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSendOtpMailResponse(): SendOtpMailResponse {
  return { success: false };
}

export const SendOtpMailResponse: MessageFns<SendOtpMailResponse> = {
  encode(message: SendOtpMailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendOtpMailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendOtpMailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMessageResponse(): MessageResponse {
  return { success: false };
}

export const MessageResponse: MessageFns<MessageResponse> = {
  encode(message: MessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.message !== undefined) {
      Message.encode(message.message, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = Message.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetMessagesResponse(): GetMessagesResponse {
  return { success: false, messages: [], total_count: 0 };
}

export const GetMessagesResponse: MessageFns<GetMessagesResponse> = {
  encode(message: GetMessagesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.messages) {
      Message.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total_count !== 0) {
      writer.uint32(32).int32(message.total_count);
    }
    if (message.next_cursor !== undefined) {
      writer.uint32(42).string(message.next_cursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMessagesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMessagesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total_count = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.next_cursor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteMessageResponse(): DeleteMessageResponse {
  return { success: false, message_id: "" };
}

export const DeleteMessageResponse: MessageFns<DeleteMessageResponse> = {
  encode(message: DeleteMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.message_id !== "") {
      writer.uint32(26).string(message.message_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseParticipantResponse(): ParticipantResponse {
  return { success: false };
}

export const ParticipantResponse: MessageFns<ParticipantResponse> = {
  encode(message: ParticipantResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.participant !== undefined) {
      ChatParticipant.encode(message.participant, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParticipantResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParticipantResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.participant = ChatParticipant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetParticipantsResponse(): GetParticipantsResponse {
  return { success: false, participants: [] };
}

export const GetParticipantsResponse: MessageFns<GetParticipantsResponse> = {
  encode(message: GetParticipantsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.participants) {
      ChatParticipant.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetParticipantsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetParticipantsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.participants.push(ChatParticipant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMarkAsReadResponse(): MarkAsReadResponse {
  return { success: false, marked_count: 0 };
}

export const MarkAsReadResponse: MessageFns<MarkAsReadResponse> = {
  encode(message: MarkAsReadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.marked_count !== 0) {
      writer.uint32(24).int32(message.marked_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarkAsReadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkAsReadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.marked_count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUnreadCountsResponse(): GetUnreadCountsResponse {
  return { success: false, unread_counts: [] };
}

export const GetUnreadCountsResponse: MessageFns<GetUnreadCountsResponse> = {
  encode(message: GetUnreadCountsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.unread_counts) {
      UnreadCount.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUnreadCountsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUnreadCountsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.unread_counts.push(UnreadCount.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChatEventResponse(): ChatEventResponse {
  return { event_type: "", chat_id: "", timestamp: "" };
}

export const ChatEventResponse: MessageFns<ChatEventResponse> = {
  encode(message: ChatEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event_type !== "") {
      writer.uint32(10).string(message.event_type);
    }
    if (message.chat_id !== "") {
      writer.uint32(18).string(message.chat_id);
    }
    if (message.message !== undefined) {
      Message.encode(message.message, writer.uint32(26).fork()).join();
    }
    if (message.participant !== undefined) {
      ChatParticipant.encode(message.participant, writer.uint32(34).fork()).join();
    }
    if (message.chat !== undefined) {
      Chat.encode(message.chat, writer.uint32(42).fork()).join();
    }
    if (message.timestamp !== "") {
      writer.uint32(50).string(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event_type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = Message.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.participant = ChatParticipant.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.chat = Chat.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChat(): Chat {
  return { chat_id: "", chat_type: 0, status: 0, created_at: "", updated_at: "" };
}

export const Chat: MessageFns<Chat> = {
  encode(message: Chat, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(26).string(message.avatar_url);
    }
    if (message.chat_type !== 0) {
      writer.uint32(32).int32(message.chat_type);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.created_at !== "") {
      writer.uint32(50).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(58).string(message.updated_at);
    }
    if (message.deleted_at !== undefined) {
      writer.uint32(66).string(message.deleted_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Chat {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chat_type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.deleted_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChatWithDetails(): ChatWithDetails {
  return {
    chat_id: "",
    chat_type: 0,
    status: 0,
    is_admin: false,
    joined_at: "",
    unread_count: 0,
    participant_count: 0,
    created_at: "",
    updated_at: "",
  };
}

export const ChatWithDetails: MessageFns<ChatWithDetails> = {
  encode(message: ChatWithDetails, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(26).string(message.avatar_url);
    }
    if (message.chat_type !== 0) {
      writer.uint32(32).int32(message.chat_type);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.is_admin !== false) {
      writer.uint32(48).bool(message.is_admin);
    }
    if (message.joined_at !== "") {
      writer.uint32(58).string(message.joined_at);
    }
    if (message.last_message !== undefined) {
      Message.encode(message.last_message, writer.uint32(66).fork()).join();
    }
    if (message.unread_count !== 0) {
      writer.uint32(72).int32(message.unread_count);
    }
    if (message.participant_count !== 0) {
      writer.uint32(80).int32(message.participant_count);
    }
    if (message.created_at !== "") {
      writer.uint32(90).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(98).string(message.updated_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatWithDetails {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatWithDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chat_type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.is_admin = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.joined_at = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.last_message = Message.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.unread_count = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.participant_count = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMessage(): Message {
  return {
    message_id: "",
    chat_id: "",
    sender_id: "",
    content: "",
    media_urls: [],
    type: 0,
    status: 0,
    created_at: "",
    updated_at: "",
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message_id !== "") {
      writer.uint32(10).string(message.message_id);
    }
    if (message.chat_id !== "") {
      writer.uint32(18).string(message.chat_id);
    }
    if (message.sender_id !== "") {
      writer.uint32(26).string(message.sender_id);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    for (const v of message.media_urls) {
      writer.uint32(42).string(v!);
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.created_at !== "") {
      writer.uint32(66).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(74).string(message.updated_at);
    }
    if (message.deleted_at !== undefined) {
      writer.uint32(82).string(message.deleted_at);
    }
    if (message.duration !== undefined) {
      writer.uint32(88).int32(message.duration);
    }
    if (message.file_url !== undefined) {
      writer.uint32(98).string(message.file_url);
    }
    if (message.file_size !== undefined) {
      writer.uint32(104).int64(message.file_size);
    }
    if (message.file_type !== undefined) {
      writer.uint32(114).string(message.file_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sender_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.media_urls.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.deleted_at = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.file_size = longToNumber(reader.int64());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.file_type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseChatParticipant(): ChatParticipant {
  return { chat_id: "", user_id: "", joined_at: "", is_admin: false, is_active: false, unread_count: 0 };
}

export const ChatParticipant: MessageFns<ChatParticipant> = {
  encode(message: ChatParticipant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.joined_at !== "") {
      writer.uint32(26).string(message.joined_at);
    }
    if (message.is_admin !== false) {
      writer.uint32(32).bool(message.is_admin);
    }
    if (message.is_active !== false) {
      writer.uint32(40).bool(message.is_active);
    }
    if (message.unread_count !== 0) {
      writer.uint32(48).int32(message.unread_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatParticipant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatParticipant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.joined_at = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.is_admin = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.is_active = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.unread_count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUnreadCount(): UnreadCount {
  return { chat_id: "", count: 0, last_read_at: "" };
}

export const UnreadCount: MessageFns<UnreadCount> = {
  encode(message: UnreadCount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chat_id !== "") {
      writer.uint32(10).string(message.chat_id);
    }
    if (message.count !== 0) {
      writer.uint32(16).int32(message.count);
    }
    if (message.last_read_at !== "") {
      writer.uint32(26).string(message.last_read_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnreadCount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnreadCount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chat_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.last_read_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** 💬 Communication Service - handles chats, messages, and real-time communication */

export interface CommunicationServiceClient {
  /** Chat Management */

  createChat(request: CreateChatRequest): Observable<ChatResponse>;

  getChat(request: GetChatRequest): Observable<ChatResponse>;

  getUserChats(request: GetUserChatsRequest): Observable<GetUserChatsResponse>;

  updateChat(request: UpdateChatRequest): Observable<ChatResponse>;

  deleteChat(request: DeleteChatRequest): Observable<DeleteChatResponse>;

  /** Message Management */

  sendMessage(request: SendMessageRequest): Observable<MessageResponse>;

  getMessages(request: GetMessagesRequest): Observable<GetMessagesResponse>;

  updateMessage(request: UpdateMessageRequest): Observable<MessageResponse>;

  deleteMessage(request: DeleteMessageRequest): Observable<DeleteMessageResponse>;

  /** Chat Participants */

  addParticipant(request: AddParticipantRequest): Observable<ParticipantResponse>;

  removeParticipant(request: RemoveParticipantRequest): Observable<ParticipantResponse>;

  getParticipants(request: GetParticipantsRequest): Observable<GetParticipantsResponse>;

  /** Message Status & Read Receipts */

  markMessagesAsRead(request: MarkAsReadRequest): Observable<MarkAsReadResponse>;

  getUnreadCounts(request: GetUnreadCountsRequest): Observable<GetUnreadCountsResponse>;

  /** Real-time subscriptions (for WebSocket events) */

  getChatEvents(request: ChatEventsRequest): Observable<ChatEventResponse>;

  /** Mail Management */

  sendOtpMail(request: SendOtpMailRequest): Observable<SendOtpMailResponse>;

  /** Push Notifications */

  clearUserPushSubscriptions(
    request: ClearUserPushSubscriptionsRequest,
  ): Observable<ClearUserPushSubscriptionsResponse>;
}

/** 💬 Communication Service - handles chats, messages, and real-time communication */

export interface CommunicationServiceController {
  /** Chat Management */

  createChat(request: CreateChatRequest): Promise<ChatResponse> | Observable<ChatResponse> | ChatResponse;

  getChat(request: GetChatRequest): Promise<ChatResponse> | Observable<ChatResponse> | ChatResponse;

  getUserChats(
    request: GetUserChatsRequest,
  ): Promise<GetUserChatsResponse> | Observable<GetUserChatsResponse> | GetUserChatsResponse;

  updateChat(request: UpdateChatRequest): Promise<ChatResponse> | Observable<ChatResponse> | ChatResponse;

  deleteChat(
    request: DeleteChatRequest,
  ): Promise<DeleteChatResponse> | Observable<DeleteChatResponse> | DeleteChatResponse;

  /** Message Management */

  sendMessage(request: SendMessageRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getMessages(
    request: GetMessagesRequest,
  ): Promise<GetMessagesResponse> | Observable<GetMessagesResponse> | GetMessagesResponse;

  updateMessage(
    request: UpdateMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  deleteMessage(
    request: DeleteMessageRequest,
  ): Promise<DeleteMessageResponse> | Observable<DeleteMessageResponse> | DeleteMessageResponse;

  /** Chat Participants */

  addParticipant(
    request: AddParticipantRequest,
  ): Promise<ParticipantResponse> | Observable<ParticipantResponse> | ParticipantResponse;

  removeParticipant(
    request: RemoveParticipantRequest,
  ): Promise<ParticipantResponse> | Observable<ParticipantResponse> | ParticipantResponse;

  getParticipants(
    request: GetParticipantsRequest,
  ): Promise<GetParticipantsResponse> | Observable<GetParticipantsResponse> | GetParticipantsResponse;

  /** Message Status & Read Receipts */

  markMessagesAsRead(
    request: MarkAsReadRequest,
  ): Promise<MarkAsReadResponse> | Observable<MarkAsReadResponse> | MarkAsReadResponse;

  getUnreadCounts(
    request: GetUnreadCountsRequest,
  ): Promise<GetUnreadCountsResponse> | Observable<GetUnreadCountsResponse> | GetUnreadCountsResponse;

  /** Real-time subscriptions (for WebSocket events) */

  getChatEvents(request: ChatEventsRequest): Observable<ChatEventResponse>;

  /** Mail Management */

  sendOtpMail(
    request: SendOtpMailRequest,
  ): Promise<SendOtpMailResponse> | Observable<SendOtpMailResponse> | SendOtpMailResponse;

  /** Push Notifications */

  clearUserPushSubscriptions(
    request: ClearUserPushSubscriptionsRequest,
  ):
    | Promise<ClearUserPushSubscriptionsResponse>
    | Observable<ClearUserPushSubscriptionsResponse>
    | ClearUserPushSubscriptionsResponse;
}

export function CommunicationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createChat",
      "getChat",
      "getUserChats",
      "updateChat",
      "deleteChat",
      "sendMessage",
      "getMessages",
      "updateMessage",
      "deleteMessage",
      "addParticipant",
      "removeParticipant",
      "getParticipants",
      "markMessagesAsRead",
      "getUnreadCounts",
      "getChatEvents",
      "sendOtpMail",
      "clearUserPushSubscriptions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CommunicationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CommunicationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMMUNICATION_SERVICE_NAME = "CommunicationService";

/** 💬 Communication Service - handles chats, messages, and real-time communication */
export type CommunicationServiceService = typeof CommunicationServiceService;
export const CommunicationServiceService = {
  /** Chat Management */
  createChat: {
    path: "/communication.CommunicationService/CreateChat",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateChatRequest): Buffer => Buffer.from(CreateChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateChatRequest => CreateChatRequest.decode(value),
    responseSerialize: (value: ChatResponse): Buffer => Buffer.from(ChatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatResponse => ChatResponse.decode(value),
  },
  getChat: {
    path: "/communication.CommunicationService/GetChat",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetChatRequest): Buffer => Buffer.from(GetChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetChatRequest => GetChatRequest.decode(value),
    responseSerialize: (value: ChatResponse): Buffer => Buffer.from(ChatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatResponse => ChatResponse.decode(value),
  },
  getUserChats: {
    path: "/communication.CommunicationService/GetUserChats",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserChatsRequest): Buffer => Buffer.from(GetUserChatsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserChatsRequest => GetUserChatsRequest.decode(value),
    responseSerialize: (value: GetUserChatsResponse): Buffer =>
      Buffer.from(GetUserChatsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserChatsResponse => GetUserChatsResponse.decode(value),
  },
  updateChat: {
    path: "/communication.CommunicationService/UpdateChat",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateChatRequest): Buffer => Buffer.from(UpdateChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateChatRequest => UpdateChatRequest.decode(value),
    responseSerialize: (value: ChatResponse): Buffer => Buffer.from(ChatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatResponse => ChatResponse.decode(value),
  },
  deleteChat: {
    path: "/communication.CommunicationService/DeleteChat",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteChatRequest): Buffer => Buffer.from(DeleteChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteChatRequest => DeleteChatRequest.decode(value),
    responseSerialize: (value: DeleteChatResponse): Buffer => Buffer.from(DeleteChatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteChatResponse => DeleteChatResponse.decode(value),
  },
  /** Message Management */
  sendMessage: {
    path: "/communication.CommunicationService/SendMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendMessageRequest): Buffer => Buffer.from(SendMessageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendMessageRequest => SendMessageRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  getMessages: {
    path: "/communication.CommunicationService/GetMessages",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetMessagesRequest): Buffer => Buffer.from(GetMessagesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetMessagesRequest => GetMessagesRequest.decode(value),
    responseSerialize: (value: GetMessagesResponse): Buffer => Buffer.from(GetMessagesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetMessagesResponse => GetMessagesResponse.decode(value),
  },
  updateMessage: {
    path: "/communication.CommunicationService/UpdateMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateMessageRequest): Buffer => Buffer.from(UpdateMessageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateMessageRequest => UpdateMessageRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  deleteMessage: {
    path: "/communication.CommunicationService/DeleteMessage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteMessageRequest): Buffer => Buffer.from(DeleteMessageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteMessageRequest => DeleteMessageRequest.decode(value),
    responseSerialize: (value: DeleteMessageResponse): Buffer =>
      Buffer.from(DeleteMessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteMessageResponse => DeleteMessageResponse.decode(value),
  },
  /** Chat Participants */
  addParticipant: {
    path: "/communication.CommunicationService/AddParticipant",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AddParticipantRequest): Buffer =>
      Buffer.from(AddParticipantRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddParticipantRequest => AddParticipantRequest.decode(value),
    responseSerialize: (value: ParticipantResponse): Buffer => Buffer.from(ParticipantResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ParticipantResponse => ParticipantResponse.decode(value),
  },
  removeParticipant: {
    path: "/communication.CommunicationService/RemoveParticipant",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RemoveParticipantRequest): Buffer =>
      Buffer.from(RemoveParticipantRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RemoveParticipantRequest => RemoveParticipantRequest.decode(value),
    responseSerialize: (value: ParticipantResponse): Buffer => Buffer.from(ParticipantResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ParticipantResponse => ParticipantResponse.decode(value),
  },
  getParticipants: {
    path: "/communication.CommunicationService/GetParticipants",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetParticipantsRequest): Buffer =>
      Buffer.from(GetParticipantsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetParticipantsRequest => GetParticipantsRequest.decode(value),
    responseSerialize: (value: GetParticipantsResponse): Buffer =>
      Buffer.from(GetParticipantsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetParticipantsResponse => GetParticipantsResponse.decode(value),
  },
  /** Message Status & Read Receipts */
  markMessagesAsRead: {
    path: "/communication.CommunicationService/MarkMessagesAsRead",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MarkAsReadRequest): Buffer => Buffer.from(MarkAsReadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): MarkAsReadRequest => MarkAsReadRequest.decode(value),
    responseSerialize: (value: MarkAsReadResponse): Buffer => Buffer.from(MarkAsReadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MarkAsReadResponse => MarkAsReadResponse.decode(value),
  },
  getUnreadCounts: {
    path: "/communication.CommunicationService/GetUnreadCounts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUnreadCountsRequest): Buffer =>
      Buffer.from(GetUnreadCountsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUnreadCountsRequest => GetUnreadCountsRequest.decode(value),
    responseSerialize: (value: GetUnreadCountsResponse): Buffer =>
      Buffer.from(GetUnreadCountsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUnreadCountsResponse => GetUnreadCountsResponse.decode(value),
  },
  /** Real-time subscriptions (for WebSocket events) */
  getChatEvents: {
    path: "/communication.CommunicationService/GetChatEvents",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: ChatEventsRequest): Buffer => Buffer.from(ChatEventsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatEventsRequest => ChatEventsRequest.decode(value),
    responseSerialize: (value: ChatEventResponse): Buffer => Buffer.from(ChatEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatEventResponse => ChatEventResponse.decode(value),
  },
  /** Mail Management */
  sendOtpMail: {
    path: "/communication.CommunicationService/SendOtpMail",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendOtpMailRequest): Buffer => Buffer.from(SendOtpMailRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SendOtpMailRequest => SendOtpMailRequest.decode(value),
    responseSerialize: (value: SendOtpMailResponse): Buffer => Buffer.from(SendOtpMailResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SendOtpMailResponse => SendOtpMailResponse.decode(value),
  },
  /** Push Notifications */
  clearUserPushSubscriptions: {
    path: "/communication.CommunicationService/ClearUserPushSubscriptions",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ClearUserPushSubscriptionsRequest): Buffer =>
      Buffer.from(ClearUserPushSubscriptionsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ClearUserPushSubscriptionsRequest =>
      ClearUserPushSubscriptionsRequest.decode(value),
    responseSerialize: (value: ClearUserPushSubscriptionsResponse): Buffer =>
      Buffer.from(ClearUserPushSubscriptionsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ClearUserPushSubscriptionsResponse =>
      ClearUserPushSubscriptionsResponse.decode(value),
  },
} as const;

export interface CommunicationServiceServer extends UntypedServiceImplementation {
  /** Chat Management */
  createChat: handleUnaryCall<CreateChatRequest, ChatResponse>;
  getChat: handleUnaryCall<GetChatRequest, ChatResponse>;
  getUserChats: handleUnaryCall<GetUserChatsRequest, GetUserChatsResponse>;
  updateChat: handleUnaryCall<UpdateChatRequest, ChatResponse>;
  deleteChat: handleUnaryCall<DeleteChatRequest, DeleteChatResponse>;
  /** Message Management */
  sendMessage: handleUnaryCall<SendMessageRequest, MessageResponse>;
  getMessages: handleUnaryCall<GetMessagesRequest, GetMessagesResponse>;
  updateMessage: handleUnaryCall<UpdateMessageRequest, MessageResponse>;
  deleteMessage: handleUnaryCall<DeleteMessageRequest, DeleteMessageResponse>;
  /** Chat Participants */
  addParticipant: handleUnaryCall<AddParticipantRequest, ParticipantResponse>;
  removeParticipant: handleUnaryCall<RemoveParticipantRequest, ParticipantResponse>;
  getParticipants: handleUnaryCall<GetParticipantsRequest, GetParticipantsResponse>;
  /** Message Status & Read Receipts */
  markMessagesAsRead: handleUnaryCall<MarkAsReadRequest, MarkAsReadResponse>;
  getUnreadCounts: handleUnaryCall<GetUnreadCountsRequest, GetUnreadCountsResponse>;
  /** Real-time subscriptions (for WebSocket events) */
  getChatEvents: handleServerStreamingCall<ChatEventsRequest, ChatEventResponse>;
  /** Mail Management */
  sendOtpMail: handleUnaryCall<SendOtpMailRequest, SendOtpMailResponse>;
  /** Push Notifications */
  clearUserPushSubscriptions: handleUnaryCall<ClearUserPushSubscriptionsRequest, ClearUserPushSubscriptionsResponse>;
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
