// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: communication.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "communication";

export enum SendOtpType {
  REGISTRATION = 0,
  SIGNIN = 1,
  ADMIN_REGISTRATION = 2,
  ADMIN_SIGNIN = 3,
  FORGOT_PASSWORD = 4,
  UNRECOGNIZED = -1,
}

export enum ChatType {
  CHAT_TYPE_DIRECT = 0,
  CHAT_TYPE_GROUP = 1,
  CHAT_TYPE_CHANNEL = 2,
  UNRECOGNIZED = -1,
}

export enum ChatStatus {
  CHAT_STATUS_PENDING = 0,
  CHAT_STATUS_ACTIVE = 1,
  CHAT_STATUS_ARCHIVED = 2,
  CHAT_STATUS_DELETED = 3,
  UNRECOGNIZED = -1,
}

export enum MessageType {
  MESSAGE_TYPE_TEXT = 0,
  MESSAGE_TYPE_IMAGE = 1,
  MESSAGE_TYPE_VIDEO = 2,
  MESSAGE_TYPE_AUDIO = 3,
  MESSAGE_TYPE_FILE = 4,
  MESSAGE_TYPE_VOICE_NOTE = 5,
  MESSAGE_TYPE_SYSTEM = 6,
  UNRECOGNIZED = -1,
}

export enum MessageStatus {
  MESSAGE_STATUS_PENDING = 0,
  MESSAGE_STATUS_SENT = 1,
  MESSAGE_STATUS_DELIVERED = 2,
  MESSAGE_STATUS_READ = 3,
  MESSAGE_STATUS_FAILED = 4,
  UNRECOGNIZED = -1,
}

export interface SendOtpMailRequest {
  email: string;
  name: string;
  otp: string;
  type: SendOtpType;
}

export interface ClearUserPushSubscriptionsRequest {
  userId: string;
}

export interface ClearUserPushSubscriptionsResponse {
  success: boolean;
}

export interface CreateChatRequest {
  name: string;
  chatType: ChatType;
  creatorId: string;
  participantIds: string[];
  avatarUrl?: string | undefined;
}

export interface GetChatRequest {
  chatId: string;
  userId: string;
}

export interface GetUserChatsRequest {
  userId: string;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface UpdateChatRequest {
  chatId: string;
  userId: string;
  name?: string | undefined;
  avatarUrl?: string | undefined;
  status?: ChatStatus | undefined;
}

export interface DeleteChatRequest {
  chatId: string;
  userId: string;
}

export interface SendMessageRequest {
  chatId: string;
  senderId: string;
  content: string;
  type: MessageType;
  mediaUrls: string[];
  fileUrl?: string | undefined;
  fileSize?: number | undefined;
  fileType?: string | undefined;
  duration?: number | undefined;
}

export interface GetMessagesRequest {
  chatId: string;
  userId: string;
  limit?: number | undefined;
  offset?: number | undefined;
  beforeMessageId?: string | undefined;
  afterMessageId?: string | undefined;
}

export interface UpdateMessageRequest {
  messageId: string;
  userId: string;
  content?: string | undefined;
  mediaUrls: string[];
}

export interface DeleteMessageRequest {
  messageId: string;
  userId: string;
}

export interface AddParticipantRequest {
  chatId: string;
  userId: string;
  newParticipantId: string;
  isAdmin?: boolean | undefined;
}

export interface RemoveParticipantRequest {
  chatId: string;
  userId: string;
  participantId: string;
}

export interface GetParticipantsRequest {
  chatId: string;
  userId: string;
}

export interface MarkAsReadRequest {
  chatId: string;
  userId: string;
  messageIds: string[];
}

export interface GetUnreadCountsRequest {
  userId: string;
  chatIds: string[];
}

export interface ChatEventsRequest {
  userId: string;
  chatIds: string[];
}

export interface ChatResponse {
  success: boolean;
  error?: string | undefined;
  chat?: Chat | undefined;
}

export interface GetUserChatsResponse {
  success: boolean;
  error?: string | undefined;
  chats: ChatWithDetails[];
  totalCount: number;
}

export interface DeleteChatResponse {
  success: boolean;
  error?: string | undefined;
  chatId: string;
}

export interface SendOtpMailResponse {
  success: boolean;
  error?: string | undefined;
}

export interface MessageResponse {
  success: boolean;
  error?: string | undefined;
  message?: Message | undefined;
}

export interface GetMessagesResponse {
  success: boolean;
  error?: string | undefined;
  messages: Message[];
  totalCount: number;
  nextCursor?: string | undefined;
}

export interface DeleteMessageResponse {
  success: boolean;
  error?: string | undefined;
  messageId: string;
}

export interface ParticipantResponse {
  success: boolean;
  error?: string | undefined;
  participant?: ChatParticipant | undefined;
}

export interface GetParticipantsResponse {
  success: boolean;
  error?: string | undefined;
  participants: ChatParticipant[];
}

export interface MarkAsReadResponse {
  success: boolean;
  error?: string | undefined;
  markedCount: number;
}

export interface GetUnreadCountsResponse {
  success: boolean;
  error?: string | undefined;
  unreadCounts: UnreadCount[];
}

export interface ChatEventResponse {
  eventType: string;
  chatId: string;
  message?: Message | undefined;
  participant?: ChatParticipant | undefined;
  chat?: Chat | undefined;
  timestamp: string;
}

export interface Chat {
  chatId: string;
  name?: string | undefined;
  avatarUrl?: string | undefined;
  chatType: ChatType;
  status: ChatStatus;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface ChatWithDetails {
  chatId: string;
  name?: string | undefined;
  avatarUrl?: string | undefined;
  chatType: ChatType;
  status: ChatStatus;
  isAdmin: boolean;
  joinedAt: string;
  lastMessage?: Message | undefined;
  unreadCount: number;
  participantCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface Message {
  messageId: string;
  chatId: string;
  senderId: string;
  content: string;
  mediaUrls: string[];
  type: MessageType;
  status: MessageStatus;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  duration?: number | undefined;
  fileUrl?: string | undefined;
  fileSize?: number | undefined;
  fileType?: string | undefined;
}

export interface ChatParticipant {
  chatId: string;
  userId: string;
  joinedAt: string;
  isAdmin: boolean;
  isActive: boolean;
  unreadCount: number;
}

export interface UnreadCount {
  chatId: string;
  count: number;
  lastReadAt: string;
}

export const COMMUNICATION_PACKAGE_NAME = "communication";

/** 💬 Communication Service - handles chats, messages, and real-time communication */

export interface CommunicationServiceClient {
  /** Chat Management */

  createChat(request: CreateChatRequest): Observable<ChatResponse>;

  getChat(request: GetChatRequest): Observable<ChatResponse>;

  getUserChats(request: GetUserChatsRequest): Observable<GetUserChatsResponse>;

  updateChat(request: UpdateChatRequest): Observable<ChatResponse>;

  deleteChat(request: DeleteChatRequest): Observable<DeleteChatResponse>;

  /** Message Management */

  sendMessage(request: SendMessageRequest): Observable<MessageResponse>;

  getMessages(request: GetMessagesRequest): Observable<GetMessagesResponse>;

  updateMessage(request: UpdateMessageRequest): Observable<MessageResponse>;

  deleteMessage(request: DeleteMessageRequest): Observable<DeleteMessageResponse>;

  /** Chat Participants */

  addParticipant(request: AddParticipantRequest): Observable<ParticipantResponse>;

  removeParticipant(request: RemoveParticipantRequest): Observable<ParticipantResponse>;

  getParticipants(request: GetParticipantsRequest): Observable<GetParticipantsResponse>;

  /** Message Status & Read Receipts */

  markMessagesAsRead(request: MarkAsReadRequest): Observable<MarkAsReadResponse>;

  getUnreadCounts(request: GetUnreadCountsRequest): Observable<GetUnreadCountsResponse>;

  /** Real-time subscriptions (for WebSocket events) */

  getChatEvents(request: ChatEventsRequest): Observable<ChatEventResponse>;

  /** Mail Management */

  sendOtpMail(request: SendOtpMailRequest): Observable<SendOtpMailResponse>;

  /** Push Notifications */

  clearUserPushSubscriptions(
    request: ClearUserPushSubscriptionsRequest,
  ): Observable<ClearUserPushSubscriptionsResponse>;
}

/** 💬 Communication Service - handles chats, messages, and real-time communication */

export interface CommunicationServiceController {
  /** Chat Management */

  createChat(request: CreateChatRequest): Promise<ChatResponse> | Observable<ChatResponse> | ChatResponse;

  getChat(request: GetChatRequest): Promise<ChatResponse> | Observable<ChatResponse> | ChatResponse;

  getUserChats(
    request: GetUserChatsRequest,
  ): Promise<GetUserChatsResponse> | Observable<GetUserChatsResponse> | GetUserChatsResponse;

  updateChat(request: UpdateChatRequest): Promise<ChatResponse> | Observable<ChatResponse> | ChatResponse;

  deleteChat(
    request: DeleteChatRequest,
  ): Promise<DeleteChatResponse> | Observable<DeleteChatResponse> | DeleteChatResponse;

  /** Message Management */

  sendMessage(request: SendMessageRequest): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getMessages(
    request: GetMessagesRequest,
  ): Promise<GetMessagesResponse> | Observable<GetMessagesResponse> | GetMessagesResponse;

  updateMessage(
    request: UpdateMessageRequest,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  deleteMessage(
    request: DeleteMessageRequest,
  ): Promise<DeleteMessageResponse> | Observable<DeleteMessageResponse> | DeleteMessageResponse;

  /** Chat Participants */

  addParticipant(
    request: AddParticipantRequest,
  ): Promise<ParticipantResponse> | Observable<ParticipantResponse> | ParticipantResponse;

  removeParticipant(
    request: RemoveParticipantRequest,
  ): Promise<ParticipantResponse> | Observable<ParticipantResponse> | ParticipantResponse;

  getParticipants(
    request: GetParticipantsRequest,
  ): Promise<GetParticipantsResponse> | Observable<GetParticipantsResponse> | GetParticipantsResponse;

  /** Message Status & Read Receipts */

  markMessagesAsRead(
    request: MarkAsReadRequest,
  ): Promise<MarkAsReadResponse> | Observable<MarkAsReadResponse> | MarkAsReadResponse;

  getUnreadCounts(
    request: GetUnreadCountsRequest,
  ): Promise<GetUnreadCountsResponse> | Observable<GetUnreadCountsResponse> | GetUnreadCountsResponse;

  /** Real-time subscriptions (for WebSocket events) */

  getChatEvents(request: ChatEventsRequest): Observable<ChatEventResponse>;

  /** Mail Management */

  sendOtpMail(
    request: SendOtpMailRequest,
  ): Promise<SendOtpMailResponse> | Observable<SendOtpMailResponse> | SendOtpMailResponse;

  /** Push Notifications */

  clearUserPushSubscriptions(
    request: ClearUserPushSubscriptionsRequest,
  ):
    | Promise<ClearUserPushSubscriptionsResponse>
    | Observable<ClearUserPushSubscriptionsResponse>
    | ClearUserPushSubscriptionsResponse;
}

export function CommunicationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createChat",
      "getChat",
      "getUserChats",
      "updateChat",
      "deleteChat",
      "sendMessage",
      "getMessages",
      "updateMessage",
      "deleteMessage",
      "addParticipant",
      "removeParticipant",
      "getParticipants",
      "markMessagesAsRead",
      "getUnreadCounts",
      "getChatEvents",
      "sendOtpMail",
      "clearUserPushSubscriptions",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CommunicationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CommunicationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMMUNICATION_SERVICE_NAME = "CommunicationService";
