// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v5.27.3
// source: files.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "files";

export enum FileType {
  FILE_TYPE_IMAGE = 0,
  FILE_TYPE_VIDEO = 1,
  FILE_TYPE_AUDIO = 2,
  UNRECOGNIZED = -1,
}

export enum TempFileStatus {
  TEMP_FILE_STATUS_TEMPORARY = 0,
  TEMP_FILE_STATUS_CONFIRMING = 1,
  TEMP_FILE_STATUS_EXPIRED = 2,
  TEMP_FILE_STATUS_FAILED = 3,
  UNRECOGNIZED = -1,
}

export enum UploadSessionStatus {
  UPLOAD_SESSION_STATUS_ACTIVE = 0,
  UPLOAD_SESSION_STATUS_CONFIRMING = 1,
  UPLOAD_SESSION_STATUS_COMPLETED = 2,
  UPLOAD_SESSION_STATUS_EXPIRED = 3,
  UPLOAD_SESSION_STATUS_CANCELLED = 4,
  UNRECOGNIZED = -1,
}

export enum ProcessingStatus {
  PROCESSING_STATUS_PENDING = 0,
  PROCESSING_STATUS_PROCESSING = 1,
  PROCESSING_STATUS_COMPLETED = 2,
  PROCESSING_STATUS_FAILED = 3,
  PROCESSING_STATUS_CANCELLED = 4,
  UNRECOGNIZED = -1,
}

export enum FileVisibility {
  FILE_VISIBILITY_PUBLIC = 0,
  FILE_VISIBILITY_PRIVATE = 1,
  FILE_VISIBILITY_ORGANIZATION = 2,
  FILE_VISIBILITY_BRANCH = 3,
  FILE_VISIBILITY_ROLE_RESTRICTED = 4,
  UNRECOGNIZED = -1,
}

export interface VerifyFileRequest {
  entity_type: string;
  entity_id: string;
}

export interface CreateOrUpdateFileRequest {
  entity_type: string;
  entity_id: string;
  file_url: string;
}

export interface CreateOrUpdateFileResponse {
  file_url: string;
}

export interface VerifyFileResponse {
  file_url: string;
}

export interface UploadTemporaryFileRequest {
  file_data: Uint8Array;
  file_name: string;
  mime_type: string;
  user_id: string;
  /** JSON string */
  metadata?: string | undefined;
  session_id?: string | undefined;
}

export interface ConfirmFileRequest {
  file_id: string;
  user_id: string;
  /** JSON string */
  additional_metadata?: string | undefined;
}

export interface GetTempFileRequest {
  file_id: string;
}

export interface GetTempFilesByUserRequest {
  user_id: string;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface UploadFileRequest {
  file_data: Uint8Array;
  file_name: string;
  mime_type: string;
  user_id: string;
  /** JSON string */
  metadata?: string | undefined;
}

export interface UploadMultipleFilesRequest {
  files: FileUploadData[];
  user_id: string;
  /** JSON string */
  metadata?:
    | string
    | undefined;
  /** default true */
  temporary?: boolean | undefined;
  session_id?: string | undefined;
}

export interface FileUploadData {
  file_data: Uint8Array;
  file_name: string;
  mime_type: string;
}

export interface CreateUploadSessionRequest {
  user_id: string;
  expected_files: number;
  /** default 30 */
  expires_in_minutes?: number | undefined;
}

export interface ConfirmUploadSessionRequest {
  session_id: string;
  user_id: string;
  files_to_keep: string[];
}

export interface GetUploadSessionRequest {
  session_id: string;
  user_id: string;
}

export interface DeleteFileRequest {
  file_url: string;
  user_id: string;
}

export interface GetFileInfoRequest {
  file_id: string;
  user_id: string;
}

export interface GetUserFilesRequest {
  user_id: string;
  file_type?: FileType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface GetProcessingStatusRequest {
  file_id: string;
  user_id: string;
}

export interface RetryProcessingRequest {
  file_id: string;
  user_id: string;
}

export interface TempFileResponse {
  success: boolean;
  error?: string | undefined;
  temp_file?: TempFile | undefined;
}

export interface GetTempFilesResponse {
  success: boolean;
  error?: string | undefined;
  temp_files: TempFile[];
  total_count: number;
}

export interface ConfirmFileResponse {
  success: boolean;
  error?: string | undefined;
  permanent_file_id?: string | undefined;
  file_name?: string | undefined;
  cloudinary_url?: string | undefined;
  file_type?: FileType | undefined;
  upload_job_id?: string | undefined;
}

export interface FileUploadResponse {
  success: boolean;
  error?: string | undefined;
  file_id?: string | undefined;
  file_name?: string | undefined;
  cloudinary_url?: string | undefined;
  file_type?: FileType | undefined;
  upload_job_id?: string | undefined;
}

export interface MultipleFileUploadResponse {
  success: boolean;
  error?: string | undefined;
  results: FileUploadResult[];
  total_files: number;
  successful_uploads: number;
}

export interface FileUploadResult {
  success: boolean;
  error?: string | undefined;
  file_id?: string | undefined;
  file_name?: string | undefined;
  cloudinary_url?: string | undefined;
  file_type?: FileType | undefined;
  status?: TempFileStatus | undefined;
  expires_at?: string | undefined;
  uploaded_at?: string | undefined;
}

export interface UploadSessionResponse {
  success: boolean;
  error?: string | undefined;
  session?: UploadSession | undefined;
}

export interface ConfirmUploadSessionResponse {
  success: boolean;
  error?: string | undefined;
  session_id?: string | undefined;
  confirmed_files: ConfirmFileResponse[];
  deleted_files: string[];
  status?: UploadSessionStatus | undefined;
}

export interface DeleteFileResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
}

export interface FileInfoResponse {
  success: boolean;
  error?: string | undefined;
  file_info?: FileInfo | undefined;
}

export interface GetUserFilesResponse {
  success: boolean;
  error?: string | undefined;
  files: FileInfo[];
  total_count: number;
}

export interface ProcessingStatusResponse {
  success: boolean;
  error?: string | undefined;
  status?: ProcessingStatus | undefined;
  processing_error?: string | undefined;
  progress_percentage?: number | undefined;
}

export interface RetryProcessingResponse {
  success: boolean;
  error?: string | undefined;
  job_id?: string | undefined;
  message: string;
}

export interface TempFile {
  file_id: string;
  user_id: string;
  file_name: string;
  file_size: number;
  mime_type: string;
  file_type: FileType;
  cloudinary_url: string;
  status: TempFileStatus;
  /** JSON string */
  metadata?: string | undefined;
  session_id?: string | undefined;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface UploadSession {
  session_id: string;
  user_id: string;
  expected_files: number;
  uploaded_files: number;
  status: UploadSessionStatus;
  upload_token?:
    | string
    | undefined;
  /** JSON string */
  metadata?: string | undefined;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface FileInfo {
  file_id: string;
  file_name: string;
  original_name: string;
  file_size: number;
  file_type: FileType;
  mime_type: string;
  file_url: string;
  thumbnail_url?: string | undefined;
  compressed_url?: string | undefined;
  is_processed: boolean;
  processing_status: ProcessingStatus;
  processing_error?: string | undefined;
  visibility: FileVisibility;
  download_count: number;
  view_count: number;
  is_public: boolean;
  uploaded_by: string;
  company_id?: string | undefined;
  branch_id?: string | undefined;
  entity_type?: string | undefined;
  entity_id?: string | undefined;
  alt_text?: string | undefined;
  description?: string | undefined;
  tags: string[];
  /** JSON string */
  metadata?: string | undefined;
  created_at: string;
  updated_at: string;
  deleted_at?: string | undefined;
}

export const FILES_PACKAGE_NAME = "files";

function createBaseVerifyFileRequest(): VerifyFileRequest {
  return { entity_type: "", entity_id: "" };
}

export const VerifyFileRequest: MessageFns<VerifyFileRequest> = {
  encode(message: VerifyFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity_type !== "") {
      writer.uint32(10).string(message.entity_type);
    }
    if (message.entity_id !== "") {
      writer.uint32(18).string(message.entity_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity_type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entity_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateOrUpdateFileRequest(): CreateOrUpdateFileRequest {
  return { entity_type: "", entity_id: "", file_url: "" };
}

export const CreateOrUpdateFileRequest: MessageFns<CreateOrUpdateFileRequest> = {
  encode(message: CreateOrUpdateFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity_type !== "") {
      writer.uint32(10).string(message.entity_type);
    }
    if (message.entity_id !== "") {
      writer.uint32(18).string(message.entity_id);
    }
    if (message.file_url !== "") {
      writer.uint32(26).string(message.file_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrUpdateFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrUpdateFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity_type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entity_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateOrUpdateFileResponse(): CreateOrUpdateFileResponse {
  return { file_url: "" };
}

export const CreateOrUpdateFileResponse: MessageFns<CreateOrUpdateFileResponse> = {
  encode(message: CreateOrUpdateFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_url !== "") {
      writer.uint32(10).string(message.file_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrUpdateFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrUpdateFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVerifyFileResponse(): VerifyFileResponse {
  return { file_url: "" };
}

export const VerifyFileResponse: MessageFns<VerifyFileResponse> = {
  encode(message: VerifyFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_url !== "") {
      writer.uint32(10).string(message.file_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VerifyFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVerifyFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUploadTemporaryFileRequest(): UploadTemporaryFileRequest {
  return { file_data: new Uint8Array(0), file_name: "", mime_type: "", user_id: "" };
}

export const UploadTemporaryFileRequest: MessageFns<UploadTemporaryFileRequest> = {
  encode(message: UploadTemporaryFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_data.length !== 0) {
      writer.uint32(10).bytes(message.file_data);
    }
    if (message.file_name !== "") {
      writer.uint32(18).string(message.file_name);
    }
    if (message.mime_type !== "") {
      writer.uint32(26).string(message.mime_type);
    }
    if (message.user_id !== "") {
      writer.uint32(34).string(message.user_id);
    }
    if (message.metadata !== undefined) {
      writer.uint32(42).string(message.metadata);
    }
    if (message.session_id !== undefined) {
      writer.uint32(50).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadTemporaryFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadTemporaryFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mime_type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConfirmFileRequest(): ConfirmFileRequest {
  return { file_id: "", user_id: "" };
}

export const ConfirmFileRequest: MessageFns<ConfirmFileRequest> = {
  encode(message: ConfirmFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.additional_metadata !== undefined) {
      writer.uint32(26).string(message.additional_metadata);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfirmFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfirmFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.additional_metadata = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetTempFileRequest(): GetTempFileRequest {
  return { file_id: "" };
}

export const GetTempFileRequest: MessageFns<GetTempFileRequest> = {
  encode(message: GetTempFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTempFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTempFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetTempFilesByUserRequest(): GetTempFilesByUserRequest {
  return { user_id: "" };
}

export const GetTempFilesByUserRequest: MessageFns<GetTempFilesByUserRequest> = {
  encode(message: GetTempFilesByUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.limit !== undefined) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(24).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTempFilesByUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTempFilesByUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUploadFileRequest(): UploadFileRequest {
  return { file_data: new Uint8Array(0), file_name: "", mime_type: "", user_id: "" };
}

export const UploadFileRequest: MessageFns<UploadFileRequest> = {
  encode(message: UploadFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_data.length !== 0) {
      writer.uint32(10).bytes(message.file_data);
    }
    if (message.file_name !== "") {
      writer.uint32(18).string(message.file_name);
    }
    if (message.mime_type !== "") {
      writer.uint32(26).string(message.mime_type);
    }
    if (message.user_id !== "") {
      writer.uint32(34).string(message.user_id);
    }
    if (message.metadata !== undefined) {
      writer.uint32(42).string(message.metadata);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mime_type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUploadMultipleFilesRequest(): UploadMultipleFilesRequest {
  return { files: [], user_id: "" };
}

export const UploadMultipleFilesRequest: MessageFns<UploadMultipleFilesRequest> = {
  encode(message: UploadMultipleFilesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.files) {
      FileUploadData.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.metadata !== undefined) {
      writer.uint32(26).string(message.metadata);
    }
    if (message.temporary !== undefined) {
      writer.uint32(32).bool(message.temporary);
    }
    if (message.session_id !== undefined) {
      writer.uint32(42).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadMultipleFilesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadMultipleFilesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.files.push(FileUploadData.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.temporary = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFileUploadData(): FileUploadData {
  return { file_data: new Uint8Array(0), file_name: "", mime_type: "" };
}

export const FileUploadData: MessageFns<FileUploadData> = {
  encode(message: FileUploadData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_data.length !== 0) {
      writer.uint32(10).bytes(message.file_data);
    }
    if (message.file_name !== "") {
      writer.uint32(18).string(message.file_name);
    }
    if (message.mime_type !== "") {
      writer.uint32(26).string(message.mime_type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileUploadData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileUploadData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_data = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mime_type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateUploadSessionRequest(): CreateUploadSessionRequest {
  return { user_id: "", expected_files: 0 };
}

export const CreateUploadSessionRequest: MessageFns<CreateUploadSessionRequest> = {
  encode(message: CreateUploadSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.expected_files !== 0) {
      writer.uint32(16).int32(message.expected_files);
    }
    if (message.expires_in_minutes !== undefined) {
      writer.uint32(24).int32(message.expires_in_minutes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.expected_files = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expires_in_minutes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConfirmUploadSessionRequest(): ConfirmUploadSessionRequest {
  return { session_id: "", user_id: "", files_to_keep: [] };
}

export const ConfirmUploadSessionRequest: MessageFns<ConfirmUploadSessionRequest> = {
  encode(message: ConfirmUploadSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    for (const v of message.files_to_keep) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfirmUploadSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfirmUploadSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.files_to_keep.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUploadSessionRequest(): GetUploadSessionRequest {
  return { session_id: "", user_id: "" };
}

export const GetUploadSessionRequest: MessageFns<GetUploadSessionRequest> = {
  encode(message: GetUploadSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteFileRequest(): DeleteFileRequest {
  return { file_url: "", user_id: "" };
}

export const DeleteFileRequest: MessageFns<DeleteFileRequest> = {
  encode(message: DeleteFileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_url !== "") {
      writer.uint32(10).string(message.file_url);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteFileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteFileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetFileInfoRequest(): GetFileInfoRequest {
  return { file_id: "", user_id: "" };
}

export const GetFileInfoRequest: MessageFns<GetFileInfoRequest> = {
  encode(message: GetFileInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFileInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFileInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserFilesRequest(): GetUserFilesRequest {
  return { user_id: "" };
}

export const GetUserFilesRequest: MessageFns<GetUserFilesRequest> = {
  encode(message: GetUserFilesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.file_type !== undefined) {
      writer.uint32(16).int32(message.file_type);
    }
    if (message.limit !== undefined) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(32).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserFilesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserFilesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetProcessingStatusRequest(): GetProcessingStatusRequest {
  return { file_id: "", user_id: "" };
}

export const GetProcessingStatusRequest: MessageFns<GetProcessingStatusRequest> = {
  encode(message: GetProcessingStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProcessingStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProcessingStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRetryProcessingRequest(): RetryProcessingRequest {
  return { file_id: "", user_id: "" };
}

export const RetryProcessingRequest: MessageFns<RetryProcessingRequest> = {
  encode(message: RetryProcessingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetryProcessingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetryProcessingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTempFileResponse(): TempFileResponse {
  return { success: false };
}

export const TempFileResponse: MessageFns<TempFileResponse> = {
  encode(message: TempFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.temp_file !== undefined) {
      TempFile.encode(message.temp_file, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TempFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTempFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.temp_file = TempFile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetTempFilesResponse(): GetTempFilesResponse {
  return { success: false, temp_files: [], total_count: 0 };
}

export const GetTempFilesResponse: MessageFns<GetTempFilesResponse> = {
  encode(message: GetTempFilesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.temp_files) {
      TempFile.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total_count !== 0) {
      writer.uint32(32).int32(message.total_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTempFilesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTempFilesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.temp_files.push(TempFile.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total_count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConfirmFileResponse(): ConfirmFileResponse {
  return { success: false };
}

export const ConfirmFileResponse: MessageFns<ConfirmFileResponse> = {
  encode(message: ConfirmFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.permanent_file_id !== undefined) {
      writer.uint32(26).string(message.permanent_file_id);
    }
    if (message.file_name !== undefined) {
      writer.uint32(34).string(message.file_name);
    }
    if (message.cloudinary_url !== undefined) {
      writer.uint32(42).string(message.cloudinary_url);
    }
    if (message.file_type !== undefined) {
      writer.uint32(48).int32(message.file_type);
    }
    if (message.upload_job_id !== undefined) {
      writer.uint32(58).string(message.upload_job_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfirmFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfirmFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.permanent_file_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cloudinary_url = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.upload_job_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFileUploadResponse(): FileUploadResponse {
  return { success: false };
}

export const FileUploadResponse: MessageFns<FileUploadResponse> = {
  encode(message: FileUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.file_id !== undefined) {
      writer.uint32(26).string(message.file_id);
    }
    if (message.file_name !== undefined) {
      writer.uint32(34).string(message.file_name);
    }
    if (message.cloudinary_url !== undefined) {
      writer.uint32(42).string(message.cloudinary_url);
    }
    if (message.file_type !== undefined) {
      writer.uint32(48).int32(message.file_type);
    }
    if (message.upload_job_id !== undefined) {
      writer.uint32(58).string(message.upload_job_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cloudinary_url = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.upload_job_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMultipleFileUploadResponse(): MultipleFileUploadResponse {
  return { success: false, results: [], total_files: 0, successful_uploads: 0 };
}

export const MultipleFileUploadResponse: MessageFns<MultipleFileUploadResponse> = {
  encode(message: MultipleFileUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.results) {
      FileUploadResult.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total_files !== 0) {
      writer.uint32(32).int32(message.total_files);
    }
    if (message.successful_uploads !== 0) {
      writer.uint32(40).int32(message.successful_uploads);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultipleFileUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMultipleFileUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.results.push(FileUploadResult.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total_files = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.successful_uploads = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFileUploadResult(): FileUploadResult {
  return { success: false };
}

export const FileUploadResult: MessageFns<FileUploadResult> = {
  encode(message: FileUploadResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.file_id !== undefined) {
      writer.uint32(26).string(message.file_id);
    }
    if (message.file_name !== undefined) {
      writer.uint32(34).string(message.file_name);
    }
    if (message.cloudinary_url !== undefined) {
      writer.uint32(42).string(message.cloudinary_url);
    }
    if (message.file_type !== undefined) {
      writer.uint32(48).int32(message.file_type);
    }
    if (message.status !== undefined) {
      writer.uint32(56).int32(message.status);
    }
    if (message.expires_at !== undefined) {
      writer.uint32(66).string(message.expires_at);
    }
    if (message.uploaded_at !== undefined) {
      writer.uint32(74).string(message.uploaded_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileUploadResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileUploadResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cloudinary_url = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.expires_at = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.uploaded_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUploadSessionResponse(): UploadSessionResponse {
  return { success: false };
}

export const UploadSessionResponse: MessageFns<UploadSessionResponse> = {
  encode(message: UploadSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.session !== undefined) {
      UploadSession.encode(message.session, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.session = UploadSession.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConfirmUploadSessionResponse(): ConfirmUploadSessionResponse {
  return { success: false, confirmed_files: [], deleted_files: [] };
}

export const ConfirmUploadSessionResponse: MessageFns<ConfirmUploadSessionResponse> = {
  encode(message: ConfirmUploadSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.session_id !== undefined) {
      writer.uint32(26).string(message.session_id);
    }
    for (const v of message.confirmed_files) {
      ConfirmFileResponse.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.deleted_files) {
      writer.uint32(42).string(v!);
    }
    if (message.status !== undefined) {
      writer.uint32(48).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfirmUploadSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfirmUploadSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.confirmed_files.push(ConfirmFileResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deleted_files.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteFileResponse(): DeleteFileResponse {
  return { success: false, message: "" };
}

export const DeleteFileResponse: MessageFns<DeleteFileResponse> = {
  encode(message: DeleteFileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteFileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteFileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFileInfoResponse(): FileInfoResponse {
  return { success: false };
}

export const FileInfoResponse: MessageFns<FileInfoResponse> = {
  encode(message: FileInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.file_info !== undefined) {
      FileInfo.encode(message.file_info, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file_info = FileInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserFilesResponse(): GetUserFilesResponse {
  return { success: false, files: [], total_count: 0 };
}

export const GetUserFilesResponse: MessageFns<GetUserFilesResponse> = {
  encode(message: GetUserFilesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.files) {
      FileInfo.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total_count !== 0) {
      writer.uint32(32).int32(message.total_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserFilesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserFilesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.files.push(FileInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total_count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseProcessingStatusResponse(): ProcessingStatusResponse {
  return { success: false };
}

export const ProcessingStatusResponse: MessageFns<ProcessingStatusResponse> = {
  encode(message: ProcessingStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.status !== undefined) {
      writer.uint32(24).int32(message.status);
    }
    if (message.processing_error !== undefined) {
      writer.uint32(34).string(message.processing_error);
    }
    if (message.progress_percentage !== undefined) {
      writer.uint32(40).int32(message.progress_percentage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessingStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessingStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.processing_error = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.progress_percentage = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRetryProcessingResponse(): RetryProcessingResponse {
  return { success: false, message: "" };
}

export const RetryProcessingResponse: MessageFns<RetryProcessingResponse> = {
  encode(message: RetryProcessingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.job_id !== undefined) {
      writer.uint32(26).string(message.job_id);
    }
    if (message.message !== "") {
      writer.uint32(34).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetryProcessingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetryProcessingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.job_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTempFile(): TempFile {
  return {
    file_id: "",
    user_id: "",
    file_name: "",
    file_size: 0,
    mime_type: "",
    file_type: 0,
    cloudinary_url: "",
    status: 0,
    expires_at: "",
    created_at: "",
    updated_at: "",
  };
}

export const TempFile: MessageFns<TempFile> = {
  encode(message: TempFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.file_name !== "") {
      writer.uint32(26).string(message.file_name);
    }
    if (message.file_size !== 0) {
      writer.uint32(32).int64(message.file_size);
    }
    if (message.mime_type !== "") {
      writer.uint32(42).string(message.mime_type);
    }
    if (message.file_type !== 0) {
      writer.uint32(48).int32(message.file_type);
    }
    if (message.cloudinary_url !== "") {
      writer.uint32(58).string(message.cloudinary_url);
    }
    if (message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.metadata !== undefined) {
      writer.uint32(74).string(message.metadata);
    }
    if (message.session_id !== undefined) {
      writer.uint32(82).string(message.session_id);
    }
    if (message.expires_at !== "") {
      writer.uint32(90).string(message.expires_at);
    }
    if (message.created_at !== "") {
      writer.uint32(98).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(106).string(message.updated_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TempFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTempFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.file_size = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.mime_type = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.cloudinary_url = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.expires_at = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUploadSession(): UploadSession {
  return {
    session_id: "",
    user_id: "",
    expected_files: 0,
    uploaded_files: 0,
    status: 0,
    expires_at: "",
    created_at: "",
    updated_at: "",
  };
}

export const UploadSession: MessageFns<UploadSession> = {
  encode(message: UploadSession, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.expected_files !== 0) {
      writer.uint32(24).int32(message.expected_files);
    }
    if (message.uploaded_files !== 0) {
      writer.uint32(32).int32(message.uploaded_files);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.upload_token !== undefined) {
      writer.uint32(50).string(message.upload_token);
    }
    if (message.metadata !== undefined) {
      writer.uint32(58).string(message.metadata);
    }
    if (message.expires_at !== "") {
      writer.uint32(66).string(message.expires_at);
    }
    if (message.created_at !== "") {
      writer.uint32(74).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(82).string(message.updated_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadSession {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expected_files = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.uploaded_files = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.upload_token = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.expires_at = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFileInfo(): FileInfo {
  return {
    file_id: "",
    file_name: "",
    original_name: "",
    file_size: 0,
    file_type: 0,
    mime_type: "",
    file_url: "",
    is_processed: false,
    processing_status: 0,
    visibility: 0,
    download_count: 0,
    view_count: 0,
    is_public: false,
    uploaded_by: "",
    tags: [],
    created_at: "",
    updated_at: "",
  };
}

export const FileInfo: MessageFns<FileInfo> = {
  encode(message: FileInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file_id !== "") {
      writer.uint32(10).string(message.file_id);
    }
    if (message.file_name !== "") {
      writer.uint32(18).string(message.file_name);
    }
    if (message.original_name !== "") {
      writer.uint32(26).string(message.original_name);
    }
    if (message.file_size !== 0) {
      writer.uint32(32).int64(message.file_size);
    }
    if (message.file_type !== 0) {
      writer.uint32(40).int32(message.file_type);
    }
    if (message.mime_type !== "") {
      writer.uint32(50).string(message.mime_type);
    }
    if (message.file_url !== "") {
      writer.uint32(58).string(message.file_url);
    }
    if (message.thumbnail_url !== undefined) {
      writer.uint32(66).string(message.thumbnail_url);
    }
    if (message.compressed_url !== undefined) {
      writer.uint32(74).string(message.compressed_url);
    }
    if (message.is_processed !== false) {
      writer.uint32(80).bool(message.is_processed);
    }
    if (message.processing_status !== 0) {
      writer.uint32(88).int32(message.processing_status);
    }
    if (message.processing_error !== undefined) {
      writer.uint32(98).string(message.processing_error);
    }
    if (message.visibility !== 0) {
      writer.uint32(104).int32(message.visibility);
    }
    if (message.download_count !== 0) {
      writer.uint32(112).int32(message.download_count);
    }
    if (message.view_count !== 0) {
      writer.uint32(120).int32(message.view_count);
    }
    if (message.is_public !== false) {
      writer.uint32(128).bool(message.is_public);
    }
    if (message.uploaded_by !== "") {
      writer.uint32(138).string(message.uploaded_by);
    }
    if (message.company_id !== undefined) {
      writer.uint32(146).string(message.company_id);
    }
    if (message.branch_id !== undefined) {
      writer.uint32(154).string(message.branch_id);
    }
    if (message.entity_type !== undefined) {
      writer.uint32(162).string(message.entity_type);
    }
    if (message.entity_id !== undefined) {
      writer.uint32(170).string(message.entity_id);
    }
    if (message.alt_text !== undefined) {
      writer.uint32(178).string(message.alt_text);
    }
    if (message.description !== undefined) {
      writer.uint32(186).string(message.description);
    }
    for (const v of message.tags) {
      writer.uint32(194).string(v!);
    }
    if (message.metadata !== undefined) {
      writer.uint32(202).string(message.metadata);
    }
    if (message.created_at !== "") {
      writer.uint32(210).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(218).string(message.updated_at);
    }
    if (message.deleted_at !== undefined) {
      writer.uint32(226).string(message.deleted_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.file_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.original_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.file_size = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.file_type = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.mime_type = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.file_url = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.thumbnail_url = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.compressed_url = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.is_processed = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.processing_status = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.processing_error = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.visibility = reader.int32() as any;
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.download_count = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.view_count = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.is_public = reader.bool();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.uploaded_by = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.company_id = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.branch_id = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.entity_type = reader.string();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.entity_id = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.alt_text = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.deleted_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** 📁 Files Service - handles file uploads, storage, and management */

export interface FilesServiceClient {
  verifyFile(request: VerifyFileRequest): Observable<VerifyFileResponse>;

  createOrUpdateFile(request: CreateOrUpdateFileRequest): Observable<CreateOrUpdateFileResponse>;

  /** Temporary Upload System (Two-Phase) */

  uploadTemporaryFile(request: UploadTemporaryFileRequest): Observable<TempFileResponse>;

  confirmFile(request: ConfirmFileRequest): Observable<ConfirmFileResponse>;

  getTempFile(request: GetTempFileRequest): Observable<TempFileResponse>;

  getTempFilesByUser(request: GetTempFilesByUserRequest): Observable<GetTempFilesResponse>;

  /** Direct Upload (Original) */

  uploadFile(request: UploadFileRequest): Observable<FileUploadResponse>;

  uploadMultipleFiles(request: UploadMultipleFilesRequest): Observable<MultipleFileUploadResponse>;

  /** Upload Sessions (Batch) */

  createUploadSession(request: CreateUploadSessionRequest): Observable<UploadSessionResponse>;

  confirmUploadSession(request: ConfirmUploadSessionRequest): Observable<ConfirmUploadSessionResponse>;

  getUploadSession(request: GetUploadSessionRequest): Observable<UploadSessionResponse>;

  /** File Management */

  deleteFile(request: DeleteFileRequest): Observable<DeleteFileResponse>;

  getFileInfo(request: GetFileInfoRequest): Observable<FileInfoResponse>;

  getUserFiles(request: GetUserFilesRequest): Observable<GetUserFilesResponse>;

  /** File Processing Status */

  getProcessingStatus(request: GetProcessingStatusRequest): Observable<ProcessingStatusResponse>;

  retryProcessing(request: RetryProcessingRequest): Observable<RetryProcessingResponse>;
}

/** 📁 Files Service - handles file uploads, storage, and management */

export interface FilesServiceController {
  verifyFile(
    request: VerifyFileRequest,
  ): Promise<VerifyFileResponse> | Observable<VerifyFileResponse> | VerifyFileResponse;

  createOrUpdateFile(
    request: CreateOrUpdateFileRequest,
  ): Promise<CreateOrUpdateFileResponse> | Observable<CreateOrUpdateFileResponse> | CreateOrUpdateFileResponse;

  /** Temporary Upload System (Two-Phase) */

  uploadTemporaryFile(
    request: UploadTemporaryFileRequest,
  ): Promise<TempFileResponse> | Observable<TempFileResponse> | TempFileResponse;

  confirmFile(
    request: ConfirmFileRequest,
  ): Promise<ConfirmFileResponse> | Observable<ConfirmFileResponse> | ConfirmFileResponse;

  getTempFile(request: GetTempFileRequest): Promise<TempFileResponse> | Observable<TempFileResponse> | TempFileResponse;

  getTempFilesByUser(
    request: GetTempFilesByUserRequest,
  ): Promise<GetTempFilesResponse> | Observable<GetTempFilesResponse> | GetTempFilesResponse;

  /** Direct Upload (Original) */

  uploadFile(
    request: UploadFileRequest,
  ): Promise<FileUploadResponse> | Observable<FileUploadResponse> | FileUploadResponse;

  uploadMultipleFiles(
    request: UploadMultipleFilesRequest,
  ): Promise<MultipleFileUploadResponse> | Observable<MultipleFileUploadResponse> | MultipleFileUploadResponse;

  /** Upload Sessions (Batch) */

  createUploadSession(
    request: CreateUploadSessionRequest,
  ): Promise<UploadSessionResponse> | Observable<UploadSessionResponse> | UploadSessionResponse;

  confirmUploadSession(
    request: ConfirmUploadSessionRequest,
  ): Promise<ConfirmUploadSessionResponse> | Observable<ConfirmUploadSessionResponse> | ConfirmUploadSessionResponse;

  getUploadSession(
    request: GetUploadSessionRequest,
  ): Promise<UploadSessionResponse> | Observable<UploadSessionResponse> | UploadSessionResponse;

  /** File Management */

  deleteFile(
    request: DeleteFileRequest,
  ): Promise<DeleteFileResponse> | Observable<DeleteFileResponse> | DeleteFileResponse;

  getFileInfo(request: GetFileInfoRequest): Promise<FileInfoResponse> | Observable<FileInfoResponse> | FileInfoResponse;

  getUserFiles(
    request: GetUserFilesRequest,
  ): Promise<GetUserFilesResponse> | Observable<GetUserFilesResponse> | GetUserFilesResponse;

  /** File Processing Status */

  getProcessingStatus(
    request: GetProcessingStatusRequest,
  ): Promise<ProcessingStatusResponse> | Observable<ProcessingStatusResponse> | ProcessingStatusResponse;

  retryProcessing(
    request: RetryProcessingRequest,
  ): Promise<RetryProcessingResponse> | Observable<RetryProcessingResponse> | RetryProcessingResponse;
}

export function FilesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "verifyFile",
      "createOrUpdateFile",
      "uploadTemporaryFile",
      "confirmFile",
      "getTempFile",
      "getTempFilesByUser",
      "uploadFile",
      "uploadMultipleFiles",
      "createUploadSession",
      "confirmUploadSession",
      "getUploadSession",
      "deleteFile",
      "getFileInfo",
      "getUserFiles",
      "getProcessingStatus",
      "retryProcessing",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FilesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FilesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FILES_SERVICE_NAME = "FilesService";

/** 📁 Files Service - handles file uploads, storage, and management */
export type FilesServiceService = typeof FilesServiceService;
export const FilesServiceService = {
  verifyFile: {
    path: "/files.FilesService/VerifyFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: VerifyFileRequest): Buffer => Buffer.from(VerifyFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VerifyFileRequest => VerifyFileRequest.decode(value),
    responseSerialize: (value: VerifyFileResponse): Buffer => Buffer.from(VerifyFileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VerifyFileResponse => VerifyFileResponse.decode(value),
  },
  createOrUpdateFile: {
    path: "/files.FilesService/CreateOrUpdateFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateOrUpdateFileRequest): Buffer =>
      Buffer.from(CreateOrUpdateFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateOrUpdateFileRequest => CreateOrUpdateFileRequest.decode(value),
    responseSerialize: (value: CreateOrUpdateFileResponse): Buffer =>
      Buffer.from(CreateOrUpdateFileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateOrUpdateFileResponse => CreateOrUpdateFileResponse.decode(value),
  },
  /** Temporary Upload System (Two-Phase) */
  uploadTemporaryFile: {
    path: "/files.FilesService/UploadTemporaryFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UploadTemporaryFileRequest): Buffer =>
      Buffer.from(UploadTemporaryFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadTemporaryFileRequest => UploadTemporaryFileRequest.decode(value),
    responseSerialize: (value: TempFileResponse): Buffer => Buffer.from(TempFileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TempFileResponse => TempFileResponse.decode(value),
  },
  confirmFile: {
    path: "/files.FilesService/ConfirmFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ConfirmFileRequest): Buffer => Buffer.from(ConfirmFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ConfirmFileRequest => ConfirmFileRequest.decode(value),
    responseSerialize: (value: ConfirmFileResponse): Buffer => Buffer.from(ConfirmFileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ConfirmFileResponse => ConfirmFileResponse.decode(value),
  },
  getTempFile: {
    path: "/files.FilesService/GetTempFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetTempFileRequest): Buffer => Buffer.from(GetTempFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetTempFileRequest => GetTempFileRequest.decode(value),
    responseSerialize: (value: TempFileResponse): Buffer => Buffer.from(TempFileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): TempFileResponse => TempFileResponse.decode(value),
  },
  getTempFilesByUser: {
    path: "/files.FilesService/GetTempFilesByUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetTempFilesByUserRequest): Buffer =>
      Buffer.from(GetTempFilesByUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetTempFilesByUserRequest => GetTempFilesByUserRequest.decode(value),
    responseSerialize: (value: GetTempFilesResponse): Buffer =>
      Buffer.from(GetTempFilesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetTempFilesResponse => GetTempFilesResponse.decode(value),
  },
  /** Direct Upload (Original) */
  uploadFile: {
    path: "/files.FilesService/UploadFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UploadFileRequest): Buffer => Buffer.from(UploadFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadFileRequest => UploadFileRequest.decode(value),
    responseSerialize: (value: FileUploadResponse): Buffer => Buffer.from(FileUploadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FileUploadResponse => FileUploadResponse.decode(value),
  },
  uploadMultipleFiles: {
    path: "/files.FilesService/UploadMultipleFiles",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UploadMultipleFilesRequest): Buffer =>
      Buffer.from(UploadMultipleFilesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadMultipleFilesRequest => UploadMultipleFilesRequest.decode(value),
    responseSerialize: (value: MultipleFileUploadResponse): Buffer =>
      Buffer.from(MultipleFileUploadResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MultipleFileUploadResponse => MultipleFileUploadResponse.decode(value),
  },
  /** Upload Sessions (Batch) */
  createUploadSession: {
    path: "/files.FilesService/CreateUploadSession",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateUploadSessionRequest): Buffer =>
      Buffer.from(CreateUploadSessionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUploadSessionRequest => CreateUploadSessionRequest.decode(value),
    responseSerialize: (value: UploadSessionResponse): Buffer =>
      Buffer.from(UploadSessionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UploadSessionResponse => UploadSessionResponse.decode(value),
  },
  confirmUploadSession: {
    path: "/files.FilesService/ConfirmUploadSession",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ConfirmUploadSessionRequest): Buffer =>
      Buffer.from(ConfirmUploadSessionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ConfirmUploadSessionRequest => ConfirmUploadSessionRequest.decode(value),
    responseSerialize: (value: ConfirmUploadSessionResponse): Buffer =>
      Buffer.from(ConfirmUploadSessionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ConfirmUploadSessionResponse => ConfirmUploadSessionResponse.decode(value),
  },
  getUploadSession: {
    path: "/files.FilesService/GetUploadSession",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUploadSessionRequest): Buffer =>
      Buffer.from(GetUploadSessionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadSessionRequest => GetUploadSessionRequest.decode(value),
    responseSerialize: (value: UploadSessionResponse): Buffer =>
      Buffer.from(UploadSessionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UploadSessionResponse => UploadSessionResponse.decode(value),
  },
  /** File Management */
  deleteFile: {
    path: "/files.FilesService/DeleteFile",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteFileRequest): Buffer => Buffer.from(DeleteFileRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteFileRequest => DeleteFileRequest.decode(value),
    responseSerialize: (value: DeleteFileResponse): Buffer => Buffer.from(DeleteFileResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteFileResponse => DeleteFileResponse.decode(value),
  },
  getFileInfo: {
    path: "/files.FilesService/GetFileInfo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetFileInfoRequest): Buffer => Buffer.from(GetFileInfoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetFileInfoRequest => GetFileInfoRequest.decode(value),
    responseSerialize: (value: FileInfoResponse): Buffer => Buffer.from(FileInfoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FileInfoResponse => FileInfoResponse.decode(value),
  },
  getUserFiles: {
    path: "/files.FilesService/GetUserFiles",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserFilesRequest): Buffer => Buffer.from(GetUserFilesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserFilesRequest => GetUserFilesRequest.decode(value),
    responseSerialize: (value: GetUserFilesResponse): Buffer =>
      Buffer.from(GetUserFilesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserFilesResponse => GetUserFilesResponse.decode(value),
  },
  /** File Processing Status */
  getProcessingStatus: {
    path: "/files.FilesService/GetProcessingStatus",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetProcessingStatusRequest): Buffer =>
      Buffer.from(GetProcessingStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetProcessingStatusRequest => GetProcessingStatusRequest.decode(value),
    responseSerialize: (value: ProcessingStatusResponse): Buffer =>
      Buffer.from(ProcessingStatusResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ProcessingStatusResponse => ProcessingStatusResponse.decode(value),
  },
  retryProcessing: {
    path: "/files.FilesService/RetryProcessing",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RetryProcessingRequest): Buffer =>
      Buffer.from(RetryProcessingRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RetryProcessingRequest => RetryProcessingRequest.decode(value),
    responseSerialize: (value: RetryProcessingResponse): Buffer =>
      Buffer.from(RetryProcessingResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RetryProcessingResponse => RetryProcessingResponse.decode(value),
  },
} as const;

export interface FilesServiceServer extends UntypedServiceImplementation {
  verifyFile: handleUnaryCall<VerifyFileRequest, VerifyFileResponse>;
  createOrUpdateFile: handleUnaryCall<CreateOrUpdateFileRequest, CreateOrUpdateFileResponse>;
  /** Temporary Upload System (Two-Phase) */
  uploadTemporaryFile: handleUnaryCall<UploadTemporaryFileRequest, TempFileResponse>;
  confirmFile: handleUnaryCall<ConfirmFileRequest, ConfirmFileResponse>;
  getTempFile: handleUnaryCall<GetTempFileRequest, TempFileResponse>;
  getTempFilesByUser: handleUnaryCall<GetTempFilesByUserRequest, GetTempFilesResponse>;
  /** Direct Upload (Original) */
  uploadFile: handleUnaryCall<UploadFileRequest, FileUploadResponse>;
  uploadMultipleFiles: handleUnaryCall<UploadMultipleFilesRequest, MultipleFileUploadResponse>;
  /** Upload Sessions (Batch) */
  createUploadSession: handleUnaryCall<CreateUploadSessionRequest, UploadSessionResponse>;
  confirmUploadSession: handleUnaryCall<ConfirmUploadSessionRequest, ConfirmUploadSessionResponse>;
  getUploadSession: handleUnaryCall<GetUploadSessionRequest, UploadSessionResponse>;
  /** File Management */
  deleteFile: handleUnaryCall<DeleteFileRequest, DeleteFileResponse>;
  getFileInfo: handleUnaryCall<GetFileInfoRequest, FileInfoResponse>;
  getUserFiles: handleUnaryCall<GetUserFilesRequest, GetUserFilesResponse>;
  /** File Processing Status */
  getProcessingStatus: handleUnaryCall<GetProcessingStatusRequest, ProcessingStatusResponse>;
  retryProcessing: handleUnaryCall<RetryProcessingRequest, RetryProcessingResponse>;
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
