// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.33.2
// source: files.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "files";

export enum FileType {
  FILE_TYPE_IMAGE = 0,
  FILE_TYPE_VIDEO = 1,
  FILE_TYPE_AUDIO = 2,
  UNRECOGNIZED = -1,
}

export enum TempFileStatus {
  TEMP_FILE_STATUS_TEMPORARY = 0,
  TEMP_FILE_STATUS_CONFIRMING = 1,
  TEMP_FILE_STATUS_EXPIRED = 2,
  TEMP_FILE_STATUS_FAILED = 3,
  UNRECOGNIZED = -1,
}

export enum UploadSessionStatus {
  UPLOAD_SESSION_STATUS_ACTIVE = 0,
  UPLOAD_SESSION_STATUS_CONFIRMING = 1,
  UPLOAD_SESSION_STATUS_COMPLETED = 2,
  UPLOAD_SESSION_STATUS_EXPIRED = 3,
  UPLOAD_SESSION_STATUS_CANCELLED = 4,
  UNRECOGNIZED = -1,
}

export enum ProcessingStatus {
  PROCESSING_STATUS_PENDING = 0,
  PROCESSING_STATUS_PROCESSING = 1,
  PROCESSING_STATUS_COMPLETED = 2,
  PROCESSING_STATUS_FAILED = 3,
  PROCESSING_STATUS_CANCELLED = 4,
  UNRECOGNIZED = -1,
}

export enum FileVisibility {
  FILE_VISIBILITY_PUBLIC = 0,
  FILE_VISIBILITY_PRIVATE = 1,
  FILE_VISIBILITY_ORGANIZATION = 2,
  FILE_VISIBILITY_BRANCH = 3,
  FILE_VISIBILITY_ROLE_RESTRICTED = 4,
  UNRECOGNIZED = -1,
}

export interface VerifyFileRequest {
  entityType: string;
  entityId: string;
}

export interface CreateOrUpdateFileRequest {
  entityType: string;
  entityId: string;
  fileUrl: string;
}

export interface CreateOrUpdateFileResponse {
  fileUrl: string;
}

export interface VerifyFileResponse {
  fileUrl: string;
}

export interface UploadTemporaryFileRequest {
  fileData: Uint8Array;
  fileName: string;
  mimeType: string;
  userId: string;
  /** JSON string */
  metadata?: string | undefined;
  sessionId?: string | undefined;
}

export interface ConfirmFileRequest {
  fileId: string;
  userId: string;
  /** JSON string */
  additionalMetadata?: string | undefined;
}

export interface GetTempFileRequest {
  fileId: string;
}

export interface GetTempFilesByUserRequest {
  userId: string;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface UploadFileRequest {
  fileData: Uint8Array;
  fileName: string;
  mimeType: string;
  userId: string;
  /** JSON string */
  metadata?: string | undefined;
}

export interface UploadMultipleFilesRequest {
  files: FileUploadData[];
  userId: string;
  /** JSON string */
  metadata?:
    | string
    | undefined;
  /** default true */
  temporary?: boolean | undefined;
  sessionId?: string | undefined;
}

export interface FileUploadData {
  fileData: Uint8Array;
  fileName: string;
  mimeType: string;
}

export interface CreateUploadSessionRequest {
  userId: string;
  expectedFiles: number;
  /** default 30 */
  expiresInMinutes?: number | undefined;
}

export interface ConfirmUploadSessionRequest {
  sessionId: string;
  userId: string;
  filesToKeep: string[];
}

export interface GetUploadSessionRequest {
  sessionId: string;
  userId: string;
}

export interface DeleteFileRequest {
  fileUrl: string;
  userId: string;
}

export interface GetFileInfoRequest {
  fileId: string;
  userId: string;
}

export interface GetUserFilesRequest {
  userId: string;
  fileType?: FileType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
}

export interface GetProcessingStatusRequest {
  fileId: string;
  userId: string;
}

export interface RetryProcessingRequest {
  fileId: string;
  userId: string;
}

export interface TempFileResponse {
  success: boolean;
  error?: string | undefined;
  fileUrl?: string | undefined;
}

export interface GetTempFilesResponse {
  success: boolean;
  error?: string | undefined;
  tempFiles: TempFile[];
  totalCount: number;
}

export interface ConfirmFileResponse {
  success: boolean;
  error?: string | undefined;
  permanentFileId?: string | undefined;
  fileName?: string | undefined;
  cloudinaryUrl?: string | undefined;
  fileType?: FileType | undefined;
  uploadJobId?: string | undefined;
}

export interface FileUploadResponse {
  success: boolean;
  error?: string | undefined;
  fileId?: string | undefined;
  fileName?: string | undefined;
  cloudinaryUrl?: string | undefined;
  fileType?: FileType | undefined;
  uploadJobId?: string | undefined;
}

export interface MultipleFileUploadResponse {
  success: boolean;
  error?: string | undefined;
  results: FileUploadResult[];
  totalFiles: number;
  successfulUploads: number;
}

export interface FileUploadResult {
  success: boolean;
  error?: string | undefined;
  fileId?: string | undefined;
  fileName?: string | undefined;
  cloudinaryUrl?: string | undefined;
  fileType?: FileType | undefined;
  status?: TempFileStatus | undefined;
  expiresAt?: string | undefined;
  uploadedAt?: string | undefined;
}

export interface UploadSessionResponse {
  success: boolean;
  error?: string | undefined;
  session?: UploadSession | undefined;
}

export interface ConfirmUploadSessionResponse {
  success: boolean;
  error?: string | undefined;
  sessionId?: string | undefined;
  confirmedFiles: ConfirmFileResponse[];
  deletedFiles: string[];
  status?: UploadSessionStatus | undefined;
}

export interface DeleteFileResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
}

export interface FileInfoResponse {
  success: boolean;
  error?: string | undefined;
  fileInfo?: FileInfo | undefined;
}

export interface GetUserFilesResponse {
  success: boolean;
  error?: string | undefined;
  files: FileInfo[];
  totalCount: number;
}

export interface ProcessingStatusResponse {
  success: boolean;
  error?: string | undefined;
  status?: ProcessingStatus | undefined;
  processingError?: string | undefined;
  progressPercentage?: number | undefined;
}

export interface RetryProcessingResponse {
  success: boolean;
  error?: string | undefined;
  jobId?: string | undefined;
  message: string;
}

export interface TempFile {
  fileId: string;
  userId: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
  fileType: FileType;
  cloudinaryUrl: string;
  status: TempFileStatus;
  /** JSON string */
  metadata?: string | undefined;
  sessionId?: string | undefined;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface UploadSession {
  sessionId: string;
  userId: string;
  expectedFiles: number;
  uploadedFiles: number;
  status: UploadSessionStatus;
  uploadToken?:
    | string
    | undefined;
  /** JSON string */
  metadata?: string | undefined;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface FileInfo {
  fileId: string;
  fileName: string;
  originalName: string;
  fileSize: number;
  fileType: FileType;
  mimeType: string;
  fileUrl: string;
  thumbnailUrl?: string | undefined;
  compressedUrl?: string | undefined;
  isProcessed: boolean;
  processingStatus: ProcessingStatus;
  processingError?: string | undefined;
  visibility: FileVisibility;
  downloadCount: number;
  viewCount: number;
  isPublic: boolean;
  uploadedBy: string;
  companyId?: string | undefined;
  branchId?: string | undefined;
  entityType?: string | undefined;
  entityId?: string | undefined;
  altText?: string | undefined;
  description?: string | undefined;
  tags: string[];
  /** JSON string */
  metadata?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export const FILES_PACKAGE_NAME = "files";

/** 📁 Files Service - handles file uploads, storage, and management */

export interface FilesServiceClient {
  verifyFile(request: VerifyFileRequest): Observable<VerifyFileResponse>;

  createOrUpdateFile(request: CreateOrUpdateFileRequest): Observable<CreateOrUpdateFileResponse>;

  /** Temporary Upload System (Two-Phase) */

  uploadTemporaryFile(request: UploadTemporaryFileRequest): Observable<TempFileResponse>;

  confirmFile(request: ConfirmFileRequest): Observable<ConfirmFileResponse>;

  getTempFile(request: GetTempFileRequest): Observable<TempFileResponse>;

  getTempFilesByUser(request: GetTempFilesByUserRequest): Observable<GetTempFilesResponse>;

  /** Direct Upload (Original) */

  uploadFile(request: UploadFileRequest): Observable<FileUploadResponse>;

  uploadMultipleFiles(request: UploadMultipleFilesRequest): Observable<MultipleFileUploadResponse>;

  /** Upload Sessions (Batch) */

  createUploadSession(request: CreateUploadSessionRequest): Observable<UploadSessionResponse>;

  confirmUploadSession(request: ConfirmUploadSessionRequest): Observable<ConfirmUploadSessionResponse>;

  getUploadSession(request: GetUploadSessionRequest): Observable<UploadSessionResponse>;

  /** File Management */

  deleteFile(request: DeleteFileRequest): Observable<DeleteFileResponse>;

  getFileInfo(request: GetFileInfoRequest): Observable<FileInfoResponse>;

  getUserFiles(request: GetUserFilesRequest): Observable<GetUserFilesResponse>;

  /** File Processing Status */

  getProcessingStatus(request: GetProcessingStatusRequest): Observable<ProcessingStatusResponse>;

  retryProcessing(request: RetryProcessingRequest): Observable<RetryProcessingResponse>;
}

/** 📁 Files Service - handles file uploads, storage, and management */

export interface FilesServiceController {
  verifyFile(
    request: VerifyFileRequest,
  ): Promise<VerifyFileResponse> | Observable<VerifyFileResponse> | VerifyFileResponse;

  createOrUpdateFile(
    request: CreateOrUpdateFileRequest,
  ): Promise<CreateOrUpdateFileResponse> | Observable<CreateOrUpdateFileResponse> | CreateOrUpdateFileResponse;

  /** Temporary Upload System (Two-Phase) */

  uploadTemporaryFile(
    request: UploadTemporaryFileRequest,
  ): Promise<TempFileResponse> | Observable<TempFileResponse> | TempFileResponse;

  confirmFile(
    request: ConfirmFileRequest,
  ): Promise<ConfirmFileResponse> | Observable<ConfirmFileResponse> | ConfirmFileResponse;

  getTempFile(request: GetTempFileRequest): Promise<TempFileResponse> | Observable<TempFileResponse> | TempFileResponse;

  getTempFilesByUser(
    request: GetTempFilesByUserRequest,
  ): Promise<GetTempFilesResponse> | Observable<GetTempFilesResponse> | GetTempFilesResponse;

  /** Direct Upload (Original) */

  uploadFile(
    request: UploadFileRequest,
  ): Promise<FileUploadResponse> | Observable<FileUploadResponse> | FileUploadResponse;

  uploadMultipleFiles(
    request: UploadMultipleFilesRequest,
  ): Promise<MultipleFileUploadResponse> | Observable<MultipleFileUploadResponse> | MultipleFileUploadResponse;

  /** Upload Sessions (Batch) */

  createUploadSession(
    request: CreateUploadSessionRequest,
  ): Promise<UploadSessionResponse> | Observable<UploadSessionResponse> | UploadSessionResponse;

  confirmUploadSession(
    request: ConfirmUploadSessionRequest,
  ): Promise<ConfirmUploadSessionResponse> | Observable<ConfirmUploadSessionResponse> | ConfirmUploadSessionResponse;

  getUploadSession(
    request: GetUploadSessionRequest,
  ): Promise<UploadSessionResponse> | Observable<UploadSessionResponse> | UploadSessionResponse;

  /** File Management */

  deleteFile(
    request: DeleteFileRequest,
  ): Promise<DeleteFileResponse> | Observable<DeleteFileResponse> | DeleteFileResponse;

  getFileInfo(request: GetFileInfoRequest): Promise<FileInfoResponse> | Observable<FileInfoResponse> | FileInfoResponse;

  getUserFiles(
    request: GetUserFilesRequest,
  ): Promise<GetUserFilesResponse> | Observable<GetUserFilesResponse> | GetUserFilesResponse;

  /** File Processing Status */

  getProcessingStatus(
    request: GetProcessingStatusRequest,
  ): Promise<ProcessingStatusResponse> | Observable<ProcessingStatusResponse> | ProcessingStatusResponse;

  retryProcessing(
    request: RetryProcessingRequest,
  ): Promise<RetryProcessingResponse> | Observable<RetryProcessingResponse> | RetryProcessingResponse;
}

export function FilesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "verifyFile",
      "createOrUpdateFile",
      "uploadTemporaryFile",
      "confirmFile",
      "getTempFile",
      "getTempFilesByUser",
      "uploadFile",
      "uploadMultipleFiles",
      "createUploadSession",
      "confirmUploadSession",
      "getUploadSession",
      "deleteFile",
      "getFileInfo",
      "getUserFiles",
      "getProcessingStatus",
      "retryProcessing",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FilesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FilesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FILES_SERVICE_NAME = "FilesService";
