// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: financials.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "financials";

export enum walletEntityTypeEnum {
  ORGANIZATION = 0,
  COMPANY = 1,
  BRANCH = 2,
  ADMIN = 3,
  USER = 4,
  UNRECOGNIZED = -1,
}

export interface CreateWalletRequest {
  entityId: string;
  entityType: walletEntityTypeEnum;
  currencyCode: string;
}

export interface UpdateWalletRequest {
  entityId: string;
  entityType: string;
  currencyCode: string;
  balance: number;
}

export interface WalletTransactionRequest {
  walletId: string;
  amount: number;
  description: string;
  /** "credit" or "debit" */
  kind: string;
}

export interface WalletTransferRequest {
  fromEntityType: string;
  fromEntityId: string;
  currencyCode: string;
  toEntityType: string;
  toEntityId: string;
  amount: number;
  description: string;
}

export interface WalletReply {
  success: boolean;
  message: string;
  wallet: Wallet | undefined;
}

export interface Wallet {
  walletId: string;
  entityId: string;
  entityType: string;
  currencyCode: string;
  balance: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export const FINANCIALS_PACKAGE_NAME = "financials";

export interface FinancialsServiceClient {
  createWallet(request: CreateWalletRequest): Observable<WalletReply>;

  updateWallet(request: UpdateWalletRequest): Observable<WalletReply>;

  credit(request: WalletTransactionRequest): Observable<WalletReply>;

  debit(request: WalletTransactionRequest): Observable<WalletReply>;

  transfer(request: WalletTransferRequest): Observable<WalletReply>;
}

export interface FinancialsServiceController {
  createWallet(request: CreateWalletRequest): Promise<WalletReply> | Observable<WalletReply> | WalletReply;

  updateWallet(request: UpdateWalletRequest): Promise<WalletReply> | Observable<WalletReply> | WalletReply;

  credit(request: WalletTransactionRequest): Promise<WalletReply> | Observable<WalletReply> | WalletReply;

  debit(request: WalletTransactionRequest): Promise<WalletReply> | Observable<WalletReply> | WalletReply;

  transfer(request: WalletTransferRequest): Promise<WalletReply> | Observable<WalletReply> | WalletReply;
}

export function FinancialsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createWallet", "updateWallet", "credit", "debit", "transfer"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FinancialsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FinancialsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FINANCIALS_SERVICE_NAME = "FinancialsService";
