// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: financial.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "financial";

export interface CreateCategoryRequest {
  name: string;
  description: string;
}

export interface CreateCategoryResponse {
  id: string;
}

export const FINANCIAL_PACKAGE_NAME = "financial";

/** 📁 Files Service - handles file uploads, storage, and management */

export interface FinancialServiceClient {
  createCategory(request: CreateCategoryRequest): Observable<CreateCategoryResponse>;
}

/** 📁 Files Service - handles file uploads, storage, and management */

export interface FinancialServiceController {
  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CreateCategoryResponse> | Observable<CreateCategoryResponse> | CreateCategoryResponse;
}

export function FinancialServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createCategory"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FinancialService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FinancialService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FINANCIAL_SERVICE_NAME = "FinancialService";
