// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: operations.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "operations";

export interface EmptyRequest {
}

export interface CreateServiceTypeRequest {
  /** e.g., RESTAURANT, HOTEL, SPA, GYM, etc. */
  name: string;
}

export interface CreateServiceTypeResponse {
  success: boolean;
  message: string;
  data?: ServiceType | undefined;
}

export interface UpdateServiceTypeRequest {
  serviceTypeId: string;
  name: string;
}

/** The request message containing the user's name. */
export interface HelloRequest {
  name: string;
}

/** The response message containing the greetings. */
export interface HelloReply {
  message: string;
}

export interface HealthCheckRequest {
}

export interface HealthCheckResponse {
  status: string;
}

/** --- Company Services Creation --- */
export interface CreateCompanyServicesRequest {
  companyId: string;
  businessTypeId: number;
  name: string;
  basePrice: string;
  description: string;
  isActive: boolean;
  branchId?: string | undefined;
  businessTypes: BusinessTypeRequest[];
}

export interface CreateCompanyServicesResponse {
  message: string;
  success: boolean;
  data?: CompanyServiceData | undefined;
}

/** --- Update Company Service --- */
export interface UpdateCompanyServiceStatusRequest {
  companyServiceId: string;
  isActive?: boolean | undefined;
}

export interface UpdateCompanyServiceRequest {
  companyServiceId: string;
  businessTypeId?: number | undefined;
  name?: string | undefined;
  basePrice?: string | undefined;
  description?: string | undefined;
  isActive?: boolean | undefined;
}

export interface UpdateCompanyServiceResponse {
  success: boolean;
  message: string;
  data?: CompanyServiceData | undefined;
}

/** --- Delete Company Service (Soft Delete) --- */
export interface DeleteCompanyServiceRequest {
  companyServiceId: string;
}

export interface DeleteCompanyServiceResponse {
  success: boolean;
  message: string;
}

/** --- Get Company Services --- */
export interface GetCompanyServicesRequest {
  companyId: string;
  branchId?: string | undefined;
  includeInactive?: boolean | undefined;
}

/** --- Get Company Services --- */
export interface GetCompanyServiceRequest {
  companyServiceId: string;
}

/** --- Search Company Services with Filters --- */
export interface SearchCompanyServicesRequest {
  /** Optional - filter by company, if not provided returns all companies */
  companyId?:
    | string
    | undefined;
  /** Filter by service/business type name */
  serviceName?:
    | string
    | undefined;
  /** Filter by business type ID */
  businessTypeId?:
    | number
    | undefined;
  /** Include inactive services */
  includeInactive?:
    | boolean
    | undefined;
  /** Filter by branch */
  branchId?:
    | string
    | undefined;
  /** Include soft-deleted services (default: false) */
  includeDeleted?: boolean | undefined;
}

export interface GetCompanyServiceResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  companyService: CompanyServiceData | undefined;
}

export interface GetCompanyServicesResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  companyServices: CompanyServiceData[];
}

export interface CompanyServiceData {
  companyServiceId: string;
  companyId: string;
  businessTypeId: number;
  name: string;
  price: string;
  description: string;
  isActive: boolean;
  branchId?: string | undefined;
  createdAt: string;
  updatedAt: string;
  businessType?: BusinessType | undefined;
  serviceBranches: ServiceBranch[];
}

export interface BusinessTypeRequest {
  /** RESTAURANT, HOTEL, SPA, GYM, etc. */
  type: string;
  description: string;
  checkInTime: string;
  checkOutTime: string;
  businessHours: BusinessHourRequest[];
  restaurantTableTypes: RestaurantTableTypeRequest[];
  hotelRoomTypes: HotelRoomTypeRequest[];
}

export interface BusinessHourRequest {
  /** MONDAY, TUESDAY, etc. */
  dayOfWeek: string;
  startTime: string;
  endTime: string;
}

export interface RestaurantTableTypeRequest {
  name: string;
  seatingCapacity: number;
  description: string;
  tables: RestaurantTableRequest[];
}

export interface RestaurantTableRequest {
  name: string;
  locationId: number;
  description: string;
}

export interface OrganizationIdRequest {
  organizationId: string;
}

export interface HotelRoomTypeRequest {
  name: string;
  description: string;
  pricePerNight: number;
  maxOccupancy: number;
  bedSizeId: number;
  hotelRooms: HotelRoomRequest[];
}

export interface HotelRoomRequest {
  ref: string;
  locationId: number;
  description: string;
  isActive: boolean;
}

/** --- Service Branch Creation --- */
export interface CreateServiceBranchRequest {
  branchId: string;
  serviceId: string;
  serviceTypeName: string;
  description: string;
  checkInTime: string;
  checkOutTime: string;
}

export interface CreateServiceBranchResponse {
  serviceBranchId: string;
}

export interface CreateTableLocationRequest {
  name: string;
  organizationId: string;
  creatorId: string;
}

export interface CreateBedSizeRequest {
  name: string;
  organizationId: string;
  creatorId: string;
}

export interface CreateRoomLocationRequest {
  name: string;
  organizationId: string;
  creatorId: string;
}

/** --- Business Hours Upsert --- */
export interface UpsertBusinessHoursRequest {
  serviceBranchId: string;
  businessDay: string;
  startTime: string;
  endTime: string;
}

export interface UpsertBusinessHoursResponse {
  businessHoursId: string;
}

export interface ServiceType {
  serviceTypeId: string;
  name: string;
}

export interface GetServiceTypesResponse {
  success: boolean;
  error?: string | undefined;
  serviceTypes: ServiceType[];
}

/** Business Types Messages */
export interface CreateBusinessTypeRequest {
  name: string;
  description: string;
  isActive: boolean;
}

export interface CreateBusinessTypeResponse {
  success: boolean;
  message: string;
  data?: BusinessTypeData | undefined;
}

export interface UpdateBusinessTypeActiveStatusRequest {
  businessTypeId: number;
}

export interface UpdateBusinessTypeActiveStatusResponse {
  success: boolean;
  message: string;
  data?: BusinessTypeData | undefined;
}

export interface GetBusinessTypesResponse {
  success: boolean;
  error?: string | undefined;
  businessTypes: BusinessTypeData[];
}

export interface BusinessTypeData {
  businessTypeId: number;
  name: string;
  description: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface GetBedSizesResponse {
  success: boolean;
  error?: string | undefined;
  bedSizes: BedSize[];
}

export interface DeleteTableLocationRequest {
  tableLocationId: number;
}

export interface DeleteBedSizeRequest {
  bedSizeId: number;
}

export interface DeleteRoomLocationRequest {
  roomLocationId: number;
}

export interface GetTableLocationsResponse {
  success: boolean;
  error?: string | undefined;
  tableLocations: TableLocation[];
}

export interface GetRoomLocationsResponse {
  success: boolean;
  error?: string | undefined;
  roomLocations: RoomLocation[];
}

export interface UtilitiesResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
}

export interface TableLocation {
  tableLocationId: number;
  name: string;
  description: string;
  isGlobal: boolean;
  isActive: boolean;
}

export interface RoomLocation {
  roomLocationId: number;
  name: string;
  description: string;
  isGlobal: boolean;
  isActive: boolean;
}

export interface HotelRoomType {
  name: string;
  description?: string | undefined;
  pricePerNight: number;
  maxOccupancy: number;
  bedSizeId: number;
  hotelRooms: HotelRoom[];
}

export interface HotelRoom {
  ref: string;
  description?: string | undefined;
  locationId: number;
  isActive?: boolean | undefined;
}

export interface BedSize {
  bedSizeId: number;
  name: string;
  description: string;
  isGlobal: boolean;
  isActive: boolean;
}

export interface BusinessType {
  businessTypeId: number;
  name: string;
  description: string;
  isActive: boolean;
}

export interface ServiceBranch {
  serviceBranchId: string;
  branchId: string;
  serviceId: string;
  serviceTypeName: string;
  description: string;
  checkInTime: string;
  checkOutTime: string;
  businessHours: BusinessHours[];
  restaurantTableTypes: RestaurantTableType[];
  hotelRoomTypes: HotelRoomType[];
}

export interface BusinessHours {
  dayOfWeek: string;
  startTime: string;
  endTime: string;
  isActive: boolean;
}

export interface RestaurantTableType {
  name?: string | undefined;
  description?: string | undefined;
  seatingCapacity?: number | undefined;
  tables: RestaurantTable[];
}

export interface RestaurantTable {
  name?: string | undefined;
  description?: string | undefined;
  locationId?: number | undefined;
}

export const OPERATIONS_PACKAGE_NAME = "operations";

/** The greeting service definition. */

export interface OperationServiceClient {
  /** Sends a greeting */

  sayHello(request: HelloRequest): Observable<HelloReply>;

  healthCheck(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  /** Company Services Management */

  createCompanyServices(request: CreateCompanyServicesRequest): Observable<CreateCompanyServicesResponse>;

  updateCompanyServiceStatus(request: UpdateCompanyServiceStatusRequest): Observable<UpdateCompanyServiceResponse>;

  updateCompanyService(request: UpdateCompanyServiceRequest): Observable<UpdateCompanyServiceResponse>;

  deleteCompanyService(request: DeleteCompanyServiceRequest): Observable<DeleteCompanyServiceResponse>;

  getCompanyServices(request: GetCompanyServicesRequest): Observable<GetCompanyServicesResponse>;

  getCompanyService(request: GetCompanyServiceRequest): Observable<GetCompanyServiceResponse>;

  searchCompanyServices(request: SearchCompanyServicesRequest): Observable<GetCompanyServicesResponse>;

  createServiceBranch(request: CreateServiceBranchRequest): Observable<CreateServiceBranchResponse>;

  upsertBusinessHours(request: UpsertBusinessHoursRequest): Observable<UpsertBusinessHoursResponse>;

  /** Service Types Management */

  getServiceTypes(request: EmptyRequest): Observable<GetServiceTypesResponse>;

  createServiceType(request: CreateServiceTypeRequest): Observable<CreateServiceTypeResponse>;

  updateServiceType(request: UpdateServiceTypeRequest): Observable<CreateServiceTypeResponse>;

  /** Business Types Management */

  getAdminBusinessTypes(request: EmptyRequest): Observable<GetBusinessTypesResponse>;

  getBusinessTypes(request: EmptyRequest): Observable<GetBusinessTypesResponse>;

  createBusinessType(request: CreateBusinessTypeRequest): Observable<CreateBusinessTypeResponse>;

  updateBusinessTypeActiveStatus(
    request: UpdateBusinessTypeActiveStatusRequest,
  ): Observable<UpdateBusinessTypeActiveStatusResponse>;

  fetchServiceTypes(request: EmptyRequest): Observable<GetServiceTypesResponse>;

  getTableLocations(request: OrganizationIdRequest): Observable<GetTableLocationsResponse>;

  getBedSizes(request: OrganizationIdRequest): Observable<GetBedSizesResponse>;

  getRoomLocations(request: OrganizationIdRequest): Observable<GetRoomLocationsResponse>;

  /** Delete Utilities */

  deleteTableLocation(request: DeleteTableLocationRequest): Observable<UtilitiesResponse>;

  deleteBedSize(request: DeleteBedSizeRequest): Observable<UtilitiesResponse>;

  deleteRoomLocation(request: DeleteRoomLocationRequest): Observable<UtilitiesResponse>;

  /** CREATE UTILITIES */

  createTableLocation(request: CreateTableLocationRequest): Observable<UtilitiesResponse>;

  createBedSize(request: CreateBedSizeRequest): Observable<UtilitiesResponse>;

  createRoomLocation(request: CreateRoomLocationRequest): Observable<UtilitiesResponse>;
}

/** The greeting service definition. */

export interface OperationServiceController {
  /** Sends a greeting */

  sayHello(request: HelloRequest): Promise<HelloReply> | Observable<HelloReply> | HelloReply;

  healthCheck(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  /** Company Services Management */

  createCompanyServices(
    request: CreateCompanyServicesRequest,
  ): Promise<CreateCompanyServicesResponse> | Observable<CreateCompanyServicesResponse> | CreateCompanyServicesResponse;

  updateCompanyServiceStatus(
    request: UpdateCompanyServiceStatusRequest,
  ): Promise<UpdateCompanyServiceResponse> | Observable<UpdateCompanyServiceResponse> | UpdateCompanyServiceResponse;

  updateCompanyService(
    request: UpdateCompanyServiceRequest,
  ): Promise<UpdateCompanyServiceResponse> | Observable<UpdateCompanyServiceResponse> | UpdateCompanyServiceResponse;

  deleteCompanyService(
    request: DeleteCompanyServiceRequest,
  ): Promise<DeleteCompanyServiceResponse> | Observable<DeleteCompanyServiceResponse> | DeleteCompanyServiceResponse;

  getCompanyServices(
    request: GetCompanyServicesRequest,
  ): Promise<GetCompanyServicesResponse> | Observable<GetCompanyServicesResponse> | GetCompanyServicesResponse;

  getCompanyService(
    request: GetCompanyServiceRequest,
  ): Promise<GetCompanyServiceResponse> | Observable<GetCompanyServiceResponse> | GetCompanyServiceResponse;

  searchCompanyServices(
    request: SearchCompanyServicesRequest,
  ): Promise<GetCompanyServicesResponse> | Observable<GetCompanyServicesResponse> | GetCompanyServicesResponse;

  createServiceBranch(
    request: CreateServiceBranchRequest,
  ): Promise<CreateServiceBranchResponse> | Observable<CreateServiceBranchResponse> | CreateServiceBranchResponse;

  upsertBusinessHours(
    request: UpsertBusinessHoursRequest,
  ): Promise<UpsertBusinessHoursResponse> | Observable<UpsertBusinessHoursResponse> | UpsertBusinessHoursResponse;

  /** Service Types Management */

  getServiceTypes(
    request: EmptyRequest,
  ): Promise<GetServiceTypesResponse> | Observable<GetServiceTypesResponse> | GetServiceTypesResponse;

  createServiceType(
    request: CreateServiceTypeRequest,
  ): Promise<CreateServiceTypeResponse> | Observable<CreateServiceTypeResponse> | CreateServiceTypeResponse;

  updateServiceType(
    request: UpdateServiceTypeRequest,
  ): Promise<CreateServiceTypeResponse> | Observable<CreateServiceTypeResponse> | CreateServiceTypeResponse;

  /** Business Types Management */

  getAdminBusinessTypes(
    request: EmptyRequest,
  ): Promise<GetBusinessTypesResponse> | Observable<GetBusinessTypesResponse> | GetBusinessTypesResponse;

  getBusinessTypes(
    request: EmptyRequest,
  ): Promise<GetBusinessTypesResponse> | Observable<GetBusinessTypesResponse> | GetBusinessTypesResponse;

  createBusinessType(
    request: CreateBusinessTypeRequest,
  ): Promise<CreateBusinessTypeResponse> | Observable<CreateBusinessTypeResponse> | CreateBusinessTypeResponse;

  updateBusinessTypeActiveStatus(
    request: UpdateBusinessTypeActiveStatusRequest,
  ):
    | Promise<UpdateBusinessTypeActiveStatusResponse>
    | Observable<UpdateBusinessTypeActiveStatusResponse>
    | UpdateBusinessTypeActiveStatusResponse;

  fetchServiceTypes(
    request: EmptyRequest,
  ): Promise<GetServiceTypesResponse> | Observable<GetServiceTypesResponse> | GetServiceTypesResponse;

  getTableLocations(
    request: OrganizationIdRequest,
  ): Promise<GetTableLocationsResponse> | Observable<GetTableLocationsResponse> | GetTableLocationsResponse;

  getBedSizes(
    request: OrganizationIdRequest,
  ): Promise<GetBedSizesResponse> | Observable<GetBedSizesResponse> | GetBedSizesResponse;

  getRoomLocations(
    request: OrganizationIdRequest,
  ): Promise<GetRoomLocationsResponse> | Observable<GetRoomLocationsResponse> | GetRoomLocationsResponse;

  /** Delete Utilities */

  deleteTableLocation(
    request: DeleteTableLocationRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  deleteBedSize(
    request: DeleteBedSizeRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  deleteRoomLocation(
    request: DeleteRoomLocationRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  /** CREATE UTILITIES */

  createTableLocation(
    request: CreateTableLocationRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  createBedSize(
    request: CreateBedSizeRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  createRoomLocation(
    request: CreateRoomLocationRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;
}

export function OperationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "sayHello",
      "healthCheck",
      "createCompanyServices",
      "updateCompanyServiceStatus",
      "updateCompanyService",
      "deleteCompanyService",
      "getCompanyServices",
      "getCompanyService",
      "searchCompanyServices",
      "createServiceBranch",
      "upsertBusinessHours",
      "getServiceTypes",
      "createServiceType",
      "updateServiceType",
      "getAdminBusinessTypes",
      "getBusinessTypes",
      "createBusinessType",
      "updateBusinessTypeActiveStatus",
      "fetchServiceTypes",
      "getTableLocations",
      "getBedSizes",
      "getRoomLocations",
      "deleteTableLocation",
      "deleteBedSize",
      "deleteRoomLocation",
      "createTableLocation",
      "createBedSize",
      "createRoomLocation",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OperationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OperationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OPERATION_SERVICE_NAME = "OperationService";
