// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.32.0
// source: operations.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "operations";

export interface EmptyRequest {
}

export interface CreateServiceTypeRequest {
  /** e.g., RESTAURANT, HOTEL, SPA, GYM, etc. */
  name: string;
}

export interface CreateServiceTypeResponse {
  success: boolean;
  message: string;
  data?: ServiceType | undefined;
}

export interface UpdateServiceTypeRequest {
  serviceTypeId: string;
  name: string;
}

/** The request message containing the user's name. */
export interface HelloRequest {
  name: string;
}

/** The response message containing the greetings. */
export interface HelloReply {
  message: string;
}

export interface HealthCheckRequest {
}

export interface HealthCheckResponse {
  status: string;
}

/** --- Company Services Creation --- */
export interface CreateCompanyServicesRequest {
  companyId: string;
  branchId: string;
  businessTypes: BusinessTypeRequest[];
}

export interface CreateCompanyServicesResponse {
  message: string;
  success: boolean;
}

export interface BusinessTypeRequest {
  /** RESTAURANT, HOTEL, SPA, GYM, etc. */
  type: string;
  description: string;
  checkInTime: string;
  checkOutTime: string;
  businessHours: BusinessHourRequest[];
  restaurantTableTypes: RestaurantTableTypeRequest[];
  hotelRoomTypes: HotelRoomTypeRequest[];
}

export interface BusinessHourRequest {
  /** MONDAY, TUESDAY, etc. */
  dayOfWeek: string;
  startTime: string;
  endTime: string;
}

export interface RestaurantTableTypeRequest {
  name: string;
  seatingCapacity: number;
  description: string;
  tables: RestaurantTableRequest[];
}

export interface RestaurantTableRequest {
  name: string;
  locationId: number;
  description: string;
}

export interface HotelRoomTypeRequest {
  name: string;
  description: string;
  pricePerNight: number;
  maxOccupancy: number;
  bedSizeId: number;
  hotelRooms: HotelRoomRequest[];
}

export interface HotelRoomRequest {
  ref: string;
  locationId: number;
  description: string;
  isActive: boolean;
}

/** --- Service Branch Creation --- */
export interface CreateServiceBranchRequest {
  branchId: string;
  serviceId: string;
  serviceTypeName: string;
  description: string;
  checkInTime: string;
  checkOutTime: string;
}

export interface CreateServiceBranchResponse {
  serviceBranchId: string;
}

/** --- Business Hours Upsert --- */
export interface UpsertBusinessHoursRequest {
  serviceBranchId: string;
  businessDay: string;
  startTime: string;
  endTime: string;
}

export interface UpsertBusinessHoursResponse {
  businessHoursId: string;
}

export interface ServiceType {
  serviceTypeId: string;
  name: string;
}

export const OPERATIONS_PACKAGE_NAME = "operations";

/** The greeting service definition. */

export interface OperationServiceClient {
  /** Sends a greeting */

  sayHello(request: HelloRequest): Observable<HelloReply>;

  healthCheck(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  /** Company Services Management */

  createCompanyServices(request: CreateCompanyServicesRequest): Observable<CreateCompanyServicesResponse>;

  createServiceBranch(request: CreateServiceBranchRequest): Observable<CreateServiceBranchResponse>;

  upsertBusinessHours(request: UpsertBusinessHoursRequest): Observable<UpsertBusinessHoursResponse>;

  /** Service Types Management */

  getServiceTypes(request: EmptyRequest): Observable<CreateServiceTypeResponse>;

  createServiceType(request: CreateServiceTypeRequest): Observable<CreateServiceTypeResponse>;

  updateServiceType(request: UpdateServiceTypeRequest): Observable<CreateServiceTypeResponse>;
}

/** The greeting service definition. */

export interface OperationServiceController {
  /** Sends a greeting */

  sayHello(request: HelloRequest): Promise<HelloReply> | Observable<HelloReply> | HelloReply;

  healthCheck(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  /** Company Services Management */

  createCompanyServices(
    request: CreateCompanyServicesRequest,
  ): Promise<CreateCompanyServicesResponse> | Observable<CreateCompanyServicesResponse> | CreateCompanyServicesResponse;

  createServiceBranch(
    request: CreateServiceBranchRequest,
  ): Promise<CreateServiceBranchResponse> | Observable<CreateServiceBranchResponse> | CreateServiceBranchResponse;

  upsertBusinessHours(
    request: UpsertBusinessHoursRequest,
  ): Promise<UpsertBusinessHoursResponse> | Observable<UpsertBusinessHoursResponse> | UpsertBusinessHoursResponse;

  /** Service Types Management */

  getServiceTypes(
    request: EmptyRequest,
  ): Promise<CreateServiceTypeResponse> | Observable<CreateServiceTypeResponse> | CreateServiceTypeResponse;

  createServiceType(
    request: CreateServiceTypeRequest,
  ): Promise<CreateServiceTypeResponse> | Observable<CreateServiceTypeResponse> | CreateServiceTypeResponse;

  updateServiceType(
    request: UpdateServiceTypeRequest,
  ): Promise<CreateServiceTypeResponse> | Observable<CreateServiceTypeResponse> | CreateServiceTypeResponse;
}

export function OperationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "sayHello",
      "healthCheck",
      "createCompanyServices",
      "createServiceBranch",
      "upsertBusinessHours",
      "getServiceTypes",
      "createServiceType",
      "updateServiceType",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OperationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OperationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OPERATION_SERVICE_NAME = "OperationService";
