// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.33.2
// source: organization.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "organization";

export enum RoleType {
  STAFF_ROLE = 0,
  BUSINESS_USER_ROLE = 1,
  UNRECOGNIZED = -1,
}

export enum DepartmentTypeEnum {
  KITCHEN = 0,
  RECEPTION = 1,
  HR = 2,
  LEGAL = 3,
  OPERATIONS = 4,
  CUSTOM = 5,
  UNRECOGNIZED = -1,
}

export interface CompanyRoleRequest {
  companyId: string;
  roleId: string;
}

export interface CompanyRolesRequest {
  companyId: string;
  branchId?: string | undefined;
  roleType: RoleType;
}

export interface UpdateCompanyDetailsRequest {
  companyId: string;
  name: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
  countryCode: string;
  companyLogo: string;
  baseCurrency: string;
  address?: AddressRequest | undefined;
}

export interface OrganizationRoleIdRequest {
  organizationRoleSlug: string;
  organizationId: string;
}

export interface FetchCompanyRequest {
  companyId: string;
}

export interface FetchCompanyResponse {
  success: boolean;
  error?: string | undefined;
  company: Company | undefined;
  message: string;
}

export interface FetchBranchResponse {
  success: boolean;
  error?: string | undefined;
  branch: Branch | undefined;
  message: string;
}

export interface FetchBranchesResponse {
  success: boolean;
  error?: string | undefined;
  branches: Branch[];
  message: string;
}

export interface FetchRolesResponse {
  success: boolean;
  error?: string | undefined;
  organizationRoles: OrganizationRole[];
}

export interface FetchRoleResponse {
  success: boolean;
  error?: string | undefined;
  organizationRole: OrganizationRole | undefined;
}

export interface RoleData {
  organizationRole: OrganizationRole | undefined;
}

export interface CreateBusinessUserRoleRequest {
  organizationId: string;
  roleName: string;
  description: string;
  businessUserIds: string[];
  permissions: Permission[];
  creatorId: string;
}

export interface CreateRoleRequest {
  companyId: string;
  roleName: string;
  description: string;
  staffIds: string[];
  businessUserIds: string[];
  permissions: Permission[];
  creatorId: string;
  roleType: RoleType;
  branchId?: string | undefined;
}

export interface UpdateRoleRequest {
  roleId: string;
  companyId: string;
  roleName: string;
  description: string;
  staffIds: string[];
  businessUserIds: string[];
  permissions: Permission[];
  creatorId: string;
  roleType: RoleType;
  branchId?: string | undefined;
}

export interface Permission {
  permissionName: string;
  state: boolean;
}

export interface EmptyRequest {
}

export interface BranchIdRequest {
  branchId: string;
}

export interface OrganizationIdRequest {
  organizationId: string;
}

export interface ServiceType {
  serviceTypeId: number;
  name: string;
  description: string;
  isActive: boolean;
}

/** � RESPONSE MESSAGES */
export interface BusinessUserRole {
  businessUserId: string;
  organizationRoleId: string;
  isActive: boolean;
  Count: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

export interface StaffCompanyRole {
  staffId: string;
  companyRoleId: string;
  isActive: boolean;
  companyRole: OrganizationRole | undefined;
}

export interface EntityPermission {
  entityId: string;
  entityType: string;
  permissionId: string;
  isGranted: boolean;
  grantedAt: string;
  grantedByUserId: string;
  level: number;
  permission: PermissionResponse | undefined;
}

export interface PermissionResponse {
  permissionId: string;
  permissionName: string;
  description: string;
  level: number;
  createdAt: string;
  updatedAt: string;
}

export interface OrganizationRole {
  roleId: string;
  organizationId: string;
  companyId: string;
  branchId: string;
  name: string;
  slug: string;
  description: string;
  isActive: boolean;
  businessUserRolesCount: number;
  isOrgLevel: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  businessUserRoles: BusinessUserRole[];
  staffCompanyRoles: StaffCompanyRole[];
  entityPermissions: EntityPermission[];
}

export interface UtilitiesResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
}

export interface FetchCompaniesResponse {
  success: boolean;
  error?: string | undefined;
  companies: Company[];
}

export interface ValidateCompanyReferenceRequest {
  companyRef: string;
}

export interface ValidateCompanyReferenceResponse {
  success: boolean;
  error?: string | undefined;
  company: Company | undefined;
}

export interface VerifyCompanyIdRequest {
  companyId: string;
  organizationId: string;
}

export interface VerifyCompanyIdResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  company?: Company | undefined;
}

export interface VerifyBranchIdRequest {
  branchId: string;
  companyId: string;
  organizationId: string;
}

export interface VerifyBranchIdResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  branch?: Branch | undefined;
}

export interface VerifyDepartmentIdRequest {
  companyId: string;
  organizationId: string;
  departmentId: string;
}

export interface VerifyDepartmentIdResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  department?: Department | undefined;
}

export interface VerifyRoleIdRequest {
  companyId: string;
  roleId: string;
}

export interface VerifyRoleIdResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  role?: OrganizationRole | undefined;
}

export interface CreateCompanyRequest {
  name: string;
  organizationId: string;
  creatorId: string;
  description: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
  companyLogo: string;
  isMultiBranch: boolean;
  /** repeated BusinessType business_types = 12; */
  mainBranch: MainBranch | undefined;
}

export interface CreateDepartmentRequest {
  organizationId: string;
  companyId: string;
  branchId?: string | undefined;
  name: string;
  description?: string | undefined;
  departmentTypeId?: string | undefined;
  creatorId: string;
}

export interface UpdateDepartmentRequest {
  organizationId: string;
  departmentId: string;
  companyId: string;
  branchId?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  departmentTypeId?: string | undefined;
  isActive?: boolean | undefined;
}

export interface CreateDepartmentTypeRequest {
  organizationId: string;
  companyId: string;
  branchId?: string | undefined;
  name: string;
  description?: string | undefined;
  type: DepartmentTypeEnum;
  creatorId: string;
}

export interface UpdateDepartmentTypeRequest {
  organizationId: string;
  departmentTypeId: string;
  companyId: string;
  branchId?: string | undefined;
  name: string;
  description?: string | undefined;
  type: DepartmentTypeEnum;
}

export interface GetDepartmentTypesRequest {
  organizationId: string;
  companyId: string;
  branchId?: string | undefined;
}

export interface GetDepartmentTypeRequest {
  organizationId: string;
  departmentTypeId: string;
  companyId: string;
}

export interface DeleteDepartmentTypeRequest {
  organizationId: string;
  companyId: string;
  departmentTypeId: string;
}

export interface GetDepartmentsRequest {
  organizationId: string;
  companyId: string;
  branchId?: string | undefined;
  isActive?: boolean | undefined;
}

export interface GetDepartmentRequest {
  organizationId: string;
  departmentId: string;
  companyId: string;
}

export interface DepartmentResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  department?: DepartmentWithType | undefined;
}

export interface GetDepartmentsResponse {
  success: boolean;
  error?: string | undefined;
  departments: DepartmentWithType[];
}

export interface MainBranch {
  name?: string | undefined;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  address: AddressRequest | undefined;
}

export interface AddressRequest {
  addressId?: string | undefined;
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  district?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  landmark?: string | undefined;
  directionUrl?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

export interface CreateOrganizationRequest {
  creatorId: string;
  organizationName: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
}

export interface CreateDepartmentRoleRequest {
  organizationId: string;
  companyId: string;
  branchId: string;
  departmentId: string;
  name: string;
  description?: string | undefined;
  levelNumber: number;
  reportsTo?: string | undefined;
  permissions: Permission[];
  staffIds: string[];
  creatorId: string;
}

export interface UpdateDepartmentRoleRequest {
  organizationId: string;
  roleId: string;
  companyId: string;
  name?: string | undefined;
  description?: string | undefined;
  levelNumber?: number | undefined;
  reportsTo?: string | undefined;
  permissions: Permission[];
  staffIds: string[];
  isActive?: boolean | undefined;
}

export interface GetDepartmentRolesRequest {
  organizationId: string;
  departmentId: string;
  companyId: string;
  branchId?: string | undefined;
}

export interface GetDepartmentRoleRequest {
  organizationId: string;
  roleId: string;
  companyId: string;
}

export interface AssignStaffDepartmentRoleRequest {
  organizationId: string;
  roleId: string;
  staffIds: string[];
  companyId: string;
}

/**
 * / Fetch all entity permissions for a specific role (department role, company role, etc.)
 * / The RPC name determines which entity_type is queried internally.
 */
export interface GetEntityPermissionsRequest {
  /** UUID of the role whose permissions to fetch */
  roleId: string;
  /** Scoping guard */
  companyId: string;
}

export interface EntityPermissionDetail {
  entityPermissionId: string;
  entityType: string;
  isGranted: boolean;
  level: number;
  grantedAt: string;
  permission: PermissionDetail | undefined;
}

export interface PermissionDetail {
  permissionId: number;
  permissionName: string;
  description: string;
  level: number;
  category: string;
}

export interface GetEntityPermissionsResponse {
  success: boolean;
  error?: string | undefined;
  permissions: EntityPermissionDetail[];
}

/** / A seeded permission group with all its member permissions expanded. */
export interface PermissionGroupData {
  groupId: number;
  groupName: string;
  description: string;
  level: number;
  category: string;
  permissions: PermissionDetail[];
  groupType: string;
}

export interface GetPermissionGroupsResponse {
  success: boolean;
  error?: string | undefined;
  groups: PermissionGroupData[];
}

export interface GetOrganizationRequest {
  organizationId: string;
}

export interface OrganizationResponse {
  success: boolean;
  error?: string | undefined;
  organization: Organization | undefined;
  company: Company | undefined;
  organizationId: string;
  message: string;
}

export interface DepartmentTypeResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  departmentType?: DepartmentType | undefined;
}

export interface GetDepartmentTypesResponse {
  success: boolean;
  error?: string | undefined;
  departmentTypes: DepartmentType[];
}

export interface DepartmentRoleResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  departmentRole?: DepartmentRoleData | undefined;
}

export interface GetDepartmentRolesResponse {
  success: boolean;
  error?: string | undefined;
  departmentRoles: DepartmentRoleData[];
}

export interface GetDepartmentRoleStaffResponse {
  success: boolean;
  error?: string | undefined;
  roleId: string;
  roleName: string;
  staffDepartmentRoles: StaffDepartmentRoleData[];
}

export interface StaffCompanyRoleData {
  staffId: string;
  companyRoleId: string;
  isActive: boolean;
  staff?: StaffData | undefined;
}

export interface GetCompanyRoleStaffResponse {
  success: boolean;
  error?: string | undefined;
  roleId: string;
  roleName: string;
  staffCompanyRoles: StaffCompanyRoleData[];
}

export interface GetCompanyRoleBusinessUsersResponse {
  success: boolean;
  error?: string | undefined;
  roleId: string;
  roleName: string;
  businessUserRoles: BusinessUserRole[];
}

/** 🏗️ DATA MODELS */
export interface Organization {
  organizationId: string;
  name: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
  isActive: boolean;
  isMultiCompany: boolean;
  creatorId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface Company {
  companyId: string;
  organizationId: string;
  referenceId: string;
  email: string;
  name: string;
  registrationDate: string;
  isActive: boolean;
  registrationNumber: string;
  companyLogo: string;
  baseCurrency: string;
  countryCode: string;
  phoneNumber: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  companyMetaData: CompanyMetaData | undefined;
  mainBranch: Branch | undefined;
  branches: Branch[];
}

export interface CompanyMetaData {
  companyId: string;
  staffCount: string;
  branchCount: string;
  isMultiBranch: boolean;
}

export interface Branch {
  branchId: string;
  companyId: string;
  name: string;
  email: string;
  phoneNumber: string;
  address: AddressRequest | undefined;
  isMainBranch: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  creatorId?: string | undefined;
}

export interface Department {
  departmentId: string;
  companyId: string;
  branchId?: string | undefined;
  name: string;
  description?: string | undefined;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

/** Analytics Messages */
export interface TrendData {
  name: string;
  value: number;
}

export interface OrganizationAnalyticsRequest {
  timeline: string;
  startDate?: string | undefined;
  endDate?: string | undefined;
}

export interface OrganizationMetric {
  count: number;
  percentage: number;
  trend: string;
}

export interface OrganizationMetricWithTrend {
  count: number;
  percentage: number;
  trend: string;
  trendData: TrendData[];
}

export interface TransactionMetric {
  value: number;
  percentage: number;
  trend: string;
}

export interface OrganizationAnalyticsResponse {
  totalOrganizations: OrganizationMetricWithTrend | undefined;
  activeOrganizations: OrganizationMetric | undefined;
  pendingOrganizations: OrganizationMetric | undefined;
  inactiveOrganizations: OrganizationMetric | undefined;
  highRevenueOrganizations: OrganizationMetric | undefined;
  largeOrganizations: OrganizationMetric | undefined;
  averageTransactions: TransactionMetric | undefined;
}

export interface TotalOrganizationsResponse {
  count: number;
  percentage: number;
  trend: string;
  trendData: TrendData[];
}

export interface TopPerformingOrganizationsRequest {
  limit?: number | undefined;
}

export interface OrganizationWithCounts {
  organizationId: string;
  name: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
  isActive: boolean;
  isMultiCompany: boolean;
  creatorId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  staffCount: number;
  businessUserCount: number;
  accessControlCount: number;
  companiesCount: number;
}

export interface TopPerformingOrganizationsResponse {
  topOrganizations: OrganizationWithCounts[];
}

/** Tables Messages */
export interface GetOrganizationsRequest {
  search?: string | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: string | undefined;
}

export interface OrganizationAddress {
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  postalCode?: string | undefined;
}

export interface OrganizationMeta {
  organizationRoles: number;
  isMultiCompany: boolean;
  companiesCount: number;
  totalBusinessUsers: number;
  activeBusinessUsers: number;
  inactiveBusinessUsers: number;
}

export interface OrganizationDetail {
  organizationId: string;
  name: string;
  email: string;
  phoneNumber?: string | undefined;
  status: string;
  isActive: boolean;
  emailVerified: boolean;
  phoneVerified: boolean;
  registrationDate?: string | undefined;
  createdAt: string;
  updatedAt: string;
  address?: OrganizationAddress | undefined;
  meta: OrganizationMeta | undefined;
  revenue: number;
  transactions: number;
}

export interface PaginationMeta {
  total: number;
  currentPage: number;
  pageSize: number;
  totalPages: number;
  nextPage?: number | undefined;
  prevPage?: number | undefined;
}

export interface GetOrganizationsResponse {
  organizations: OrganizationDetail[];
  meta: PaginationMeta | undefined;
}

export interface DepartmentType {
  departmentTypeId: string;
  companyId: string;
  branchId?: string | undefined;
  name: string;
  description?: string | undefined;
  type: DepartmentTypeEnum;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface DepartmentWithType {
  departmentId: string;
  companyId: string;
  branchId?: string | undefined;
  name: string;
  description?: string | undefined;
  isActive: boolean;
  departmentTypeId?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  departmentType?: DepartmentType | undefined;
  departmentRoles: DepartmentRoleData[];
  branch?: Branch | undefined;
}

/** Slim user info embedded in staff department role assignments */
export interface StaffUserInfo {
  userId: string;
  email: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  avatarUrl?: string | undefined;
  phoneNumber?: string | undefined;
  username?: string | undefined;
}

/**
 * Full staff record mirroring profile-service Staff type
 * Self-contained so organization.proto does not need to import profile.proto
 */
export interface StaffData {
  staffId: string;
  companyId: string;
  userId: string;
  branchId?: string | undefined;
  email: string;
  designation?: string | undefined;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  user?: StaffUserInfo | undefined;
  roleId?: string | undefined;
}

/**
 * Enriched staff record embedded in department role assignments
 * Populated by the department service via a getManyStaffDetails call to profile-service
 */
export interface StaffDepartmentRoleData {
  staffId: string;
  departmentRoleId: string;
  isActive: boolean;
  companyId?: string | undefined;
  email?: string | undefined;
  designation?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  user?: StaffUserInfo | undefined;
  staff?: StaffData | undefined;
}

export interface DepartmentRoleData {
  roleId: string;
  companyId: string;
  branchId: string;
  departmentId: string;
  name: string;
  slug: string;
  description?: string | undefined;
  isActive: boolean;
  levelNumber: number;
  reportsTo?: string | undefined;
  entityPermissions: EntityPermission[];
  staffDepartmentRoles: StaffDepartmentRoleData[];
  superior?: DepartmentRoleData | undefined;
  subordinates: DepartmentRoleData[];
  department?: DepartmentWithType | undefined;
  createdAt: string;
  updatedAt: string;
}

export const ORGANIZATION_PACKAGE_NAME = "organization";

/** 🏢 Organization Service - handles organization and branch management */

export interface OrganizationServiceClient {
  /** Organization Management */

  createOrganization(request: CreateOrganizationRequest): Observable<OrganizationResponse>;

  getOrganization(request: GetOrganizationRequest): Observable<OrganizationResponse>;

  /** Validate Company Reference */

  validateCompanyReference(request: ValidateCompanyReferenceRequest): Observable<ValidateCompanyReferenceResponse>;

  /** Verify IDs */

  verifyCompanyId(request: VerifyCompanyIdRequest): Observable<VerifyCompanyIdResponse>;

  verifyBranchId(request: VerifyBranchIdRequest): Observable<VerifyBranchIdResponse>;

  verifyDepartmentId(request: VerifyDepartmentIdRequest): Observable<VerifyDepartmentIdResponse>;

  verifyRoleId(request: VerifyRoleIdRequest): Observable<VerifyRoleIdResponse>;

  /** Create Company */

  createCompany(request: CreateCompanyRequest): Observable<UtilitiesResponse>;

  fetchOrganizationCompanies(request: OrganizationIdRequest): Observable<FetchCompaniesResponse>;

  fetchCompany(request: FetchCompanyRequest): Observable<FetchCompanyResponse>;

  handleMultiBranchCompanySetup(request: FetchCompanyRequest): Observable<UtilitiesResponse>;

  updateCompanyDetails(request: UpdateCompanyDetailsRequest): Observable<UtilitiesResponse>;

  /**
   * Create Branch
   * rpc CreateBranch(CreateBranchRequest) returns (UtilitiesResponse);
   */

  fetchBranch(request: BranchIdRequest): Observable<FetchBranchResponse>;

  /**
   * rpc UpdateBranch(UpdateBranchRequest) returns (UtilitiesResponse);
   * rpc DeleteBranch(BranchIdRequest) returns (UtilitiesResponse);
   */

  fetchCompanyBranches(request: FetchCompanyRequest): Observable<FetchBranchesResponse>;

  fetchOrgRoles(request: OrganizationIdRequest): Observable<FetchRolesResponse>;

  fetchOrgRole(request: OrganizationRoleIdRequest): Observable<FetchRoleResponse>;

  createBusinessUserRole(request: CreateBusinessUserRoleRequest): Observable<UtilitiesResponse>;

  updateBusinessUserRole(request: CreateBusinessUserRoleRequest): Observable<UtilitiesResponse>;

  createRole(request: CreateRoleRequest): Observable<UtilitiesResponse>;

  updateRole(request: UpdateRoleRequest): Observable<UtilitiesResponse>;

  getCompanyRoles(request: CompanyRolesRequest): Observable<FetchRolesResponse>;

  getCompanyRole(request: CompanyRoleRequest): Observable<FetchRoleResponse>;

  getCompanyRoleStaff(request: CompanyRoleRequest): Observable<GetCompanyRoleStaffResponse>;

  getCompanyRoleBusinessUsers(request: CompanyRoleRequest): Observable<GetCompanyRoleBusinessUsersResponse>;

  /** Analytics */

  getOrganizationAnalytics(request: OrganizationAnalyticsRequest): Observable<OrganizationAnalyticsResponse>;

  totalOrganizations(request: EmptyRequest): Observable<TotalOrganizationsResponse>;

  topPerformingOrganizations(
    request: TopPerformingOrganizationsRequest,
  ): Observable<TopPerformingOrganizationsResponse>;

  createDepartmentType(request: CreateDepartmentTypeRequest): Observable<DepartmentTypeResponse>;

  updateDepartmentType(request: UpdateDepartmentTypeRequest): Observable<DepartmentTypeResponse>;

  getDepartmentTypes(request: GetDepartmentTypesRequest): Observable<GetDepartmentTypesResponse>;

  getDepartmentType(request: GetDepartmentTypeRequest): Observable<DepartmentTypeResponse>;

  deleteDepartmentType(request: DeleteDepartmentTypeRequest): Observable<UtilitiesResponse>;

  /** Departments */

  createDepartment(request: CreateDepartmentRequest): Observable<DepartmentResponse>;

  updateDepartment(request: UpdateDepartmentRequest): Observable<DepartmentResponse>;

  getDepartments(request: GetDepartmentsRequest): Observable<GetDepartmentsResponse>;

  getDepartment(request: GetDepartmentRequest): Observable<DepartmentResponse>;

  /** Department Roles */

  createDepartmentRole(request: CreateDepartmentRoleRequest): Observable<DepartmentRoleResponse>;

  updateDepartmentRole(request: UpdateDepartmentRoleRequest): Observable<DepartmentRoleResponse>;

  getDepartmentRoles(request: GetDepartmentRolesRequest): Observable<GetDepartmentRolesResponse>;

  getDepartmentRole(request: GetDepartmentRoleRequest): Observable<DepartmentRoleResponse>;

  getDepartmentRoleStaff(request: GetDepartmentRoleRequest): Observable<GetDepartmentRoleStaffResponse>;

  assignStaffDepartmentRole(request: AssignStaffDepartmentRoleRequest): Observable<UtilitiesResponse>;

  /** Entity Permissions */

  getDepartmentRolePermissions(request: GetEntityPermissionsRequest): Observable<GetEntityPermissionsResponse>;

  getStaffCompanyRolePermissions(request: GetEntityPermissionsRequest): Observable<GetEntityPermissionsResponse>;

  getBusinessUserRolePermissions(request: GetEntityPermissionsRequest): Observable<GetEntityPermissionsResponse>;

  /** Permission Group Catalogs */

  getDepartmentPermissionGroups(request: EmptyRequest): Observable<GetPermissionGroupsResponse>;

  getStaffPermissionGroups(request: EmptyRequest): Observable<GetPermissionGroupsResponse>;

  getBusinessUserPermissionGroups(request: EmptyRequest): Observable<GetPermissionGroupsResponse>;

  /** Tables */

  getOrganizations(request: GetOrganizationsRequest): Observable<GetOrganizationsResponse>;
}

/** 🏢 Organization Service - handles organization and branch management */

export interface OrganizationServiceController {
  /** Organization Management */

  createOrganization(
    request: CreateOrganizationRequest,
  ): Promise<OrganizationResponse> | Observable<OrganizationResponse> | OrganizationResponse;

  getOrganization(
    request: GetOrganizationRequest,
  ): Promise<OrganizationResponse> | Observable<OrganizationResponse> | OrganizationResponse;

  /** Validate Company Reference */

  validateCompanyReference(
    request: ValidateCompanyReferenceRequest,
  ):
    | Promise<ValidateCompanyReferenceResponse>
    | Observable<ValidateCompanyReferenceResponse>
    | ValidateCompanyReferenceResponse;

  /** Verify IDs */

  verifyCompanyId(
    request: VerifyCompanyIdRequest,
  ): Promise<VerifyCompanyIdResponse> | Observable<VerifyCompanyIdResponse> | VerifyCompanyIdResponse;

  verifyBranchId(
    request: VerifyBranchIdRequest,
  ): Promise<VerifyBranchIdResponse> | Observable<VerifyBranchIdResponse> | VerifyBranchIdResponse;

  verifyDepartmentId(
    request: VerifyDepartmentIdRequest,
  ): Promise<VerifyDepartmentIdResponse> | Observable<VerifyDepartmentIdResponse> | VerifyDepartmentIdResponse;

  verifyRoleId(
    request: VerifyRoleIdRequest,
  ): Promise<VerifyRoleIdResponse> | Observable<VerifyRoleIdResponse> | VerifyRoleIdResponse;

  /** Create Company */

  createCompany(
    request: CreateCompanyRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  fetchOrganizationCompanies(
    request: OrganizationIdRequest,
  ): Promise<FetchCompaniesResponse> | Observable<FetchCompaniesResponse> | FetchCompaniesResponse;

  fetchCompany(
    request: FetchCompanyRequest,
  ): Promise<FetchCompanyResponse> | Observable<FetchCompanyResponse> | FetchCompanyResponse;

  handleMultiBranchCompanySetup(
    request: FetchCompanyRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  updateCompanyDetails(
    request: UpdateCompanyDetailsRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  /**
   * Create Branch
   * rpc CreateBranch(CreateBranchRequest) returns (UtilitiesResponse);
   */

  fetchBranch(
    request: BranchIdRequest,
  ): Promise<FetchBranchResponse> | Observable<FetchBranchResponse> | FetchBranchResponse;

  /**
   * rpc UpdateBranch(UpdateBranchRequest) returns (UtilitiesResponse);
   * rpc DeleteBranch(BranchIdRequest) returns (UtilitiesResponse);
   */

  fetchCompanyBranches(
    request: FetchCompanyRequest,
  ): Promise<FetchBranchesResponse> | Observable<FetchBranchesResponse> | FetchBranchesResponse;

  fetchOrgRoles(
    request: OrganizationIdRequest,
  ): Promise<FetchRolesResponse> | Observable<FetchRolesResponse> | FetchRolesResponse;

  fetchOrgRole(
    request: OrganizationRoleIdRequest,
  ): Promise<FetchRoleResponse> | Observable<FetchRoleResponse> | FetchRoleResponse;

  createBusinessUserRole(
    request: CreateBusinessUserRoleRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  updateBusinessUserRole(
    request: CreateBusinessUserRoleRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  createRole(
    request: CreateRoleRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  updateRole(
    request: UpdateRoleRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  getCompanyRoles(
    request: CompanyRolesRequest,
  ): Promise<FetchRolesResponse> | Observable<FetchRolesResponse> | FetchRolesResponse;

  getCompanyRole(
    request: CompanyRoleRequest,
  ): Promise<FetchRoleResponse> | Observable<FetchRoleResponse> | FetchRoleResponse;

  getCompanyRoleStaff(
    request: CompanyRoleRequest,
  ): Promise<GetCompanyRoleStaffResponse> | Observable<GetCompanyRoleStaffResponse> | GetCompanyRoleStaffResponse;

  getCompanyRoleBusinessUsers(
    request: CompanyRoleRequest,
  ):
    | Promise<GetCompanyRoleBusinessUsersResponse>
    | Observable<GetCompanyRoleBusinessUsersResponse>
    | GetCompanyRoleBusinessUsersResponse;

  /** Analytics */

  getOrganizationAnalytics(
    request: OrganizationAnalyticsRequest,
  ): Promise<OrganizationAnalyticsResponse> | Observable<OrganizationAnalyticsResponse> | OrganizationAnalyticsResponse;

  totalOrganizations(
    request: EmptyRequest,
  ): Promise<TotalOrganizationsResponse> | Observable<TotalOrganizationsResponse> | TotalOrganizationsResponse;

  topPerformingOrganizations(
    request: TopPerformingOrganizationsRequest,
  ):
    | Promise<TopPerformingOrganizationsResponse>
    | Observable<TopPerformingOrganizationsResponse>
    | TopPerformingOrganizationsResponse;

  createDepartmentType(
    request: CreateDepartmentTypeRequest,
  ): Promise<DepartmentTypeResponse> | Observable<DepartmentTypeResponse> | DepartmentTypeResponse;

  updateDepartmentType(
    request: UpdateDepartmentTypeRequest,
  ): Promise<DepartmentTypeResponse> | Observable<DepartmentTypeResponse> | DepartmentTypeResponse;

  getDepartmentTypes(
    request: GetDepartmentTypesRequest,
  ): Promise<GetDepartmentTypesResponse> | Observable<GetDepartmentTypesResponse> | GetDepartmentTypesResponse;

  getDepartmentType(
    request: GetDepartmentTypeRequest,
  ): Promise<DepartmentTypeResponse> | Observable<DepartmentTypeResponse> | DepartmentTypeResponse;

  deleteDepartmentType(
    request: DeleteDepartmentTypeRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  /** Departments */

  createDepartment(
    request: CreateDepartmentRequest,
  ): Promise<DepartmentResponse> | Observable<DepartmentResponse> | DepartmentResponse;

  updateDepartment(
    request: UpdateDepartmentRequest,
  ): Promise<DepartmentResponse> | Observable<DepartmentResponse> | DepartmentResponse;

  getDepartments(
    request: GetDepartmentsRequest,
  ): Promise<GetDepartmentsResponse> | Observable<GetDepartmentsResponse> | GetDepartmentsResponse;

  getDepartment(
    request: GetDepartmentRequest,
  ): Promise<DepartmentResponse> | Observable<DepartmentResponse> | DepartmentResponse;

  /** Department Roles */

  createDepartmentRole(
    request: CreateDepartmentRoleRequest,
  ): Promise<DepartmentRoleResponse> | Observable<DepartmentRoleResponse> | DepartmentRoleResponse;

  updateDepartmentRole(
    request: UpdateDepartmentRoleRequest,
  ): Promise<DepartmentRoleResponse> | Observable<DepartmentRoleResponse> | DepartmentRoleResponse;

  getDepartmentRoles(
    request: GetDepartmentRolesRequest,
  ): Promise<GetDepartmentRolesResponse> | Observable<GetDepartmentRolesResponse> | GetDepartmentRolesResponse;

  getDepartmentRole(
    request: GetDepartmentRoleRequest,
  ): Promise<DepartmentRoleResponse> | Observable<DepartmentRoleResponse> | DepartmentRoleResponse;

  getDepartmentRoleStaff(
    request: GetDepartmentRoleRequest,
  ):
    | Promise<GetDepartmentRoleStaffResponse>
    | Observable<GetDepartmentRoleStaffResponse>
    | GetDepartmentRoleStaffResponse;

  assignStaffDepartmentRole(
    request: AssignStaffDepartmentRoleRequest,
  ): Promise<UtilitiesResponse> | Observable<UtilitiesResponse> | UtilitiesResponse;

  /** Entity Permissions */

  getDepartmentRolePermissions(
    request: GetEntityPermissionsRequest,
  ): Promise<GetEntityPermissionsResponse> | Observable<GetEntityPermissionsResponse> | GetEntityPermissionsResponse;

  getStaffCompanyRolePermissions(
    request: GetEntityPermissionsRequest,
  ): Promise<GetEntityPermissionsResponse> | Observable<GetEntityPermissionsResponse> | GetEntityPermissionsResponse;

  getBusinessUserRolePermissions(
    request: GetEntityPermissionsRequest,
  ): Promise<GetEntityPermissionsResponse> | Observable<GetEntityPermissionsResponse> | GetEntityPermissionsResponse;

  /** Permission Group Catalogs */

  getDepartmentPermissionGroups(
    request: EmptyRequest,
  ): Promise<GetPermissionGroupsResponse> | Observable<GetPermissionGroupsResponse> | GetPermissionGroupsResponse;

  getStaffPermissionGroups(
    request: EmptyRequest,
  ): Promise<GetPermissionGroupsResponse> | Observable<GetPermissionGroupsResponse> | GetPermissionGroupsResponse;

  getBusinessUserPermissionGroups(
    request: EmptyRequest,
  ): Promise<GetPermissionGroupsResponse> | Observable<GetPermissionGroupsResponse> | GetPermissionGroupsResponse;

  /** Tables */

  getOrganizations(
    request: GetOrganizationsRequest,
  ): Promise<GetOrganizationsResponse> | Observable<GetOrganizationsResponse> | GetOrganizationsResponse;
}

export function OrganizationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createOrganization",
      "getOrganization",
      "validateCompanyReference",
      "verifyCompanyId",
      "verifyBranchId",
      "verifyDepartmentId",
      "verifyRoleId",
      "createCompany",
      "fetchOrganizationCompanies",
      "fetchCompany",
      "handleMultiBranchCompanySetup",
      "updateCompanyDetails",
      "fetchBranch",
      "fetchCompanyBranches",
      "fetchOrgRoles",
      "fetchOrgRole",
      "createBusinessUserRole",
      "updateBusinessUserRole",
      "createRole",
      "updateRole",
      "getCompanyRoles",
      "getCompanyRole",
      "getCompanyRoleStaff",
      "getCompanyRoleBusinessUsers",
      "getOrganizationAnalytics",
      "totalOrganizations",
      "topPerformingOrganizations",
      "createDepartmentType",
      "updateDepartmentType",
      "getDepartmentTypes",
      "getDepartmentType",
      "deleteDepartmentType",
      "createDepartment",
      "updateDepartment",
      "getDepartments",
      "getDepartment",
      "createDepartmentRole",
      "updateDepartmentRole",
      "getDepartmentRoles",
      "getDepartmentRole",
      "getDepartmentRoleStaff",
      "assignStaffDepartmentRole",
      "getDepartmentRolePermissions",
      "getStaffCompanyRolePermissions",
      "getBusinessUserRolePermissions",
      "getDepartmentPermissionGroups",
      "getStaffPermissionGroups",
      "getBusinessUserPermissionGroups",
      "getOrganizations",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrganizationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrganizationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORGANIZATION_SERVICE_NAME = "OrganizationService";
