// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v5.27.3
// source: organization.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "organization";

export interface ValidateCompanyReferenceRequest {
  company_ref: string;
}

export interface ValidateCompanyReferenceResponse {
  success: boolean;
  error?: string | undefined;
  company_id: string;
}

export interface CreateOrganizationRequest {
  creator_id: string;
  organization_name: string;
  phone_number: string;
  email: string;
  registration_number: string;
  registration_date: string;
}

export interface GetOrganizationRequest {
  organization_id: string;
}

export interface OrganizationResponse {
  success: boolean;
  error?: string | undefined;
  organization?: Organization | undefined;
}

export interface Organization {
  organization_id: string;
  name: string;
  phone_number: string;
  email: string;
  registration_number: string;
  registration_date: string;
  creator_id: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string | undefined;
}

export const ORGANIZATION_PACKAGE_NAME = "organization";

function createBaseValidateCompanyReferenceRequest(): ValidateCompanyReferenceRequest {
  return { company_ref: "" };
}

export const ValidateCompanyReferenceRequest: MessageFns<ValidateCompanyReferenceRequest> = {
  encode(message: ValidateCompanyReferenceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.company_ref !== "") {
      writer.uint32(10).string(message.company_ref);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateCompanyReferenceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateCompanyReferenceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.company_ref = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseValidateCompanyReferenceResponse(): ValidateCompanyReferenceResponse {
  return { success: false, company_id: "" };
}

export const ValidateCompanyReferenceResponse: MessageFns<ValidateCompanyReferenceResponse> = {
  encode(message: ValidateCompanyReferenceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.company_id !== "") {
      writer.uint32(26).string(message.company_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateCompanyReferenceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateCompanyReferenceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.company_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateOrganizationRequest(): CreateOrganizationRequest {
  return {
    creator_id: "",
    organization_name: "",
    phone_number: "",
    email: "",
    registration_number: "",
    registration_date: "",
  };
}

export const CreateOrganizationRequest: MessageFns<CreateOrganizationRequest> = {
  encode(message: CreateOrganizationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator_id !== "") {
      writer.uint32(10).string(message.creator_id);
    }
    if (message.organization_name !== "") {
      writer.uint32(18).string(message.organization_name);
    }
    if (message.phone_number !== "") {
      writer.uint32(26).string(message.phone_number);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.registration_number !== "") {
      writer.uint32(42).string(message.registration_number);
    }
    if (message.registration_date !== "") {
      writer.uint32(50).string(message.registration_date);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrganizationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrganizationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organization_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phone_number = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.registration_number = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.registration_date = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetOrganizationRequest(): GetOrganizationRequest {
  return { organization_id: "" };
}

export const GetOrganizationRequest: MessageFns<GetOrganizationRequest> = {
  encode(message: GetOrganizationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organization_id !== "") {
      writer.uint32(10).string(message.organization_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOrganizationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOrganizationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organization_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOrganizationResponse(): OrganizationResponse {
  return { success: false };
}

export const OrganizationResponse: MessageFns<OrganizationResponse> = {
  encode(message: OrganizationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.organization !== undefined) {
      Organization.encode(message.organization, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrganizationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrganizationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.organization = Organization.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseOrganization(): Organization {
  return {
    organization_id: "",
    name: "",
    phone_number: "",
    email: "",
    registration_number: "",
    registration_date: "",
    creator_id: "",
    created_at: "",
    updated_at: "",
  };
}

export const Organization: MessageFns<Organization> = {
  encode(message: Organization, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.organization_id !== "") {
      writer.uint32(10).string(message.organization_id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.phone_number !== "") {
      writer.uint32(26).string(message.phone_number);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.registration_number !== "") {
      writer.uint32(42).string(message.registration_number);
    }
    if (message.registration_date !== "") {
      writer.uint32(50).string(message.registration_date);
    }
    if (message.creator_id !== "") {
      writer.uint32(58).string(message.creator_id);
    }
    if (message.created_at !== "") {
      writer.uint32(66).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(74).string(message.updated_at);
    }
    if (message.deleted_at !== undefined) {
      writer.uint32(82).string(message.deleted_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Organization {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrganization();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.organization_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phone_number = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.registration_number = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.registration_date = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.creator_id = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.deleted_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** 🏢 Organization Service - handles organization and branch management */

export interface OrganizationServiceClient {
  /** Organization Management */

  createOrganization(request: CreateOrganizationRequest): Observable<OrganizationResponse>;

  getOrganization(request: GetOrganizationRequest): Observable<OrganizationResponse>;

  validateCompanyReference(request: ValidateCompanyReferenceRequest): Observable<ValidateCompanyReferenceResponse>;
}

/** 🏢 Organization Service - handles organization and branch management */

export interface OrganizationServiceController {
  /** Organization Management */

  createOrganization(
    request: CreateOrganizationRequest,
  ): Promise<OrganizationResponse> | Observable<OrganizationResponse> | OrganizationResponse;

  getOrganization(
    request: GetOrganizationRequest,
  ): Promise<OrganizationResponse> | Observable<OrganizationResponse> | OrganizationResponse;

  validateCompanyReference(
    request: ValidateCompanyReferenceRequest,
  ):
    | Promise<ValidateCompanyReferenceResponse>
    | Observable<ValidateCompanyReferenceResponse>
    | ValidateCompanyReferenceResponse;
}

export function OrganizationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrganization", "getOrganization", "validateCompanyReference"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrganizationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrganizationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORGANIZATION_SERVICE_NAME = "OrganizationService";

/** 🏢 Organization Service - handles organization and branch management */
export type OrganizationServiceService = typeof OrganizationServiceService;
export const OrganizationServiceService = {
  /** Organization Management */
  createOrganization: {
    path: "/organization.OrganizationService/CreateOrganization",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateOrganizationRequest): Buffer =>
      Buffer.from(CreateOrganizationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateOrganizationRequest => CreateOrganizationRequest.decode(value),
    responseSerialize: (value: OrganizationResponse): Buffer =>
      Buffer.from(OrganizationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrganizationResponse => OrganizationResponse.decode(value),
  },
  getOrganization: {
    path: "/organization.OrganizationService/GetOrganization",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetOrganizationRequest): Buffer =>
      Buffer.from(GetOrganizationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetOrganizationRequest => GetOrganizationRequest.decode(value),
    responseSerialize: (value: OrganizationResponse): Buffer =>
      Buffer.from(OrganizationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): OrganizationResponse => OrganizationResponse.decode(value),
  },
  validateCompanyReference: {
    path: "/organization.OrganizationService/validateCompanyReference",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateCompanyReferenceRequest): Buffer =>
      Buffer.from(ValidateCompanyReferenceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateCompanyReferenceRequest =>
      ValidateCompanyReferenceRequest.decode(value),
    responseSerialize: (value: ValidateCompanyReferenceResponse): Buffer =>
      Buffer.from(ValidateCompanyReferenceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ValidateCompanyReferenceResponse =>
      ValidateCompanyReferenceResponse.decode(value),
  },
} as const;

export interface OrganizationServiceServer extends UntypedServiceImplementation {
  /** Organization Management */
  createOrganization: handleUnaryCall<CreateOrganizationRequest, OrganizationResponse>;
  getOrganization: handleUnaryCall<GetOrganizationRequest, OrganizationResponse>;
  validateCompanyReference: handleUnaryCall<ValidateCompanyReferenceRequest, ValidateCompanyReferenceResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
