// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.3
//   protoc               v5.27.3
// source: profile.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "profile";

export interface GetUserRequest {
  user_id: string;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface UpdateUserStatusRequest {
  user_id: string;
  last_seen: string;
}

export interface GetUserContactsRequest {
  user_id: string;
  name?: string | undefined;
}

export interface UpdateUserRequest {
  user_id: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  email?: string | undefined;
  phone_number?: string | undefined;
  avatar_url?: string | undefined;
  address?: Address | undefined;
}

export interface UserResponse {
  success: boolean;
  error?: string | undefined;
  user?: User | undefined;
}

export interface GetUserByEmailResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  user?: User | undefined;
}

export interface UpdateUserStatusResponse {
  success: boolean;
  error?: string | undefined;
  user?: BasicUser | undefined;
}

export interface GetUserContactsResponse {
  success: boolean;
  error?: string | undefined;
  contacts: Contact[];
  total_count: number;
}

export interface UpdateUserResponse {
  success: boolean;
  error?: string | undefined;
  user?: BasicUser | undefined;
}

export interface User {
  user_id: string;
  email: string;
  username?: string | undefined;
  first_name?: string | undefined;
  last_name?: string | undefined;
  phone_number?: string | undefined;
  avatar_url?: string | undefined;
  last_seen?: string | undefined;
  created_at: string;
  updated_at: string;
  email_verified: boolean;
  address?: Address | undefined;
  user_role?: UserRole | undefined;
  business_user?: BusinessUser | undefined;
}

export interface BasicUser {
  user_id: string;
  email: string;
  username?: string | undefined;
  first_name?: string | undefined;
  last_name?: string | undefined;
  phone_number?: string | undefined;
  last_seen?: string | undefined;
  created_at: string;
  updated_at: string;
  email_verified: boolean;
}

export interface Contact {
  user_id: string;
  email: string;
  username?: string | undefined;
  first_name?: string | undefined;
  last_name?: string | undefined;
  avatar_url?: string | undefined;
  last_seen?: string | undefined;
  email_verified: boolean;
}

export interface Address {
  address_id?: string | undefined;
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  district?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postal_code?: string | undefined;
  country?: string | undefined;
  landmark?: string | undefined;
  direction_url?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

export interface UserRole {
  user_role_id: string;
  role_name: string;
  is_active: boolean;
}

export interface BusinessUser {
  business_user_id: string;
  business_name: string;
  is_active: boolean;
}

export const PROFILE_PACKAGE_NAME = "profile";

function createBaseGetUserRequest(): GetUserRequest {
  return { user_id: "" };
}

export const GetUserRequest: MessageFns<GetUserRequest> = {
  encode(message: GetUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserByEmailRequest(): GetUserByEmailRequest {
  return { email: "" };
}

export const GetUserByEmailRequest: MessageFns<GetUserByEmailRequest> = {
  encode(message: GetUserByEmailRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserByEmailRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserByEmailRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateUserStatusRequest(): UpdateUserStatusRequest {
  return { user_id: "", last_seen: "" };
}

export const UpdateUserStatusRequest: MessageFns<UpdateUserStatusRequest> = {
  encode(message: UpdateUserStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.last_seen !== "") {
      writer.uint32(18).string(message.last_seen);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.last_seen = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserContactsRequest(): GetUserContactsRequest {
  return { user_id: "" };
}

export const GetUserContactsRequest: MessageFns<GetUserContactsRequest> = {
  encode(message: GetUserContactsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserContactsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserContactsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateUserRequest(): UpdateUserRequest {
  return { user_id: "" };
}

export const UpdateUserRequest: MessageFns<UpdateUserRequest> = {
  encode(message: UpdateUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.first_name !== undefined) {
      writer.uint32(18).string(message.first_name);
    }
    if (message.last_name !== undefined) {
      writer.uint32(26).string(message.last_name);
    }
    if (message.email !== undefined) {
      writer.uint32(34).string(message.email);
    }
    if (message.phone_number !== undefined) {
      writer.uint32(42).string(message.phone_number);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(50).string(message.avatar_url);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phone_number = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserResponse(): UserResponse {
  return { success: false };
}

export const UserResponse: MessageFns<UserResponse> = {
  encode(message: UserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserByEmailResponse(): GetUserByEmailResponse {
  return { success: false };
}

export const GetUserByEmailResponse: MessageFns<GetUserByEmailResponse> = {
  encode(message: GetUserByEmailResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.message !== undefined) {
      writer.uint32(26).string(message.message);
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserByEmailResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserByEmailResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateUserStatusResponse(): UpdateUserStatusResponse {
  return { success: false };
}

export const UpdateUserStatusResponse: MessageFns<UpdateUserStatusResponse> = {
  encode(message: UpdateUserStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.user !== undefined) {
      BasicUser.encode(message.user, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = BasicUser.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserContactsResponse(): GetUserContactsResponse {
  return { success: false, contacts: [], total_count: 0 };
}

export const GetUserContactsResponse: MessageFns<GetUserContactsResponse> = {
  encode(message: GetUserContactsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    for (const v of message.contacts) {
      Contact.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.total_count !== 0) {
      writer.uint32(32).int32(message.total_count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserContactsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserContactsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contacts.push(Contact.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.total_count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateUserResponse(): UpdateUserResponse {
  return { success: false };
}

export const UpdateUserResponse: MessageFns<UpdateUserResponse> = {
  encode(message: UpdateUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== undefined) {
      writer.uint32(18).string(message.error);
    }
    if (message.user !== undefined) {
      BasicUser.encode(message.user, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = BasicUser.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUser(): User {
  return { user_id: "", email: "", created_at: "", updated_at: "", email_verified: false };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.username !== undefined) {
      writer.uint32(26).string(message.username);
    }
    if (message.first_name !== undefined) {
      writer.uint32(34).string(message.first_name);
    }
    if (message.last_name !== undefined) {
      writer.uint32(42).string(message.last_name);
    }
    if (message.phone_number !== undefined) {
      writer.uint32(50).string(message.phone_number);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(58).string(message.avatar_url);
    }
    if (message.last_seen !== undefined) {
      writer.uint32(66).string(message.last_seen);
    }
    if (message.created_at !== "") {
      writer.uint32(74).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(82).string(message.updated_at);
    }
    if (message.email_verified !== false) {
      writer.uint32(88).bool(message.email_verified);
    }
    if (message.address !== undefined) {
      Address.encode(message.address, writer.uint32(98).fork()).join();
    }
    if (message.user_role !== undefined) {
      UserRole.encode(message.user_role, writer.uint32(106).fork()).join();
    }
    if (message.business_user !== undefined) {
      BusinessUser.encode(message.business_user, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.phone_number = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.last_seen = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.address = Address.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.user_role = UserRole.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.business_user = BusinessUser.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseBasicUser(): BasicUser {
  return { user_id: "", email: "", created_at: "", updated_at: "", email_verified: false };
}

export const BasicUser: MessageFns<BasicUser> = {
  encode(message: BasicUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.username !== undefined) {
      writer.uint32(26).string(message.username);
    }
    if (message.first_name !== undefined) {
      writer.uint32(34).string(message.first_name);
    }
    if (message.last_name !== undefined) {
      writer.uint32(42).string(message.last_name);
    }
    if (message.phone_number !== undefined) {
      writer.uint32(50).string(message.phone_number);
    }
    if (message.last_seen !== undefined) {
      writer.uint32(58).string(message.last_seen);
    }
    if (message.created_at !== "") {
      writer.uint32(66).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(74).string(message.updated_at);
    }
    if (message.email_verified !== false) {
      writer.uint32(80).bool(message.email_verified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BasicUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBasicUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.phone_number = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.last_seen = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseContact(): Contact {
  return { user_id: "", email: "", email_verified: false };
}

export const Contact: MessageFns<Contact> = {
  encode(message: Contact, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.username !== undefined) {
      writer.uint32(26).string(message.username);
    }
    if (message.first_name !== undefined) {
      writer.uint32(34).string(message.first_name);
    }
    if (message.last_name !== undefined) {
      writer.uint32(42).string(message.last_name);
    }
    if (message.avatar_url !== undefined) {
      writer.uint32(50).string(message.avatar_url);
    }
    if (message.last_seen !== undefined) {
      writer.uint32(58).string(message.last_seen);
    }
    if (message.email_verified !== false) {
      writer.uint32(64).bool(message.email_verified);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Contact {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContact();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.avatar_url = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.last_seen = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddress(): Address {
  return {};
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address_id !== undefined) {
      writer.uint32(10).string(message.address_id);
    }
    if (message.street !== undefined) {
      writer.uint32(18).string(message.street);
    }
    if (message.building !== undefined) {
      writer.uint32(26).string(message.building);
    }
    if (message.apartment !== undefined) {
      writer.uint32(34).string(message.apartment);
    }
    if (message.district !== undefined) {
      writer.uint32(42).string(message.district);
    }
    if (message.city !== undefined) {
      writer.uint32(50).string(message.city);
    }
    if (message.state !== undefined) {
      writer.uint32(58).string(message.state);
    }
    if (message.postal_code !== undefined) {
      writer.uint32(66).string(message.postal_code);
    }
    if (message.country !== undefined) {
      writer.uint32(74).string(message.country);
    }
    if (message.landmark !== undefined) {
      writer.uint32(82).string(message.landmark);
    }
    if (message.direction_url !== undefined) {
      writer.uint32(90).string(message.direction_url);
    }
    if (message.latitude !== undefined) {
      writer.uint32(97).double(message.latitude);
    }
    if (message.longitude !== undefined) {
      writer.uint32(105).double(message.longitude);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.street = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.building = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.apartment = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.district = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.postal_code = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.landmark = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.direction_url = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 97) {
            break;
          }

          message.latitude = reader.double();
          continue;
        }
        case 13: {
          if (tag !== 105) {
            break;
          }

          message.longitude = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserRole(): UserRole {
  return { user_role_id: "", role_name: "", is_active: false };
}

export const UserRole: MessageFns<UserRole> = {
  encode(message: UserRole, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_role_id !== "") {
      writer.uint32(10).string(message.user_role_id);
    }
    if (message.role_name !== "") {
      writer.uint32(18).string(message.role_name);
    }
    if (message.is_active !== false) {
      writer.uint32(24).bool(message.is_active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRole {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRole();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_role_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.role_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_active = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseBusinessUser(): BusinessUser {
  return { business_user_id: "", business_name: "", is_active: false };
}

export const BusinessUser: MessageFns<BusinessUser> = {
  encode(message: BusinessUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.business_user_id !== "") {
      writer.uint32(10).string(message.business_user_id);
    }
    if (message.business_name !== "") {
      writer.uint32(18).string(message.business_name);
    }
    if (message.is_active !== false) {
      writer.uint32(24).bool(message.is_active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BusinessUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBusinessUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.business_user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.business_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.is_active = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** 👤 Profile Service - handles user profiles and user management */

export interface ProfileServiceClient {
  /** User Management */

  getUser(request: GetUserRequest): Observable<UserResponse>;

  getUserByEmail(request: GetUserByEmailRequest): Observable<GetUserByEmailResponse>;

  updateUserStatus(request: UpdateUserStatusRequest): Observable<UpdateUserStatusResponse>;

  getUserContacts(request: GetUserContactsRequest): Observable<GetUserContactsResponse>;

  updateUser(request: UpdateUserRequest): Observable<UpdateUserResponse>;
}

/** 👤 Profile Service - handles user profiles and user management */

export interface ProfileServiceController {
  /** User Management */

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserByEmail(
    request: GetUserByEmailRequest,
  ): Promise<GetUserByEmailResponse> | Observable<GetUserByEmailResponse> | GetUserByEmailResponse;

  updateUserStatus(
    request: UpdateUserStatusRequest,
  ): Promise<UpdateUserStatusResponse> | Observable<UpdateUserStatusResponse> | UpdateUserStatusResponse;

  getUserContacts(
    request: GetUserContactsRequest,
  ): Promise<GetUserContactsResponse> | Observable<GetUserContactsResponse> | GetUserContactsResponse;

  updateUser(
    request: UpdateUserRequest,
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;
}

export function ProfileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUser", "getUserByEmail", "updateUserStatus", "getUserContacts", "updateUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProfileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProfileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROFILE_SERVICE_NAME = "ProfileService";

/** 👤 Profile Service - handles user profiles and user management */
export type ProfileServiceService = typeof ProfileServiceService;
export const ProfileServiceService = {
  /** User Management */
  getUser: {
    path: "/profile.ProfileService/GetUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserRequest): Buffer => Buffer.from(GetUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserRequest => GetUserRequest.decode(value),
    responseSerialize: (value: UserResponse): Buffer => Buffer.from(UserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserResponse => UserResponse.decode(value),
  },
  getUserByEmail: {
    path: "/profile.ProfileService/GetUserByEmail",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserByEmailRequest): Buffer =>
      Buffer.from(GetUserByEmailRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserByEmailRequest => GetUserByEmailRequest.decode(value),
    responseSerialize: (value: GetUserByEmailResponse): Buffer =>
      Buffer.from(GetUserByEmailResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserByEmailResponse => GetUserByEmailResponse.decode(value),
  },
  updateUserStatus: {
    path: "/profile.ProfileService/UpdateUserStatus",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateUserStatusRequest): Buffer =>
      Buffer.from(UpdateUserStatusRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUserStatusRequest => UpdateUserStatusRequest.decode(value),
    responseSerialize: (value: UpdateUserStatusResponse): Buffer =>
      Buffer.from(UpdateUserStatusResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUserStatusResponse => UpdateUserStatusResponse.decode(value),
  },
  getUserContacts: {
    path: "/profile.ProfileService/GetUserContacts",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserContactsRequest): Buffer =>
      Buffer.from(GetUserContactsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserContactsRequest => GetUserContactsRequest.decode(value),
    responseSerialize: (value: GetUserContactsResponse): Buffer =>
      Buffer.from(GetUserContactsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserContactsResponse => GetUserContactsResponse.decode(value),
  },
  updateUser: {
    path: "/profile.ProfileService/UpdateUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateUserRequest): Buffer => Buffer.from(UpdateUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateUserRequest => UpdateUserRequest.decode(value),
    responseSerialize: (value: UpdateUserResponse): Buffer => Buffer.from(UpdateUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateUserResponse => UpdateUserResponse.decode(value),
  },
} as const;

export interface ProfileServiceServer extends UntypedServiceImplementation {
  /** User Management */
  getUser: handleUnaryCall<GetUserRequest, UserResponse>;
  getUserByEmail: handleUnaryCall<GetUserByEmailRequest, GetUserByEmailResponse>;
  updateUserStatus: handleUnaryCall<UpdateUserStatusRequest, UpdateUserStatusResponse>;
  getUserContacts: handleUnaryCall<GetUserContactsRequest, GetUserContactsResponse>;
  updateUser: handleUnaryCall<UpdateUserRequest, UpdateUserResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
