// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.33.2
// source: profile.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Struct } from "./google/protobuf/struct.pb";

export const protobufPackage = "profile";

export enum RequestFilter {
  ALL = 0,
  ACTIVE = 1,
  INACTIVE = 2,
  UNRECOGNIZED = -1,
}

export enum Timeline {
  _1m = 0,
  _3m = 1,
  _6m = 2,
  _1y = 3,
  all = 4,
  UNRECOGNIZED = -1,
}

export enum InvitationStatus {
  PENDING = 0,
  VIEWED = 1,
  ACCEPTED = 2,
  DECLINED = 3,
  EXPIRED = 4,
  UNRECOGNIZED = -1,
}

export enum SessionSource {
  WEB = 0,
  MOBILE = 1,
  TABLET = 2,
  OTHER = 3,
  UNRECOGNIZED = -1,
}

export enum rolesEnum {
  CLIENT = 0,
  BUSINESS_USER = 1,
  STAFF = 2,
  UNRECOGNIZED = -1,
}

export enum SendOtpType {
  REGISTRATION = 0,
  SIGNIN = 1,
  ADMIN_REGISTRATION = 2,
  ADMIN_SIGNIN = 3,
  FORGOT_PASSWORD = 4,
  UNRECOGNIZED = -1,
}

export interface LoginHistoryResponse {
  loginHistory: LoginHistory[];
}

export interface LoginHistory {
  sessionId: string;
  userId: string;
  deviceInfo: string;
  isActive: boolean;
  loginAt: string;
  source: SessionSource;
}

export interface PaginatedCompanyRequest {
  /** Company identification */
  companyId: string;
  organizationId: string;
  /** Pagination and sorting */
  search?: string | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  sortBy?: string | undefined;
  sortOrder?: string | undefined;
  filter?: RequestFilter | undefined;
}

export interface GetInvitationsByCompanyResponse {
  success: boolean;
  error?: string | undefined;
  invitations: StaffInvitation[];
  meta: TableMeta | undefined;
}

export interface CompanyIdRequest {
  companyId: string;
  organizationId: string;
}

export interface GetLoginHistoryRequest {
  userId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
}

export interface GetUserCountForOrganizationRequest {
  organizationId: string;
  isActive: boolean;
}

export interface GetUserCountForOrganizationResponse {
  count: number;
}

export interface YAxis {
  max: number;
  sections: number[];
  label: string;
}

export interface XAxis {
  sections: string[];
  label: string;
}

export interface DailyActiveUsersData {
  day: string;
  date: string;
  activeUsers: number;
  isToday: boolean;
}

export interface PeakDay {
  day: string;
  date: string;
  activeUsers: number;
  isToday: boolean;
}

export interface DailyActiveUsersSummary {
  totalUsers: number;
  avgDailyActive: number;
  peakDay: PeakDay | undefined;
}

export interface DailyActiveUsersAnalyticsResponse {
  yAxis: YAxis | undefined;
  xAxis: XAxis | undefined;
  data: DailyActiveUsersData[];
  summary: DailyActiveUsersSummary | undefined;
}

export interface TrendData {
  name: string;
  value: number;
}

export interface ActiveUsersCountResponse {
  count: number;
  percentage: number;
  trend: string;
  trendData: TrendData[];
}

export interface AdminUsersAnalyticsRequest {
  timeline?: Timeline | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  roleId?: string | undefined;
}

export interface Analytic {
  value: number;
  trend: string;
  percentage: string;
}

export interface AdminUsersAnalyticsResponse {
  totalUsers: Analytic | undefined;
  newUsers: Analytic | undefined;
  activeUsers: Analytic | undefined;
  businessUsers: Analytic | undefined;
  pendingUsers: Analytic | undefined;
  deactivatedUsers: Analytic | undefined;
  highValueUsers: Analytic | undefined;
  atRiskUsers: Analytic | undefined;
}

export interface GetUsersRequest {
  search: string;
  page: number;
  pageSize: number;
  sortBy: string;
  sortOrder: string;
}

export interface TableMeta {
  total: number;
  currentPage: number;
  pageSize: number;
  totalPages: number;
  nextPage: number;
  prevPage: number;
}

export interface GetUsersResponse {
  success: boolean;
  error?: string | undefined;
  users: User[];
  meta: TableMeta | undefined;
}

export interface StaffDetailsRequest {
  staffId: string;
  companyId: string;
}

export interface ManyStaffDetailsRequest {
  staffIds: string[];
  companyId: string;
}

export interface Staff {
  staffId: string;
  companyId: string;
  userId: string;
  branchId?: string | undefined;
  email: string;
  designation?: string | undefined;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  user?: User | undefined;
  roleId: string;
  role?: OrganizationRole | undefined;
}

export interface StaffDetailsResponse {
  success: boolean;
  error?: string | undefined;
  staff?: Staff | undefined;
}

export interface ManyStaffDetailsResponse {
  success: boolean;
  error?: string | undefined;
  staffs: Staff[];
  meta?: TableMeta | undefined;
}

export interface StaffInvitationItem {
  email: string;
  roleId: string;
  branchId?: string | undefined;
  departmentId?: string | undefined;
}

export interface SendStaffInvitationsRequest {
  organizationId: string;
  companyId: string;
  invitedBy: string;
  invitations: StaffInvitationItem[];
}

export interface InvitationResult {
  success: boolean;
  message: string;
}

export interface SendStaffInvitationsResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  results: InvitationResult[];
}

export interface GetInvitationByCodeRequest {
  invitationCode: string;
}

export interface OrganizationRole {
  roleId: string;
  organizationId: string;
  companyId: string;
  branchId: string;
  name: string;
  slug: string;
  description: string;
  isActive: boolean;
  isOrgLevel: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

export interface StaffInvitation {
  invitationId: string;
  companyId: string;
  branchId?: string | undefined;
  departmentId?: string | undefined;
  roleId?: string | undefined;
  role?: OrganizationRole | undefined;
  email: string;
  invitationCode: string;
  /** InvitationStatus status = 9; */
  invitedBy: string;
  expiresAt: string;
  responsedAt?: string | undefined;
  createdAt: string;
  status: string;
}

export interface GetInvitationByCodeResponse {
  success: boolean;
  error?: string | undefined;
  invitation?: StaffInvitation | undefined;
}

export interface MarkInvitationViewedRequest {
  invitationCode: string;
}

export interface AcceptInvitationRequest {
  invitationCode: string;
  userId: string;
}

export interface AcceptInvitationResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
  staff?: Staff | undefined;
}

export interface DeclineInvitationRequest {
  invitationCode: string;
}

export interface InvitationStatusResponse {
  success: boolean;
  error?: string | undefined;
  message: string;
}

export interface ValidateAccountRequest {
  token: string;
}

export interface ValidateAccountResponse {
  user: User | undefined;
  success: boolean;
  message: string;
}

export interface OrganizationRoleIdRequest {
  organizationRoleId: string;
}

export interface FetchOrganizationRolesResponse {
  roles: Role[];
}

export interface FetchOrganizationRolesCountResponse {
  count: number;
}

export interface CommonResponseArray {
  success: boolean;
  message: string;
  status: number;
  data: { [key: string]: any }[];
  roles: Role[];
}

export interface EmptyRequest {
}

export interface CreateOrUpdateBusinessUserRoleRequest {
  businessUserIds: string[];
  organizationRoleId: string;
}

export interface CreateOrUpdateBusinessUserRoleResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
}

export interface Role {
  roleId: string;
  roleName: string;
  isActive: boolean;
}

export interface BusinessUserRole {
  businessUserRoleId: string;
  businessUserId: string;
  organizationRoleId: string;
  isActive: boolean;
}

export interface GetRolesResponse {
  roles: Role[];
}

export interface VerifyOtpResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  accessToken?: string | undefined;
  user?: User | undefined;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface SendOtpRequest {
  token: string;
  type: SendOtpType;
}

export interface VerifyOtpRequest {
  token: string;
  otp: string;
  type: SendOtpType;
  deviceInfo: string;
  source: SessionSource;
}

export interface SendOtpResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
}

export interface RefreshTokenResponse {
  success: boolean;
  user: User | undefined;
  accessToken: string;
}

export interface AuthResponse {
  success: boolean;
  error?: string | undefined;
  user: User | undefined;
  accessToken: string;
}

export interface AuthInitialResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  authToken?: string | undefined;
}

export interface RegisterRequest {
  email: string;
  password: string;
  phoneNumber: string;
  companyRef: string;
  roleName: string;
}

export interface LogoutRequest {
  userId: string;
  source: SessionSource;
}

export interface RefreshTokenRequest {
  token: string;
}

export interface GetUserRequest {
  userId: string;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface UpdateUserStatusRequest {
  userId: string;
  lastSeen: string;
}

export interface GetUserContactsRequest {
  userId: string;
  name?: string | undefined;
}

export interface UpdateUserRequest {
  userId: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  avatarUrl?: string | undefined;
  address?: Address | undefined;
  countryCode?: string | undefined;
}

export interface BusinessUser {
  businessUserId: string;
  userId: string;
  email: string;
  phoneNumber: string;
  organizationId: string;
  accessType: string;
  accessLevel: number;
  isActive: boolean;
  notes?: string | undefined;
}

export interface BusinessUserResponse {
  success: boolean;
  error?: string | undefined;
  businessUser?: BusinessUser | undefined;
  organization?: Organization | undefined;
  company?: Company | undefined;
}

export interface UserResponse {
  success: boolean;
  error?: string | undefined;
  user?: User | undefined;
}

export interface GetUserByEmailResponse {
  success: boolean;
  error?: string | undefined;
  message?: string | undefined;
  user?: User | undefined;
}

export interface UpdateUserStatusResponse {
  success: boolean;
  error?: string | undefined;
  user?: User | undefined;
}

export interface GetUserContactsResponse {
  success: boolean;
  error?: string | undefined;
  contacts: Contact[];
  totalCount: number;
}

export interface UpdateUserResponse {
  success: boolean;
  error?: string | undefined;
  user?: User | undefined;
}

export interface User {
  userId: string;
  email: string;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  phoneNumber?: string | undefined;
  avatarUrl?: string | undefined;
  lastSeen?: string | undefined;
  createdAt: string;
  updatedAt: string;
  lastLogin: string;
  emailVerified: boolean;
  address?: Address | undefined;
  userRole?: UserRole | undefined;
  userRoles: UserRole[];
  businessUser?: BusinessUser | undefined;
}

export interface Contact {
  userId: string;
  email: string;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  avatarUrl?: string | undefined;
  lastSeen?: string | undefined;
  emailVerified: boolean;
}

export interface Organization {
  organizationId: string;
  name: string;
  phoneNumber: string;
  email: string;
  registrationNumber: string;
  registrationDate: string;
  isActive: boolean;
  isMultiCompany: boolean;
  creatorId: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface Address {
  addressId?: string | undefined;
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  district?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  landmark?: string | undefined;
  directionUrl?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

export interface UserRole {
  userId: string;
  roleName: string;
  isActive: boolean;
  role: Role | undefined;
}

export interface Company {
  companyId: string;
  organizationId: string;
  referenceId: string;
  email: string;
  name: string;
  registrationDate: string;
  isActive: boolean;
  registrationNumber: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  companyMetaData: CompanyMetaData | undefined;
  branches: Branch[];
}

export interface CompanyMetaData {
  companyId: string;
  staffCount: string;
  branchCount: string;
  isMultiBranch: boolean;
}

export interface Branch {
  branchId: string;
  companyId: string;
  name: string;
  email: string;
  phoneNumber: string;
  address: AddressRequest | undefined;
  isMainBranch: boolean;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  creatorId?: string | undefined;
}

export interface AddressRequest {
  addressId?: string | undefined;
  street?: string | undefined;
  building?: string | undefined;
  apartment?: string | undefined;
  district?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  landmark?: string | undefined;
  directionUrl?: string | undefined;
  latitude?: number | undefined;
  longitude?: number | undefined;
}

export const PROFILE_PACKAGE_NAME = "profile";

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;

/** 👤 Profile Service - handles user profiles and user management */

export interface ProfileServiceClient {
  /** user services */

  validateAccount(request: ValidateAccountRequest): Observable<ValidateAccountResponse>;

  register(request: RegisterRequest): Observable<AuthInitialResponse>;

  login(request: LoginRequest): Observable<AuthInitialResponse>;

  sendOtp(request: SendOtpRequest): Observable<SendOtpResponse>;

  verifyOtp(request: VerifyOtpRequest): Observable<VerifyOtpResponse>;

  logout(request: LogoutRequest): Observable<SendOtpResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<RefreshTokenResponse>;

  getRoles(request: EmptyRequest): Observable<GetRolesResponse>;

  /** User Management */

  getUser(request: GetUserRequest): Observable<UserResponse>;

  getBusinessUser(request: GetUserRequest): Observable<BusinessUserResponse>;

  getUserByEmail(request: GetUserByEmailRequest): Observable<GetUserByEmailResponse>;

  updateUserStatus(request: UpdateUserStatusRequest): Observable<UpdateUserStatusResponse>;

  getUserContacts(request: GetUserContactsRequest): Observable<GetUserContactsResponse>;

  updateUser(request: UpdateUserRequest): Observable<UpdateUserResponse>;

  getUserCountForOrganization(
    request: GetUserCountForOrganizationRequest,
  ): Observable<GetUserCountForOrganizationResponse>;

  getLoginHistory(request: GetLoginHistoryRequest): Observable<LoginHistoryResponse>;

  /** BUSINESS ROLES */

  createOrUpdateBusinessUserRole(
    request: CreateOrUpdateBusinessUserRoleRequest,
  ): Observable<CreateOrUpdateBusinessUserRoleResponse>;

  fetchOrganizationRoles(request: OrganizationRoleIdRequest): Observable<FetchOrganizationRolesResponse>;

  fetchOrganizationRolesCount(request: OrganizationRoleIdRequest): Observable<FetchOrganizationRolesCountResponse>;

  getStaffDetails(request: StaffDetailsRequest): Observable<StaffDetailsResponse>;

  getManyStaffDetails(request: ManyStaffDetailsRequest): Observable<ManyStaffDetailsResponse>;

  getCompanyStaffs(request: PaginatedCompanyRequest): Observable<ManyStaffDetailsResponse>;

  /** Staff Invitations */

  sendStaffInvitations(request: SendStaffInvitationsRequest): Observable<SendStaffInvitationsResponse>;

  getInvitationByCode(request: GetInvitationByCodeRequest): Observable<GetInvitationByCodeResponse>;

  markInvitationViewed(request: MarkInvitationViewedRequest): Observable<InvitationStatusResponse>;

  acceptInvitation(request: AcceptInvitationRequest): Observable<AcceptInvitationResponse>;

  declineInvitation(request: DeclineInvitationRequest): Observable<InvitationStatusResponse>;

  getInvitationsByCompany(request: PaginatedCompanyRequest): Observable<GetInvitationsByCompanyResponse>;

  adminGetUsers(request: GetUsersRequest): Observable<GetUsersResponse>;

  adminUsersAnalytics(request: AdminUsersAnalyticsRequest): Observable<AdminUsersAnalyticsResponse>;

  /** ANALYTICS */

  activeUsersCount(request: EmptyRequest): Observable<ActiveUsersCountResponse>;

  dailyActiveUsersAnalytics(request: EmptyRequest): Observable<DailyActiveUsersAnalyticsResponse>;
}

/** 👤 Profile Service - handles user profiles and user management */

export interface ProfileServiceController {
  /** user services */

  validateAccount(
    request: ValidateAccountRequest,
  ): Promise<ValidateAccountResponse> | Observable<ValidateAccountResponse> | ValidateAccountResponse;

  register(
    request: RegisterRequest,
  ): Promise<AuthInitialResponse> | Observable<AuthInitialResponse> | AuthInitialResponse;

  login(request: LoginRequest): Promise<AuthInitialResponse> | Observable<AuthInitialResponse> | AuthInitialResponse;

  sendOtp(request: SendOtpRequest): Promise<SendOtpResponse> | Observable<SendOtpResponse> | SendOtpResponse;

  verifyOtp(request: VerifyOtpRequest): Promise<VerifyOtpResponse> | Observable<VerifyOtpResponse> | VerifyOtpResponse;

  logout(request: LogoutRequest): Promise<SendOtpResponse> | Observable<SendOtpResponse> | SendOtpResponse;

  refreshToken(
    request: RefreshTokenRequest,
  ): Promise<RefreshTokenResponse> | Observable<RefreshTokenResponse> | RefreshTokenResponse;

  getRoles(request: EmptyRequest): Promise<GetRolesResponse> | Observable<GetRolesResponse> | GetRolesResponse;

  /** User Management */

  getUser(request: GetUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getBusinessUser(
    request: GetUserRequest,
  ): Promise<BusinessUserResponse> | Observable<BusinessUserResponse> | BusinessUserResponse;

  getUserByEmail(
    request: GetUserByEmailRequest,
  ): Promise<GetUserByEmailResponse> | Observable<GetUserByEmailResponse> | GetUserByEmailResponse;

  updateUserStatus(
    request: UpdateUserStatusRequest,
  ): Promise<UpdateUserStatusResponse> | Observable<UpdateUserStatusResponse> | UpdateUserStatusResponse;

  getUserContacts(
    request: GetUserContactsRequest,
  ): Promise<GetUserContactsResponse> | Observable<GetUserContactsResponse> | GetUserContactsResponse;

  updateUser(
    request: UpdateUserRequest,
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;

  getUserCountForOrganization(
    request: GetUserCountForOrganizationRequest,
  ):
    | Promise<GetUserCountForOrganizationResponse>
    | Observable<GetUserCountForOrganizationResponse>
    | GetUserCountForOrganizationResponse;

  getLoginHistory(
    request: GetLoginHistoryRequest,
  ): Promise<LoginHistoryResponse> | Observable<LoginHistoryResponse> | LoginHistoryResponse;

  /** BUSINESS ROLES */

  createOrUpdateBusinessUserRole(
    request: CreateOrUpdateBusinessUserRoleRequest,
  ):
    | Promise<CreateOrUpdateBusinessUserRoleResponse>
    | Observable<CreateOrUpdateBusinessUserRoleResponse>
    | CreateOrUpdateBusinessUserRoleResponse;

  fetchOrganizationRoles(
    request: OrganizationRoleIdRequest,
  ):
    | Promise<FetchOrganizationRolesResponse>
    | Observable<FetchOrganizationRolesResponse>
    | FetchOrganizationRolesResponse;

  fetchOrganizationRolesCount(
    request: OrganizationRoleIdRequest,
  ):
    | Promise<FetchOrganizationRolesCountResponse>
    | Observable<FetchOrganizationRolesCountResponse>
    | FetchOrganizationRolesCountResponse;

  getStaffDetails(
    request: StaffDetailsRequest,
  ): Promise<StaffDetailsResponse> | Observable<StaffDetailsResponse> | StaffDetailsResponse;

  getManyStaffDetails(
    request: ManyStaffDetailsRequest,
  ): Promise<ManyStaffDetailsResponse> | Observable<ManyStaffDetailsResponse> | ManyStaffDetailsResponse;

  getCompanyStaffs(
    request: PaginatedCompanyRequest,
  ): Promise<ManyStaffDetailsResponse> | Observable<ManyStaffDetailsResponse> | ManyStaffDetailsResponse;

  /** Staff Invitations */

  sendStaffInvitations(
    request: SendStaffInvitationsRequest,
  ): Promise<SendStaffInvitationsResponse> | Observable<SendStaffInvitationsResponse> | SendStaffInvitationsResponse;

  getInvitationByCode(
    request: GetInvitationByCodeRequest,
  ): Promise<GetInvitationByCodeResponse> | Observable<GetInvitationByCodeResponse> | GetInvitationByCodeResponse;

  markInvitationViewed(
    request: MarkInvitationViewedRequest,
  ): Promise<InvitationStatusResponse> | Observable<InvitationStatusResponse> | InvitationStatusResponse;

  acceptInvitation(
    request: AcceptInvitationRequest,
  ): Promise<AcceptInvitationResponse> | Observable<AcceptInvitationResponse> | AcceptInvitationResponse;

  declineInvitation(
    request: DeclineInvitationRequest,
  ): Promise<InvitationStatusResponse> | Observable<InvitationStatusResponse> | InvitationStatusResponse;

  getInvitationsByCompany(
    request: PaginatedCompanyRequest,
  ):
    | Promise<GetInvitationsByCompanyResponse>
    | Observable<GetInvitationsByCompanyResponse>
    | GetInvitationsByCompanyResponse;

  adminGetUsers(request: GetUsersRequest): Promise<GetUsersResponse> | Observable<GetUsersResponse> | GetUsersResponse;

  adminUsersAnalytics(
    request: AdminUsersAnalyticsRequest,
  ): Promise<AdminUsersAnalyticsResponse> | Observable<AdminUsersAnalyticsResponse> | AdminUsersAnalyticsResponse;

  /** ANALYTICS */

  activeUsersCount(
    request: EmptyRequest,
  ): Promise<ActiveUsersCountResponse> | Observable<ActiveUsersCountResponse> | ActiveUsersCountResponse;

  dailyActiveUsersAnalytics(
    request: EmptyRequest,
  ):
    | Promise<DailyActiveUsersAnalyticsResponse>
    | Observable<DailyActiveUsersAnalyticsResponse>
    | DailyActiveUsersAnalyticsResponse;
}

export function ProfileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "validateAccount",
      "register",
      "login",
      "sendOtp",
      "verifyOtp",
      "logout",
      "refreshToken",
      "getRoles",
      "getUser",
      "getBusinessUser",
      "getUserByEmail",
      "updateUserStatus",
      "getUserContacts",
      "updateUser",
      "getUserCountForOrganization",
      "getLoginHistory",
      "createOrUpdateBusinessUserRole",
      "fetchOrganizationRoles",
      "fetchOrganizationRolesCount",
      "getStaffDetails",
      "getManyStaffDetails",
      "getCompanyStaffs",
      "sendStaffInvitations",
      "getInvitationByCode",
      "markInvitationViewed",
      "acceptInvitation",
      "declineInvitation",
      "getInvitationsByCompany",
      "adminGetUsers",
      "adminUsersAnalytics",
      "activeUsersCount",
      "dailyActiveUsersAnalytics",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProfileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProfileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROFILE_SERVICE_NAME = "ProfileService";
